import { InstallmentUnitDataObject } from "../../../data";

export const sampleInstallmentUnits: (InstallmentUnitDataObject & {
  notYetUploaded?: boolean;
})[] = [
  {
    id: "installment-unit-001",
    unit_name: "Bungalow A1",
    unit_type: "Bungalow",
    unit_sub_type: "3-Bedroom",
    unit_preference: "Residential",
    measurement: "sqm",
    total_area_sqm: "150",
    bedroom: "3",
    bathroom: "3",
    toilet: "4",
    drainage: 1,
    fence: 1,
    interlocking: 0,
    gated_estate: 1,
    initial_price: "5000000",
    first_deposit: "1000000",
    is_discount: "yes",
    discount_rate: "5%",
    discount_name: "Early Bird",
    negotiation: 1,
    deposit_plans: {
      "6_months_plan": "900000",
      "12_months_plan": "450000",
      "24_months_plan": "250000",
      "48_months_plan": "125000",
    },
    document_fee: "50000",
    survey_fee: "30000",
    developmental_fee: "100000",
    other_fee: "20000",
    notYetUploaded: false,
    images: [
      { id: "img-001", path: "/empty/SampleProperty.jpeg", is_default: 1 },
      { id: "img-002", path: "/empty/SampleProperty2.jpeg", is_default: 0 },
    ],
    account_officer: "John Doe",
    is_active: "active",
  },
  {
    id: "installment-unit-002",
    unit_name: "Duplex B2",
    unit_type: "Duplex",
    unit_sub_type: "4-Bedroom",
    unit_preference: "Residential",
    measurement: "sqm",
    total_area_sqm: "200",
    bedroom: "4",
    bathroom: "4",
    toilet: "5",
    drainage: 0,
    fence: 1,
    interlocking: 1,
    gated_estate: 0,
    initial_price: "8000000",
    first_deposit: "1500000",
    is_discount: "no",
    discount_rate: undefined,
    discount_name: undefined,
    negotiation: 0,
    deposit_plans: {
      "6_months_plan": "1400000",
      "12_months_plan": "700000",
      "24_months_plan": "350000",
      "48_months_plan": "175000",
    },
    document_fee: "60000",
    survey_fee: "40000",
    developmental_fee: "120000",
    other_fee: "25000",
    notYetUploaded: true,
    images: [],
    account_officer: "Jane Smith",
    is_active: "vacant",
  },
  {
    id: "installment-unit-003",
    unit_name: "Duplex B2 (Duplicate)",
    unit_type: "Duplex",
    unit_sub_type: "4-Bedroom",
    unit_preference: "Residential",
    measurement: "sqm",
    total_area_sqm: "200",
    bedroom: "4",
    bathroom: "4",
    toilet: "5",
    drainage: 0,
    fence: 1,
    interlocking: 1,
    gated_estate: 0,
    initial_price: "8000000",
    first_deposit: "1500000",
    is_discount: "no",
    discount_rate: undefined,
    discount_name: undefined,
    negotiation: 0,
    deposit_plans: {
      "6_months_plan": "1400000",
      "12_months_plan": "700000",
      "24_months_plan": "350000",
      "48_months_plan": "175000",
    },
    document_fee: "60000",
    survey_fee: "40000",
    developmental_fee: "120000",
    other_fee: "25000",
    notYetUploaded: true,
    images: [
      { id: "img-001", path: "/empty/SampleProperty.jpeg", is_default: 0 },
      { id: "img-002", path: "/empty/SampleProperty2.jpeg", is_default: 1 },
    ],
    account_officer: "Jane Smith",
    is_active: "vacant",
  },
];
