import type { BranchProps } from "@/components/Management/Staff-And-Branches/types";

export interface BranchesPageData {
  total_branches: number;
  new_branches_count: number;
  total_properties: number;
  new_properties_count: number;
  total_staffs: number;
  new_staffs_count: number;
  branches: BranchProps[];
}

export interface StaffAndBranchPageState {
  gridView: boolean;
  total_pages: number;
  current_page: number;
  selectedState: string;
  selectedLGA: string;
  localGovernments: string[];
  loading: boolean;
  error: Error | null;
  branchesPageData: BranchesPageData;
}

export const getAllBranches = async (
  access_token: string | null
): Promise<BranchesPageData> => {
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/branches`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${access_token}`,
      },
    });
    if (!res.ok) {
      throw new Error(`Error: ${res.status}`);
    }
    const data = await res.json();
    // console.log(data);
    return data.data;
  } catch (error) {
    console.error("Error fetching tenants", error);
    throw new Error(`Error: ${error}`);
  }
};

export const getOneBranch = async (branchId: string) => {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/branches/${branchId}`,
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${"227|fO0vCGLsx556Kt1FquDwEJDg0EXXOKwr9mI1OTSdbe687fff"}`,
        },
      }
    );
    if (!res.ok) {
      throw new Error(`Error: ${res.status}`);
    }
    const data = await res.json();
    console.log(data);
    return data;
  } catch (error) {
    console.error("Error fetching tenants", error);
    throw new Error(`Error: ${error}`);
  }
};

export const testBranches: BranchProps[] = [
  {
    id: 1,
    branch_title: "Valeant Pharmaceuticals North America LLC",
    branch_full_address: "PO Box 5475",
    avatar: "http://dummyimage.com/228x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Linnea Raynor",
    staff_count: 18,
    property_count: 76,
    unit_count: 18,
  },
  {
    id: 2,
    branch_title: "DLC Laboratories, Inc",
    branch_full_address: "PO Box 15486",
    avatar: "http://dummyimage.com/112x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Jeanette Skelding",
    staff_count: 36,
    property_count: 49,
    unit_count: 45,
  },
  {
    id: 3,
    branch_title: "Hospira, Inc.",
    branch_full_address: "Suite 46",
    avatar: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Dacy Gratton",
    staff_count: 41,
    property_count: 2,
    unit_count: 91,
  },
  {
    id: 4,
    branch_title: "General Injectables & Vaccines, Inc",
    branch_full_address: "Room 1427",
    avatar: "http://dummyimage.com/157x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Emyle Sends",
    staff_count: 31,
    property_count: 67,
    unit_count: 71,
  },
  {
    id: 5,
    branch_title: "ITC Medical Supplies",
    branch_full_address: "Apt 1812",
    avatar: "http://dummyimage.com/220x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Luella Plott",
    staff_count: 95,
    property_count: 81,
    unit_count: 72,
  },
  {
    id: 6,
    branch_title: "Nelco Laboratories, Inc.",
    branch_full_address: "PO Box 84916",
    avatar: "http://dummyimage.com/236x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Cornelius Witnall",
    staff_count: 26,
    property_count: 53,
    unit_count: 99,
  },
  {
    id: 7,
    branch_title: "Proficient Rx LP",
    branch_full_address: "PO Box 26900",
    avatar: null,
    manager_avatar: null,
    manager_name: "Emmott Lasty",
    staff_count: 66,
    property_count: 89,
    unit_count: 35,
  },
  {
    id: 8,
    branch_title: "Perrigo New York Inc",
    branch_full_address: "Apt 1116",
    avatar: "http://dummyimage.com/168x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Domenic Brombell",
    staff_count: 92,
    property_count: 70,
    unit_count: 82,
  },
  {
    id: 9,
    branch_title: "Nelco Laboratories, Inc.",
    branch_full_address: "Apt 614",
    avatar: "http://dummyimage.com/155x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Bari Ogborne",
    staff_count: 90,
    property_count: 41,
    unit_count: 48,
  },
  {
    id: 10,
    branch_title: "Laboratorios Genesse SL",
    branch_full_address: "Room 56",
    avatar: null,
    manager_avatar: null,
    manager_name: "Jerrilee Hutten",
    staff_count: 7,
    property_count: 71,
    unit_count: 14,
  },
  {
    id: 11,
    branch_title: "CVS PHARMACY",
    branch_full_address: "3rd Floor",
    avatar: "http://dummyimage.com/136x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Livvyy Have",
    staff_count: 100,
    property_count: 90,
    unit_count: 32,
  },
  {
    id: 12,
    branch_title: "NSE Products, Inc.",
    branch_full_address: "PO Box 36911",
    avatar: null,
    manager_avatar: null,
    manager_name: "Diena Rivalland",
    staff_count: 1,
    property_count: 18,
    unit_count: 72,
  },
  {
    id: 13,
    branch_title: "Greenbrier International",
    branch_full_address: "3rd Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Cliff Mitcheson",
    staff_count: 67,
    property_count: 77,
    unit_count: 54,
  },
  {
    id: 14,
    branch_title: "Unifirst First Aid Corporation",
    branch_full_address: "2nd Floor",
    avatar: "http://dummyimage.com/105x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Lee Clissell",
    staff_count: 8,
    property_count: 84,
    unit_count: 87,
  },
  {
    id: 15,
    branch_title: "Clinical Solutions Wholesale",
    branch_full_address: "Suite 41",
    avatar: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Andrei Tottman",
    staff_count: 71,
    property_count: 45,
    unit_count: 69,
  },
  {
    id: 16,
    branch_title: "Takeda Pharmaceuticals America, Inc.",
    branch_full_address: "18th Floor",
    avatar: "http://dummyimage.com/250x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Demetris Tetsall",
    staff_count: 15,
    property_count: 70,
    unit_count: 7,
  },
  {
    id: 17,
    branch_title: "European Perfume Works Co. L.L.C",
    branch_full_address: "Apt 581",
    avatar: null,
    manager_avatar: null,
    manager_name: "Lorinda Bartolomieu",
    staff_count: 63,
    property_count: 17,
    unit_count: 3,
  },
  {
    id: 18,
    branch_title: "Dr. Reddy's Laboratories Limited",
    branch_full_address: "PO Box 63826",
    avatar: "http://dummyimage.com/111x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Noella Coldrick",
    staff_count: 46,
    property_count: 45,
    unit_count: 77,
  },
  {
    id: 19,
    branch_title: "Parfums Christian Dior",
    branch_full_address: "Suite 70",
    avatar: "http://dummyimage.com/162x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Olvan Cow",
    staff_count: 79,
    property_count: 53,
    unit_count: 54,
  },
  {
    id: 20,
    branch_title: "Allergy Laboratories, Inc.",
    branch_full_address: "PO Box 44139",
    avatar: null,
    manager_avatar: null,
    manager_name: "Moise Ainley",
    staff_count: 87,
    property_count: 32,
    unit_count: 25,
  },
  {
    id: 21,
    branch_title: "Western Family Foods, Inc",
    branch_full_address: "Suite 22",
    avatar: "http://dummyimage.com/166x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Dall Simondson",
    staff_count: 53,
    property_count: 18,
    unit_count: 52,
  },
  {
    id: 22,
    branch_title: "Jazz Pharmaceuticals Commercial Corp.",
    branch_full_address: "Suite 63",
    avatar: null,
    manager_avatar: null,
    manager_name: "Dolley Fockes",
    staff_count: 85,
    property_count: 38,
    unit_count: 79,
  },
  {
    id: 23,
    branch_title: "Hospira, Inc.",
    branch_full_address: "Suite 65",
    avatar: "http://dummyimage.com/217x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Marieann Botright",
    staff_count: 95,
    property_count: 91,
    unit_count: 5,
  },
  {
    id: 24,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "Apt 1956",
    avatar: null,
    manager_avatar: null,
    manager_name: "Fitzgerald Sandry",
    staff_count: 24,
    property_count: 99,
    unit_count: 73,
  },
  {
    id: 25,
    branch_title: "Major Pharmeceuticals",
    branch_full_address: "13th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Simona Shegog",
    staff_count: 29,
    property_count: 79,
    unit_count: 17,
  },
  {
    id: 26,
    branch_title: "Glenmark Generics Inc. USA",
    branch_full_address: "Room 1726",
    avatar: null,
    manager_avatar: null,
    manager_name: "Andrea Camock",
    staff_count: 82,
    property_count: 5,
    unit_count: 89,
  },
  {
    id: 27,
    branch_title: "Nelco Laboratories, Inc.",
    branch_full_address: "18th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Torrin Blofield",
    staff_count: 96,
    property_count: 15,
    unit_count: 6,
  },
  {
    id: 28,
    branch_title: "Shopko",
    branch_full_address: "Room 1959",
    avatar: "http://dummyimage.com/103x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Townsend Madoc-Jones",
    staff_count: 47,
    property_count: 70,
    unit_count: 1,
  },
  {
    id: 29,
    branch_title: "Janssen Pharmaceuticals, Inc.",
    branch_full_address: "Room 1975",
    avatar: "http://dummyimage.com/223x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Margalit Hummerston",
    staff_count: 27,
    property_count: 20,
    unit_count: 92,
  },
  {
    id: 30,
    branch_title: "American Sales Company",
    branch_full_address: "Room 1752",
    avatar: "http://dummyimage.com/238x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Chester Rushman",
    staff_count: 100,
    property_count: 2,
    unit_count: 51,
  },
  {
    id: 31,
    branch_title: "KAS Direct LLC dba BabyGanics",
    branch_full_address: "Suite 15",
    avatar: null,
    manager_avatar: null,
    manager_name: "Gaston Macveigh",
    staff_count: 70,
    property_count: 43,
    unit_count: 23,
  },
  {
    id: 32,
    branch_title: "Nelco Laboratories, Inc.",
    branch_full_address: "17th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Ardene Domney",
    staff_count: 82,
    property_count: 46,
    unit_count: 83,
  },
  {
    id: 33,
    branch_title: "Internationa Nature Nutraceuticals, Inc",
    branch_full_address: "Apt 1335",
    avatar: "http://dummyimage.com/177x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Charmane Matthias",
    staff_count: 48,
    property_count: 9,
    unit_count: 35,
  },
  {
    id: 34,
    branch_title: "Supervalu Inc",
    branch_full_address: "Room 1041",
    avatar: null,
    manager_avatar: null,
    manager_name: "Clarance Shiell",
    staff_count: 47,
    property_count: 6,
    unit_count: 13,
  },
  {
    id: 35,
    branch_title: "Novartis Pharmaceuticals Corporation",
    branch_full_address: "Room 683",
    avatar: "http://dummyimage.com/125x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Moritz Dubarry",
    staff_count: 74,
    property_count: 17,
    unit_count: 47,
  },
  {
    id: 36,
    branch_title: "Forces of Nature",
    branch_full_address: "6th Floor",
    avatar: "http://dummyimage.com/186x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Joanie Draayer",
    staff_count: 87,
    property_count: 75,
    unit_count: 58,
  },
  {
    id: 37,
    branch_title: "REMEDYREPACK INC.",
    branch_full_address: "Apt 229",
    avatar: "http://dummyimage.com/219x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Bartie Gimbrett",
    staff_count: 49,
    property_count: 62,
    unit_count: 33,
  },
  {
    id: 38,
    branch_title: "Rite Aid",
    branch_full_address: "Suite 59",
    avatar: "http://dummyimage.com/121x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Birk Rigard",
    staff_count: 59,
    property_count: 38,
    unit_count: 24,
  },
  {
    id: 39,
    branch_title: "Lantern Enterprises Ltd",
    branch_full_address: "Suite 32",
    avatar: null,
    manager_avatar: null,
    manager_name: "Isiahi Hastewell",
    staff_count: 11,
    property_count: 94,
    unit_count: 96,
  },
  {
    id: 40,
    branch_title: "Bio-Germ Protection LLC",
    branch_full_address: "PO Box 71922",
    avatar: "http://dummyimage.com/136x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Hale Ableson",
    staff_count: 86,
    property_count: 56,
    unit_count: 62,
  },
  {
    id: 41,
    branch_title: "Purminerals",
    branch_full_address: "8th Floor",
    avatar: "http://dummyimage.com/191x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Kellsie Maudlin",
    staff_count: 31,
    property_count: 37,
    unit_count: 12,
  },
  {
    id: 42,
    branch_title: "AUSTIN PHARMACEUTICALS, LLC",
    branch_full_address: "17th Floor",
    avatar: "http://dummyimage.com/124x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Marguerite Roxbrough",
    staff_count: 70,
    property_count: 69,
    unit_count: 10,
  },
  {
    id: 43,
    branch_title: "Wockhardt USA LLC.",
    branch_full_address: "Suite 53",
    avatar: "http://dummyimage.com/194x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Catha Lyons",
    staff_count: 54,
    property_count: 87,
    unit_count: 85,
  },
  {
    id: 44,
    branch_title: "AllerQuest LLC",
    branch_full_address: "Suite 43",
    avatar: "http://dummyimage.com/235x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Mandie Syphus",
    staff_count: 80,
    property_count: 10,
    unit_count: 36,
  },
  {
    id: 45,
    branch_title: "LEO Pharma Inc.",
    branch_full_address: "Suite 29",
    avatar: null,
    manager_avatar: null,
    manager_name: "Daria Haysman",
    staff_count: 35,
    property_count: 47,
    unit_count: 51,
  },
  {
    id: 46,
    branch_title: "JHP Pharmaceuticals LLC",
    branch_full_address: "Room 277",
    avatar: "http://dummyimage.com/155x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Annis Care",
    staff_count: 12,
    property_count: 50,
    unit_count: 22,
  },
  {
    id: 47,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "Suite 28",
    avatar: "http://dummyimage.com/153x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Torry Slate",
    staff_count: 18,
    property_count: 21,
    unit_count: 14,
  },
  {
    id: 48,
    branch_title: "Alternative Pharmacy",
    branch_full_address: "Apt 483",
    avatar: null,
    manager_avatar: null,
    manager_name: "Tootsie Margrett",
    staff_count: 55,
    property_count: 98,
    unit_count: 75,
  },
  {
    id: 49,
    branch_title: "B. Braun Medical Inc.",
    branch_full_address: "17th Floor",
    avatar: "http://dummyimage.com/124x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Ferrel Wellstood",
    staff_count: 95,
    property_count: 19,
    unit_count: 59,
  },
  {
    id: 50,
    branch_title: "Meijer Distribution, Inc",
    branch_full_address: "PO Box 31218",
    avatar: "http://dummyimage.com/148x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Melissa Grimsdyke",
    staff_count: 23,
    property_count: 27,
    unit_count: 92,
  },
  {
    id: 51,
    branch_title: "Halim Pharm Ltd",
    branch_full_address: "1st Floor",
    avatar: "http://dummyimage.com/186x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Bud Uc",
    staff_count: 37,
    property_count: 88,
    unit_count: 18,
  },
  {
    id: 52,
    branch_title: "Jayco Industrial Supply Inc",
    branch_full_address: "Suite 42",
    avatar: null,
    manager_avatar: null,
    manager_name: "Corney Barlow",
    staff_count: 11,
    property_count: 55,
    unit_count: 91,
  },
  {
    id: 53,
    branch_title: "King Bio Inc.",
    branch_full_address: "1st Floor",
    avatar: "http://dummyimage.com/123x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Adrienne Buckney",
    staff_count: 2,
    property_count: 97,
    unit_count: 11,
  },
  {
    id: 54,
    branch_title: "Bel-Art Products",
    branch_full_address: "Apt 1860",
    avatar: null,
    manager_avatar: null,
    manager_name: "Ron Cortez",
    staff_count: 1,
    property_count: 79,
    unit_count: 72,
  },
  {
    id: 55,
    branch_title: "Cardinal Health",
    branch_full_address: "Room 1046",
    avatar: null,
    manager_avatar: null,
    manager_name: "Candra Rubert",
    staff_count: 47,
    property_count: 62,
    unit_count: 82,
  },
  {
    id: 56,
    branch_title: "Dynarex Corporation",
    branch_full_address: "Room 1645",
    avatar: "http://dummyimage.com/242x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Selle Hebblewhite",
    staff_count: 64,
    property_count: 24,
    unit_count: 87,
  },
  {
    id: 57,
    branch_title: "Sunstar Americas, Inc.",
    branch_full_address: "Room 56",
    avatar: null,
    manager_avatar: null,
    manager_name: "Karoly Thunders",
    staff_count: 90,
    property_count: 96,
    unit_count: 57,
  },
  {
    id: 58,
    branch_title: "Med-Health Pharma, LLC",
    branch_full_address: "5th Floor",
    avatar: "http://dummyimage.com/125x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Elsy Fahrenbacher",
    staff_count: 34,
    property_count: 98,
    unit_count: 28,
  },
  {
    id: 59,
    branch_title: "H.J. Harkins Company, Inc.",
    branch_full_address: "1st Floor",
    avatar: "http://dummyimage.com/150x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Regen Quinnell",
    staff_count: 29,
    property_count: 82,
    unit_count: 39,
  },
  {
    id: 60,
    branch_title: "Safeway",
    branch_full_address: "PO Box 37362",
    avatar: "http://dummyimage.com/166x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Hanson Hallifax",
    staff_count: 30,
    property_count: 11,
    unit_count: 21,
  },
  {
    id: 61,
    branch_title: "Keltman Pharmaceuticals Inc.",
    branch_full_address: "Room 66",
    avatar: "http://dummyimage.com/103x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Adrienne Bonicelli",
    staff_count: 62,
    property_count: 17,
    unit_count: 28,
  },
  {
    id: 62,
    branch_title: "Bolero Home Decor, Inc.",
    branch_full_address: "Suite 53",
    avatar: "http://dummyimage.com/134x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Gaby Haith",
    staff_count: 45,
    property_count: 13,
    unit_count: 6,
  },
  {
    id: 63,
    branch_title: "Apotheca Company",
    branch_full_address: "Suite 79",
    avatar: "http://dummyimage.com/184x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Michal MacQuaker",
    staff_count: 46,
    property_count: 74,
    unit_count: 54,
  },
  {
    id: 64,
    branch_title: "Mylan Institutional LLC",
    branch_full_address: "Room 18",
    avatar: "http://dummyimage.com/249x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Letisha Danbye",
    staff_count: 76,
    property_count: 74,
    unit_count: 97,
  },
  {
    id: 65,
    branch_title: "Antigen Laboratories, Inc.",
    branch_full_address: "Room 54",
    avatar: null,
    manager_avatar: null,
    manager_name: "Hyacintha Francecione",
    staff_count: 55,
    property_count: 74,
    unit_count: 92,
  },
  {
    id: 66,
    branch_title: "West-ward Pharmaceutical Corp",
    branch_full_address: "9th Floor",
    avatar: "http://dummyimage.com/115x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Ema Rudham",
    staff_count: 79,
    property_count: 36,
    unit_count: 28,
  },
  {
    id: 67,
    branch_title: "STAT Rx USA LLC",
    branch_full_address: "19th Floor",
    avatar: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Floris Camois",
    staff_count: 73,
    property_count: 41,
    unit_count: 16,
  },
  {
    id: 68,
    branch_title: "Eli Lilly and Company",
    branch_full_address: "19th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Rosie Guise",
    staff_count: 10,
    property_count: 31,
    unit_count: 64,
  },
  {
    id: 69,
    branch_title: "Dolgencorp Inc",
    branch_full_address: "Apt 1018",
    avatar: "http://dummyimage.com/209x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Benjamin Calfe",
    staff_count: 27,
    property_count: 72,
    unit_count: 1,
  },
  {
    id: 70,
    branch_title: "Keltman Pharmaceuticals Inc.",
    branch_full_address: "17th Floor",
    avatar: "http://dummyimage.com/157x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Clint Nother",
    staff_count: 75,
    property_count: 84,
    unit_count: 1,
  },
  {
    id: 71,
    branch_title: "Hyvee",
    branch_full_address: "Room 1956",
    avatar: null,
    manager_avatar: null,
    manager_name: "Daune McCard",
    staff_count: 27,
    property_count: 73,
    unit_count: 76,
  },
  {
    id: 72,
    branch_title: "Hospira, Inc.",
    branch_full_address: "Suite 23",
    avatar: "http://dummyimage.com/186x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Amii Basey",
    staff_count: 16,
    property_count: 40,
    unit_count: 90,
  },
  {
    id: 73,
    branch_title: "Allergy Laboratories, Inc.",
    branch_full_address: "PO Box 23992",
    avatar: "http://dummyimage.com/170x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Cindi Grassin",
    staff_count: 10,
    property_count: 3,
    unit_count: 36,
  },
  {
    id: 74,
    branch_title: "Safeway",
    branch_full_address: "Apt 1643",
    avatar: "http://dummyimage.com/142x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Susana Hinstridge",
    staff_count: 12,
    property_count: 33,
    unit_count: 46,
  },
  {
    id: 75,
    branch_title: "Uriel Pharmacy Inc.",
    branch_full_address: "Suite 65",
    avatar: "http://dummyimage.com/178x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Millisent Seager",
    staff_count: 90,
    property_count: 80,
    unit_count: 53,
  },
  {
    id: 76,
    branch_title: "Vivier Pharma, Inc.",
    branch_full_address: "Suite 47",
    avatar: "http://dummyimage.com/184x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Jacquelynn Yaknov",
    staff_count: 8,
    property_count: 36,
    unit_count: 5,
  },
  {
    id: 77,
    branch_title: "Bonita Pharmaceuticals LLC",
    branch_full_address: "Apt 1738",
    avatar: "http://dummyimage.com/143x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Neda Knowles",
    staff_count: 26,
    property_count: 23,
    unit_count: 97,
  },
  {
    id: 78,
    branch_title: "Pfizer Laboratories Div Pfizer Inc",
    branch_full_address: "Room 806",
    avatar: "http://dummyimage.com/197x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Sawyere Goodger",
    staff_count: 47,
    property_count: 2,
    unit_count: 36,
  },
  {
    id: 79,
    branch_title: "ALK-Abello, Inc.",
    branch_full_address: "Apt 606",
    avatar: "http://dummyimage.com/215x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Madeline Hallet",
    staff_count: 36,
    property_count: 48,
    unit_count: 79,
  },
  {
    id: 80,
    branch_title: "Delta Brands Inc",
    branch_full_address: "PO Box 84828",
    avatar: null,
    manager_avatar: null,
    manager_name: "Carissa Castelin",
    staff_count: 52,
    property_count: 56,
    unit_count: 92,
  },
  {
    id: 81,
    branch_title: "Jubilant HollisterStier LLC",
    branch_full_address: "16th Floor",
    avatar: "http://dummyimage.com/154x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Stephanus Franklen",
    staff_count: 26,
    property_count: 49,
    unit_count: 57,
  },
  {
    id: 82,
    branch_title: "Nelco Laboratories, Inc.",
    branch_full_address: "Suite 38",
    avatar: null,
    manager_avatar: null,
    manager_name: "Pauline Hardington",
    staff_count: 77,
    property_count: 3,
    unit_count: 91,
  },
  {
    id: 83,
    branch_title: "Cardinal Health",
    branch_full_address: "11th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Beverley Oolahan",
    staff_count: 94,
    property_count: 25,
    unit_count: 51,
  },
  {
    id: 84,
    branch_title: "Newton Laboratories, Inc.",
    branch_full_address: "Suite 17",
    avatar: "http://dummyimage.com/185x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Ethelyn Prahm",
    staff_count: 78,
    property_count: 56,
    unit_count: 59,
  },
  {
    id: 85,
    branch_title: "UDL Laboratories, Inc.",
    branch_full_address: "20th Floor",
    avatar: "http://dummyimage.com/225x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Sonnie Selcraig",
    staff_count: 99,
    property_count: 41,
    unit_count: 24,
  },
  {
    id: 86,
    branch_title: "Sanum Kehlbeck GmbH & Co. KG",
    branch_full_address: "Apt 250",
    avatar: "http://dummyimage.com/203x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Tammi Pennino",
    staff_count: 36,
    property_count: 29,
    unit_count: 16,
  },
  {
    id: 87,
    branch_title: "AvKARE, Inc.",
    branch_full_address: "1st Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Claude Fourman",
    staff_count: 25,
    property_count: 28,
    unit_count: 89,
  },
  {
    id: 88,
    branch_title: "Carilion Materials Management",
    branch_full_address: "Apt 297",
    avatar: "http://dummyimage.com/185x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Hyacinthia Rosenstock",
    staff_count: 23,
    property_count: 8,
    unit_count: 52,
  },
  {
    id: 89,
    branch_title: "Hello Products LLC",
    branch_full_address: "PO Box 25507",
    avatar: "http://dummyimage.com/195x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Mile Dagless",
    staff_count: 15,
    property_count: 21,
    unit_count: 95,
  },
  {
    id: 90,
    branch_title: "Oberon Cosmetic Co., Ltd.",
    branch_full_address: "PO Box 27560",
    avatar: null,
    manager_avatar: null,
    manager_name: "Kyrstin Hierro",
    staff_count: 9,
    property_count: 47,
    unit_count: 14,
  },
  {
    id: 91,
    branch_title: "Apotheca Company",
    branch_full_address: "PO Box 82769",
    avatar: "http://dummyimage.com/233x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Gil Knewstub",
    staff_count: 100,
    property_count: 11,
    unit_count: 39,
  },
  {
    id: 92,
    branch_title: "Pedinol Pharmacal, Inc.",
    branch_full_address: "Apt 99",
    avatar: "http://dummyimage.com/109x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Yoko Mandell",
    staff_count: 69,
    property_count: 1,
    unit_count: 43,
  },
  {
    id: 93,
    branch_title: "Antigen Laboratories, Inc.",
    branch_full_address: "PO Box 22549",
    avatar: null,
    manager_avatar: null,
    manager_name: "Akim Doerren",
    staff_count: 97,
    property_count: 65,
    unit_count: 77,
  },
  {
    id: 94,
    branch_title: "McKesson",
    branch_full_address: "1st Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Essy Bannon",
    staff_count: 87,
    property_count: 3,
    unit_count: 60,
  },
  {
    id: 95,
    branch_title: "Neutrogena Corporation",
    branch_full_address: "Room 1661",
    avatar: "http://dummyimage.com/166x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Karim Bax",
    staff_count: 56,
    property_count: 99,
    unit_count: 98,
  },
  {
    id: 96,
    branch_title: "American Health Packaging",
    branch_full_address: "PO Box 47248",
    avatar: null,
    manager_avatar: null,
    manager_name: "Sebastian Tressler",
    staff_count: 11,
    property_count: 49,
    unit_count: 13,
  },
  {
    id: 97,
    branch_title: "Washington Homeopathic Products",
    branch_full_address: "19th Floor",
    avatar: "http://dummyimage.com/168x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Mair Covotto",
    staff_count: 4,
    property_count: 78,
    unit_count: 66,
  },
  {
    id: 98,
    branch_title: "UCB, Inc.",
    branch_full_address: "PO Box 34225",
    avatar: null,
    manager_avatar: null,
    manager_name: "Shermy Mulrooney",
    staff_count: 23,
    property_count: 52,
    unit_count: 53,
  },
  {
    id: 99,
    branch_title: "Mylan Pharmaceuticals Inc.",
    branch_full_address: "PO Box 39870",
    avatar: "http://dummyimage.com/131x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Beilul Vakhrushev",
    staff_count: 80,
    property_count: 93,
    unit_count: 80,
  },
  {
    id: 100,
    branch_title: "SHISEIDO CO., LTD.",
    branch_full_address: "19th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Lanny Gavagan",
    staff_count: 99,
    property_count: 93,
    unit_count: 2,
  },
  {
    id: 101,
    branch_title: "TYA Pharmaceuticals",
    branch_full_address: "6th Floor",
    avatar: "http://dummyimage.com/144x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Daron Philpotts",
    staff_count: 64,
    property_count: 33,
    unit_count: 49,
  },
  {
    id: 102,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "Room 325",
    avatar: null,
    manager_avatar: null,
    manager_name: "Marta Bullivant",
    staff_count: 12,
    property_count: 15,
    unit_count: 16,
  },
  {
    id: 103,
    branch_title: "Liberty Pharmaceuticals, Inc.",
    branch_full_address: "14th Floor",
    avatar: "http://dummyimage.com/175x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Othello Prene",
    staff_count: 83,
    property_count: 15,
    unit_count: 70,
  },
  {
    id: 104,
    branch_title: "Uriel Pharmacy Inc.",
    branch_full_address: "Room 786",
    avatar: "http://dummyimage.com/159x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Archy Whisker",
    staff_count: 9,
    property_count: 86,
    unit_count: 40,
  },
  {
    id: 105,
    branch_title: "Industrias Lavin de Mexico S.A. de C.V.",
    branch_full_address: "Suite 87",
    avatar: null,
    manager_avatar: null,
    manager_name: "Teador Bearsmore",
    staff_count: 85,
    property_count: 49,
    unit_count: 77,
  },
  {
    id: 106,
    branch_title: "BRANDERS.COM, INC.",
    branch_full_address: "Suite 14",
    avatar: "http://dummyimage.com/143x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Thedric Tibbits",
    staff_count: 90,
    property_count: 95,
    unit_count: 54,
  },
  {
    id: 107,
    branch_title: "Clinical Solutions Wholesale",
    branch_full_address: "Suite 59",
    avatar: null,
    manager_avatar: null,
    manager_name: "Hailey Domone",
    staff_count: 8,
    property_count: 18,
    unit_count: 30,
  },
  {
    id: 108,
    branch_title: "SKINFOOD CO., LTD.",
    branch_full_address: "Room 735",
    avatar: "http://dummyimage.com/232x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Stevena Gallegos",
    staff_count: 44,
    property_count: 79,
    unit_count: 50,
  },
  {
    id: 109,
    branch_title: "Allergy Laboratories, Inc.",
    branch_full_address: "19th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Guthry Jeness",
    staff_count: 20,
    property_count: 90,
    unit_count: 30,
  },
  {
    id: 110,
    branch_title: "Supervalu Inc",
    branch_full_address: "Apt 1282",
    avatar: "http://dummyimage.com/146x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Noak Pittle",
    staff_count: 15,
    property_count: 91,
    unit_count: 60,
  },
  {
    id: 111,
    branch_title: "H E B",
    branch_full_address: "PO Box 63342",
    avatar: "http://dummyimage.com/229x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Demetris Allcoat",
    staff_count: 12,
    property_count: 28,
    unit_count: 9,
  },
  {
    id: 112,
    branch_title: "Energique, Inc.",
    branch_full_address: "Apt 756",
    avatar: null,
    manager_avatar: null,
    manager_name: "Royall Macer",
    staff_count: 34,
    property_count: 100,
    unit_count: 56,
  },
  {
    id: 113,
    branch_title: "Qualitest Pharmaceuticals",
    branch_full_address: "PO Box 67955",
    avatar: "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Donalt Couvet",
    staff_count: 32,
    property_count: 81,
    unit_count: 33,
  },
  {
    id: 114,
    branch_title: "Lil' Drug Store Products, Inc.",
    branch_full_address: "Suite 73",
    avatar: "http://dummyimage.com/153x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Modesta Deinhardt",
    staff_count: 100,
    property_count: 100,
    unit_count: 92,
  },
  {
    id: 115,
    branch_title: "GIOVANNI COSMETICS INC",
    branch_full_address: "PO Box 7530",
    avatar: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Bryant Hulme",
    staff_count: 40,
    property_count: 5,
    unit_count: 18,
  },
  {
    id: 116,
    branch_title: "Nelco Laboratories, Inc.",
    branch_full_address: "19th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Cleve Licas",
    staff_count: 33,
    property_count: 32,
    unit_count: 60,
  },
  {
    id: 117,
    branch_title: "American Health Packaging",
    branch_full_address: "17th Floor",
    avatar: "http://dummyimage.com/239x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Isacco Boichat",
    staff_count: 33,
    property_count: 44,
    unit_count: 68,
  },
  {
    id: 118,
    branch_title: "CBI Laboratories, Inc",
    branch_full_address: "Room 692",
    avatar: "http://dummyimage.com/239x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Reid Chesterman",
    staff_count: 47,
    property_count: 78,
    unit_count: 92,
  },
  {
    id: 119,
    branch_title: "Antigen Laboratories, Inc.",
    branch_full_address: "Room 1836",
    avatar: null,
    manager_avatar: null,
    manager_name: "Demott Onge",
    staff_count: 37,
    property_count: 60,
    unit_count: 2,
  },
  {
    id: 120,
    branch_title: "The Akshay Wellness Group, Inc.",
    branch_full_address: "Apt 1891",
    avatar: "http://dummyimage.com/158x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Hardy Tuberfield",
    staff_count: 85,
    property_count: 86,
    unit_count: 63,
  },
  {
    id: 121,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "Suite 95",
    avatar: "http://dummyimage.com/142x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Lucian Goddard",
    staff_count: 46,
    property_count: 9,
    unit_count: 81,
  },
  {
    id: 122,
    branch_title: "A-S Medication Solutions LLC",
    branch_full_address: "Suite 73",
    avatar: "http://dummyimage.com/234x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Standford Hazeldene",
    staff_count: 90,
    property_count: 30,
    unit_count: 94,
  },
  {
    id: 123,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "PO Box 79324",
    avatar: "http://dummyimage.com/145x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Jennifer Hebble",
    staff_count: 34,
    property_count: 53,
    unit_count: 77,
  },
  {
    id: 124,
    branch_title: "Supervalu Inc",
    branch_full_address: "Apt 1259",
    avatar: "http://dummyimage.com/129x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Bonnee Kilfedder",
    staff_count: 25,
    property_count: 85,
    unit_count: 84,
  },
  {
    id: 125,
    branch_title: "E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.",
    branch_full_address: "19th Floor",
    avatar: "http://dummyimage.com/248x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Adamo Ivanenko",
    staff_count: 88,
    property_count: 64,
    unit_count: 63,
  },
  {
    id: 126,
    branch_title: "Rebel Distributors Corp",
    branch_full_address: "9th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Esteban McCumesky",
    staff_count: 50,
    property_count: 92,
    unit_count: 97,
  },
  {
    id: 127,
    branch_title: "Henry Scein Inc",
    branch_full_address: "Suite 70",
    avatar: "http://dummyimage.com/215x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Melony Warke",
    staff_count: 3,
    property_count: 28,
    unit_count: 82,
  },
  {
    id: 128,
    branch_title: "Legacy Pharmaceutical Packaging",
    branch_full_address: "Room 1256",
    avatar: null,
    manager_avatar: null,
    manager_name: "Brina Cudworth",
    staff_count: 25,
    property_count: 52,
    unit_count: 61,
  },
  {
    id: 129,
    branch_title: "Welding & Therapy Service Inc.",
    branch_full_address: "Apt 1730",
    avatar: null,
    manager_avatar: null,
    manager_name: "Zelig Phettis",
    staff_count: 35,
    property_count: 96,
    unit_count: 73,
  },
  {
    id: 130,
    branch_title: "Mountain Top Labs, LLC",
    branch_full_address: "PO Box 90235",
    avatar: null,
    manager_avatar: null,
    manager_name: "Cazzie Boycott",
    staff_count: 22,
    property_count: 73,
    unit_count: 20,
  },
  {
    id: 131,
    branch_title: "NCS HealthCare of KY, Inc dba Vangard Labs",
    branch_full_address: "9th Floor",
    avatar: "http://dummyimage.com/245x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Noreen Mattecot",
    staff_count: 97,
    property_count: 1,
    unit_count: 12,
  },
  {
    id: 132,
    branch_title: "Acme United Corporation",
    branch_full_address: "Apt 158",
    avatar: "http://dummyimage.com/223x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Bamby Taberer",
    staff_count: 88,
    property_count: 53,
    unit_count: 40,
  },
  {
    id: 133,
    branch_title: "Braintree Laboratories, Inc.",
    branch_full_address: "Suite 92",
    avatar: "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Claudius Okenden",
    staff_count: 85,
    property_count: 41,
    unit_count: 74,
  },
  {
    id: 134,
    branch_title: "HyVee Inc",
    branch_full_address: "Suite 11",
    avatar: null,
    manager_avatar: null,
    manager_name: "Betteann Buesden",
    staff_count: 3,
    property_count: 48,
    unit_count: 6,
  },
  {
    id: 135,
    branch_title: "WOONSOCKET PRESCRIPTION CENTER,INCORPORATED",
    branch_full_address: "13th Floor",
    avatar: "http://dummyimage.com/105x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Kelsey Guntrip",
    staff_count: 22,
    property_count: 36,
    unit_count: 11,
  },
  {
    id: 136,
    branch_title: "REMEDYREPACK INC.",
    branch_full_address: "PO Box 28771",
    avatar: "http://dummyimage.com/246x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Obidiah Tease",
    staff_count: 91,
    property_count: 49,
    unit_count: 51,
  },
  {
    id: 137,
    branch_title: "Insight Pharmaceuticals",
    branch_full_address: "Room 1780",
    avatar: null,
    manager_avatar: null,
    manager_name: "Lyndy Scherme",
    staff_count: 88,
    property_count: 73,
    unit_count: 37,
  },
  {
    id: 138,
    branch_title: "Preferred Pharmaceuticals, Inc.",
    branch_full_address: "Suite 25",
    avatar: "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Adolphe Powley",
    staff_count: 27,
    property_count: 79,
    unit_count: 90,
  },
  {
    id: 139,
    branch_title: "HOMEOLAB USA INC",
    branch_full_address: "PO Box 67113",
    avatar: null,
    manager_avatar: null,
    manager_name: "Paddie Whitley",
    staff_count: 45,
    property_count: 85,
    unit_count: 92,
  },
  {
    id: 140,
    branch_title: "Watson Laboratories, Inc.",
    branch_full_address: "15th Floor",
    avatar: "http://dummyimage.com/174x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Geno Mutlow",
    staff_count: 69,
    property_count: 51,
    unit_count: 19,
  },
  {
    id: 141,
    branch_title: "Preferred Pharmaceuticals, Inc.",
    branch_full_address: "8th Floor",
    avatar: "http://dummyimage.com/158x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Barton Hambidge",
    staff_count: 62,
    property_count: 23,
    unit_count: 70,
  },
  {
    id: 142,
    branch_title: "Preferred Pharmaceuticals, Inc",
    branch_full_address: "Suite 47",
    avatar: null,
    manager_avatar: null,
    manager_name: "Levi Gambles",
    staff_count: 94,
    property_count: 39,
    unit_count: 78,
  },
  {
    id: 143,
    branch_title: "Natural Health Supply",
    branch_full_address: "11th Floor",
    avatar: "http://dummyimage.com/195x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Darda Sybbe",
    staff_count: 79,
    property_count: 87,
    unit_count: 94,
  },
  {
    id: 144,
    branch_title: "REMEDYREPACK INC.",
    branch_full_address: "Room 1222",
    avatar: "http://dummyimage.com/161x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Peadar Rolfini",
    staff_count: 68,
    property_count: 20,
    unit_count: 24,
  },
  {
    id: 145,
    branch_title: "Roerig",
    branch_full_address: "Suite 98",
    avatar: null,
    manager_avatar: null,
    manager_name: "Norrie Griffiths",
    staff_count: 71,
    property_count: 36,
    unit_count: 47,
  },
  {
    id: 146,
    branch_title: "Neutrogena Corporation",
    branch_full_address: "Room 1518",
    avatar: "http://dummyimage.com/108x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Kerby Trowl",
    staff_count: 72,
    property_count: 37,
    unit_count: 1,
  },
  {
    id: 147,
    branch_title: "American Sales Company",
    branch_full_address: "20th Floor",
    avatar: "http://dummyimage.com/237x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Ambrosius Habin",
    staff_count: 36,
    property_count: 5,
    unit_count: 9,
  },
  {
    id: 148,
    branch_title: "Rebel Distributors Corp",
    branch_full_address: "13th Floor",
    avatar: "http://dummyimage.com/145x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Rickie Loader",
    staff_count: 35,
    property_count: 80,
    unit_count: 65,
  },
  {
    id: 149,
    branch_title: "Allergy Laboratories, Inc.",
    branch_full_address: "Room 1541",
    avatar: "http://dummyimage.com/163x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Arch Upjohn",
    staff_count: 64,
    property_count: 46,
    unit_count: 66,
  },
  {
    id: 150,
    branch_title: "Barr Laboratories Inc.",
    branch_full_address: "PO Box 55093",
    avatar: "http://dummyimage.com/179x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Immanuel Collinwood",
    staff_count: 40,
    property_count: 69,
    unit_count: 29,
  },
  {
    id: 151,
    branch_title: "Apotheca Company",
    branch_full_address: "PO Box 21235",
    avatar: "http://dummyimage.com/150x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Teodora Berceros",
    staff_count: 4,
    property_count: 79,
    unit_count: 21,
  },
  {
    id: 152,
    branch_title: "Enzymatic Therapy, LLC",
    branch_full_address: "Suite 66",
    avatar: "http://dummyimage.com/170x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Marlow Corzon",
    staff_count: 86,
    property_count: 65,
    unit_count: 40,
  },
  {
    id: 153,
    branch_title: "Aphena Pharma Solutions - Tennessee, LLC",
    branch_full_address: "Apt 132",
    avatar: null,
    manager_avatar: null,
    manager_name: "Ardath Leipold",
    staff_count: 34,
    property_count: 97,
    unit_count: 7,
  },
  {
    id: 154,
    branch_title: "McKesson",
    branch_full_address: "Suite 59",
    avatar: "http://dummyimage.com/232x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Syd Mowling",
    staff_count: 28,
    property_count: 26,
    unit_count: 41,
  },
  {
    id: 155,
    branch_title: "AvPAK",
    branch_full_address: "6th Floor",
    avatar: "http://dummyimage.com/246x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Heidi Bibey",
    staff_count: 45,
    property_count: 89,
    unit_count: 59,
  },
  {
    id: 156,
    branch_title: "Davion, Inc dba HABA",
    branch_full_address: "Room 859",
    avatar: "http://dummyimage.com/207x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Gay Wormleighton",
    staff_count: 98,
    property_count: 50,
    unit_count: 5,
  },
  {
    id: 157,
    branch_title: "L. Perrigo Company",
    branch_full_address: "Room 1622",
    avatar: "http://dummyimage.com/195x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Sayre MacAleese",
    staff_count: 66,
    property_count: 43,
    unit_count: 62,
  },
  {
    id: 158,
    branch_title: "Ionx Holdings d/b/a HelloLife",
    branch_full_address: "Apt 823",
    avatar: null,
    manager_avatar: null,
    manager_name: "Holly-anne Pellett",
    staff_count: 21,
    property_count: 36,
    unit_count: 9,
  },
  {
    id: 159,
    branch_title: "Uriel Pharmacy Inc.",
    branch_full_address: "Apt 1774",
    avatar: "http://dummyimage.com/143x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Bay Anyene",
    staff_count: 24,
    property_count: 10,
    unit_count: 77,
  },
  {
    id: 160,
    branch_title: "J. A. Cosmetics U.S. INC",
    branch_full_address: "Apt 1611",
    avatar: "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Brennen Degoe",
    staff_count: 45,
    property_count: 23,
    unit_count: 70,
  },
  {
    id: 161,
    branch_title: "Procter & Gamble Manufacturing Company",
    branch_full_address: "PO Box 85703",
    avatar: "http://dummyimage.com/161x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Tony Nacey",
    staff_count: 49,
    property_count: 81,
    unit_count: 88,
  },
  {
    id: 162,
    branch_title: "Barr Laboratories Inc.",
    branch_full_address: "14th Floor",
    avatar: "http://dummyimage.com/173x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Lovell Deverille",
    staff_count: 49,
    property_count: 96,
    unit_count: 9,
  },
  {
    id: 163,
    branch_title: "Novartis Pharmaceuticals Corporation",
    branch_full_address: "Suite 8",
    avatar: "http://dummyimage.com/175x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Tilda Doughton",
    staff_count: 71,
    property_count: 99,
    unit_count: 48,
  },
  {
    id: 164,
    branch_title: "Autumn Harp, Inc.",
    branch_full_address: "PO Box 78318",
    avatar: null,
    manager_avatar: null,
    manager_name: "Jewel Tarpey",
    staff_count: 75,
    property_count: 65,
    unit_count: 96,
  },
  {
    id: 165,
    branch_title: "Breckenridge Pharmaceutical, Inc",
    branch_full_address: "Room 1109",
    avatar: "http://dummyimage.com/104x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Hetty Gartan",
    staff_count: 14,
    property_count: 79,
    unit_count: 40,
  },
  {
    id: 166,
    branch_title: "Areva Pharmaceuticals,Inc.",
    branch_full_address: "Room 551",
    avatar: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Ingmar Joslow",
    staff_count: 17,
    property_count: 87,
    unit_count: 47,
  },
  {
    id: 167,
    branch_title: "DAVA Pharmaceuticals, Inc.",
    branch_full_address: "2nd Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Isa Galilee",
    staff_count: 44,
    property_count: 53,
    unit_count: 34,
  },
  {
    id: 168,
    branch_title: "Mission Hills S.A de C.V",
    branch_full_address: "Apt 1988",
    avatar: "http://dummyimage.com/143x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Ina Berzen",
    staff_count: 41,
    property_count: 54,
    unit_count: 20,
  },
  {
    id: 169,
    branch_title: "Salix Pharmaceuticals, Inc.",
    branch_full_address: "Room 1327",
    avatar: "http://dummyimage.com/111x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Cristiano Donati",
    staff_count: 20,
    property_count: 79,
    unit_count: 23,
  },
  {
    id: 170,
    branch_title: "REMEDYREPACK INC.",
    branch_full_address: "Apt 554",
    avatar: "http://dummyimage.com/248x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Yasmin Wittke",
    staff_count: 64,
    property_count: 53,
    unit_count: 65,
  },
  {
    id: 171,
    branch_title: "American Regent, Inc.",
    branch_full_address: "PO Box 29478",
    avatar: "http://dummyimage.com/103x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Jemmy Merrison",
    staff_count: 53,
    property_count: 53,
    unit_count: 38,
  },
  {
    id: 172,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "Apt 914",
    avatar: null,
    manager_avatar: null,
    manager_name: "Nancie Barukh",
    staff_count: 88,
    property_count: 62,
    unit_count: 1,
  },
  {
    id: 173,
    branch_title: "H E B",
    branch_full_address: "PO Box 20976",
    avatar: "http://dummyimage.com/202x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Cindee O'Fergus",
    staff_count: 44,
    property_count: 86,
    unit_count: 1,
  },
  {
    id: 174,
    branch_title:
      "Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC",
    branch_full_address: "Suite 80",
    avatar: null,
    manager_avatar: null,
    manager_name: "Olympia Sorsbie",
    staff_count: 61,
    property_count: 26,
    unit_count: 97,
  },
  {
    id: 175,
    branch_title: "Baxter Healthcare Corporation",
    branch_full_address: "Apt 1679",
    avatar: "http://dummyimage.com/175x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Bogart Jasiak",
    staff_count: 50,
    property_count: 25,
    unit_count: 4,
  },
  {
    id: 176,
    branch_title: "Ningbo United",
    branch_full_address: "Room 112",
    avatar: "http://dummyimage.com/198x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Dorree Pregal",
    staff_count: 85,
    property_count: 22,
    unit_count: 43,
  },
  {
    id: 177,
    branch_title: "West-Ward Pharmaceutical Corp.",
    branch_full_address: "Room 1048",
    avatar: "http://dummyimage.com/122x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Jesse Strawbridge",
    staff_count: 61,
    property_count: 68,
    unit_count: 50,
  },
  {
    id: 178,
    branch_title: "HyVee Inc",
    branch_full_address: "Apt 321",
    avatar: "http://dummyimage.com/235x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Lidia Duesberry",
    staff_count: 21,
    property_count: 88,
    unit_count: 42,
  },
  {
    id: 179,
    branch_title: "Physicians Total Care, Inc.",
    branch_full_address: "Apt 605",
    avatar: "http://dummyimage.com/235x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Shannan Bonhan",
    staff_count: 58,
    property_count: 92,
    unit_count: 71,
  },
  {
    id: 180,
    branch_title: "Ventura Corporation, LTD",
    branch_full_address: "Apt 868",
    avatar: null,
    manager_avatar: null,
    manager_name: "Betsy Runchman",
    staff_count: 42,
    property_count: 16,
    unit_count: 88,
  },
  {
    id: 181,
    branch_title: "Mylan Pharmaceuticals Inc.",
    branch_full_address: "PO Box 55925",
    avatar: null,
    manager_avatar: null,
    manager_name: "Meaghan De Roeck",
    staff_count: 29,
    property_count: 71,
    unit_count: 53,
  },
  {
    id: 182,
    branch_title: "Conopco Inc. d/b/a Unilever",
    branch_full_address: "Room 705",
    avatar: "http://dummyimage.com/189x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Adriena Sagrott",
    staff_count: 71,
    property_count: 44,
    unit_count: 7,
  },
  {
    id: 183,
    branch_title: "NCS HealthCare of KY, Inc dba Vangard Labs",
    branch_full_address: "PO Box 64998",
    avatar: "http://dummyimage.com/123x100.png/ff4444/ffffff",
    manager_avatar: null,
    manager_name: "Elna Kahane",
    staff_count: 3,
    property_count: 21,
    unit_count: 45,
  },
  {
    id: 184,
    branch_title: "Ecolab Inc.",
    branch_full_address: "PO Box 87933",
    avatar: "http://dummyimage.com/213x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Corena Ferrino",
    staff_count: 71,
    property_count: 44,
    unit_count: 8,
  },
  {
    id: 185,
    branch_title: "Guna spa",
    branch_full_address: "Suite 38",
    avatar: "http://dummyimage.com/142x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Tully O'Lennachain",
    staff_count: 61,
    property_count: 56,
    unit_count: 14,
  },
  {
    id: 186,
    branch_title: "AB7 Industries",
    branch_full_address: "14th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Corissa Darrach",
    staff_count: 49,
    property_count: 77,
    unit_count: 72,
  },
  {
    id: 187,
    branch_title: "ProStrakan, Inc.",
    branch_full_address: "Room 494",
    avatar: "http://dummyimage.com/171x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Orbadiah Weall",
    staff_count: 94,
    property_count: 93,
    unit_count: 2,
  },
  {
    id: 188,
    branch_title: "Bryant Ranch Prepack",
    branch_full_address: "Suite 57",
    avatar: "http://dummyimage.com/209x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Gonzales Marner",
    staff_count: 86,
    property_count: 95,
    unit_count: 85,
  },
  {
    id: 189,
    branch_title: "H E B",
    branch_full_address: "Suite 87",
    avatar: "http://dummyimage.com/180x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Kelcie Keasy",
    staff_count: 75,
    property_count: 48,
    unit_count: 84,
  },
  {
    id: 190,
    branch_title: "Dynarex Corporation",
    branch_full_address: "Room 784",
    avatar: null,
    manager_avatar: null,
    manager_name: "Hamilton Durno",
    staff_count: 92,
    property_count: 57,
    unit_count: 15,
  },
  {
    id: 191,
    branch_title: "PD-Rx Pharmaceuticals, Inc.",
    branch_full_address: "Suite 4",
    avatar: "http://dummyimage.com/133x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Roseanne Tween",
    staff_count: 82,
    property_count: 79,
    unit_count: 28,
  },
  {
    id: 192,
    branch_title: "International Wholesale, Inc.",
    branch_full_address: "Suite 13",
    avatar: "http://dummyimage.com/132x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Cornela Fennick",
    staff_count: 42,
    property_count: 10,
    unit_count: 80,
  },
  {
    id: 193,
    branch_title: "Mylan Pharmaceuticals Inc.",
    branch_full_address: "Suite 6",
    avatar: null,
    manager_avatar: null,
    manager_name: "Jerry Clarke-Williams",
    staff_count: 86,
    property_count: 36,
    unit_count: 85,
  },
  {
    id: 194,
    branch_title: "GOWOONSESANG COSMETICS CO., LTD.",
    branch_full_address: "19th Floor",
    avatar: null,
    manager_avatar: null,
    manager_name: "Rosie Bruff",
    staff_count: 8,
    property_count: 28,
    unit_count: 7,
  },
  {
    id: 195,
    branch_title: "Reckitt Benckiser LLC",
    branch_full_address: "Suite 8",
    avatar: "http://dummyimage.com/214x100.png/cc0000/ffffff",
    manager_avatar: null,
    manager_name: "Yehudit Follet",
    staff_count: 13,
    property_count: 100,
    unit_count: 10,
  },
  {
    id: 196,
    branch_title: "Dolgencorp, LLC",
    branch_full_address: "14th Floor",
    avatar: "http://dummyimage.com/129x100.png/5fa2dd/ffffff",
    manager_avatar: null,
    manager_name: "Pollyanna Igglesden",
    staff_count: 68,
    property_count: 78,
    unit_count: 97,
  },
  {
    id: 197,
    branch_title: "AbbVie Inc.",
    branch_full_address: "Apt 904",
    avatar: null,
    manager_avatar: null,
    manager_name: "Conway Dei",
    staff_count: 28,
    property_count: 70,
    unit_count: 100,
  },
  {
    id: 198,
    branch_title: "Alva-Amco Pharmacal Companies, Inc.",
    branch_full_address: "PO Box 90088",
    avatar: null,
    manager_avatar: null,
    manager_name: "Ileana Van Haeften",
    staff_count: 11,
    property_count: 63,
    unit_count: 62,
  },
  {
    id: 199,
    branch_title: "Natural Health Supply",
    branch_full_address: "Room 247",
    avatar: null,
    manager_avatar: null,
    manager_name: "Marc Merriott",
    staff_count: 67,
    property_count: 52,
    unit_count: 46,
  },
  {
    id: 200,
    branch_title: "Apotheca Company",
    branch_full_address: "Apt 1897",
    avatar: "http://dummyimage.com/170x100.png/dddddd/000000",
    manager_avatar: null,
    manager_name: "Portie Huertas",
    staff_count: 32,
    property_count: 46,
    unit_count: 2,
  },
];
