export const industryOptions = [
  "Realtors",
  "Real Estate Agent",
  "Attorneys",
  "Investors",
  "Broker",
  "Estate Agent",
  "Barristers",
  "Arbitrators",
  "Solicitors",
  "Advocates",
  "Lawyer",
  "Legal Practitioner",
  "Law Firm",
  "Real Estate Appraiser",
  "Property Analyst",
  "Facility Manager",
  "Estate Surveyor & Valuer",
  "Property Manager",
  "Contractor",
  "Land Surveyor",
  "Hotel Manager",
  "Architect",
  "Builder",
  "Developer",
  "Town Planner",
  "Civil Engineer",
  "Caretaker",
  "Quantity Surveyor",
  "Property Supervisor",
  "Real Estate Developer",
  "Real Estate Investors",
  "Property Developers",
  "Hospitality Company",
  "Joint Business",
  "Enterprise",
  "Sole Proprietorship ",
  "Real Estate Company",
];

export const titles = [
  "Prince",
  "Princess",
  "Alhaji",
  "Alhaja",
  "Mr",
  "Mrs",
  "Esv",
  "Esq",
  "LL.B",
  "RSV ",
  "Anvis",
  "ANIM",
  "Dr",
  "Proff",
  "Rtp",
  "Mnitp",
  "Mnim",
  "MMP",
  "Fipman",
  "Fcicpfm",
  "TPL",
  "MBA",
  "PMP",
  "F.ASCE",
  "M.NSE",
  "F.NICE",
  "MAPM",
  "OON",
  "FNIA",
  "PPNIA",
  "PPARCON",
  "MMI",
  "AIA",
  "ENGR",
  "Pastor",
  "Evangelist",
];

export interface LocalGovernments {
  [localGovernment: string]: string[];
}

// Define the structure for the states array
export interface State {
  [stateName: string]: LocalGovernments;
}

export const states: State[] = [
  {
    Abia: {
      "Aba North": [
        "Ariaria",
        "Eziama",
        "Ogbor Hill",
        "Osusu",
        "Umuola",
        "Umuogor",
        "Uratta",
        "Umule",
      ],
      "Aba South": [
        "Aba",
        "Asaokpuja",
        "Eziama",
        "Obohia",
        "Ogbor Hill",
        "Osusu",
        "Over Rail",
        "Umuagbai",
        "Umuocham",
        "Waterside",
      ],
      Arochukwu: [
        "Abam",
        "Amasu",
        "Amangwu",
        "Amuvi",
        "Arochukwu",
        "Atani",
        "Bende",
        "Ihechiowa",
        "Isu",
        "Obinkita",
        "Ututu",
      ],
      Bende: [
        "Alayi",
        "Bende",
        "Igbere",
        "Item",
        "Itumbauzo",
        "Nkpa",
        "Ozuitem",
        "Ugwueke",
        "Umuhu-Ezexhi",
        "Umu",
        "Menyi",
        "Uzuakoli",
      ],
      Ikwuano: [
        "Akwette",
        "Amasu",
        "Ariam-Usaka",
        "Ikwuano (the LGA headquarters)",
        "Ibere",
        "Ibohia",
        "Ikpa",
        "Isiala",
        "Obuohia",
        "Okpuala",
        "Umuahia (partially within Ikwuano)",
        "Umuaro",
      ],
      "Isiala Ngwa North": [
        "Acha",
        "Amangwu",
        "Amazu",
        "Azuabom",
        "Isiaku",
        "Mgboko",
        "Ndiakwu",
        "Ngwa",
        "Ogbu",
        "Oforola",
        "Umuokpo",
        "Umuocham",
        "Umuopara",
      ],
      "Isiala Ngwa South": [
        "Amankalu",
        "Aru",
        "Eziama",
        "Ikpe",
        "Isiala Ngwa",
        "Mgboko",
        "Ndiokereke",
        "Oboro",
        "Umuode",
        "Umuomaku",
      ],
      Isuikwuato: [
        "Ajiase",
        "Akaeze",
        "Akwukwu",
        "Amaba",
        "Amibo",
        "Amoke",
        "Awhum",
        "Ibu",
        "Isuikwuato",
        "Mbato",
        "Nkwoegwu",
        "Nsulu",
        "Obuaku",
        "Ogwuta",
        "Orodo",
        "Umuchi",
        "Umuahia",
      ],
      "Obi Ngwa": [
        "Aba",
        "Abariba",
        "Ahiaba",
        "Amangwu",
        "Amoji",
        "Awhum",
        "Eziama",
        "Ibeku",
        "Ikwuano",
        "Ogbaku",
        "Umuahia",
      ],
      Ohafia: [
        "Abaomege",
        "Achi",
        "Amangwu",
        "Amaeke",
        "Amaekpu",
        "Amasu",
        "Amoji",
        "Arochukwu",
        "Ebem",
        "Eziama",
        "Ndiokereke",
        "Ohafia Town",
        "Okagwe",
        "Umuahia",
        "Uzuakoli",
      ],
      Osisioma: [
        "Awhum",
        "Awhum Uratta",
        "Egbu",
        "Eziama",
        "Nkwoegwu",
        "Umukabia",
        "Umuoma",
      ],
      Ugwunagbo: [
        "Aboh Mbaise",
        "Ahiaba",
        "Akaeze",
        "Amuzu",
        "Amodu",
        "Aro",
        "Eke",
        "Ihiagwa",
        "Ikwuano",
        "Obollo",
        "Oboro",
        "Okpo",
        "Ugwunagbo",
        "Umudike",
      ],
      "Umuahia North": [
        "Abaomege",
        "Akwette",
        "Aro-Ikpa",
        "Enyiogugu",
        "Eziama",
        "Ibeku",
        "Ibere",
        "Ikwuano",
        "Ntigha",
        "Umuahia",
        "Umuokpo",
        "Umuopara",
      ],
      "Umuahia South": [
        "Amawom",
        "Amuzukwu",
        "Ariam",
        "Arogo",
        "Ibeku",
        "Mgboko",
        "Ndi Oji",
        "Ntigha",
        "Okwuta",
        "Umuahia",
        "Umuocham",
      ],
      Ukwuani: [
        "Abbi",
        "Amai",
        "Asaba",
        "Ibusa",
        "Kwale",
        "Obi-Oroha",
        "Obioma",
        "Utagba-Ogbe",
      ],
      "Ukwa East": [
        "Amangwu",
        "Ameshi",
        "Amechi",
        "Arochi",
        "Ezeleke",
        "Mgboko",
        "Nkporo",
        "Obioma",
        "Okwuohia",
        "Umuahia",
      ],
      "Ukwa West": [
        "Amangwu",
        "Ameshi",
        "Amechi",
        "Arochi",
        "Ezeleke",
        "Mgboko",
        "Nkporo",
        "Obioma",
        "Okwuohia",
        "Umuahia",
      ],
    },
  },
  {
    Adamawa: {
      Demsa: ["Demsa", "Gore", "Numan", "Tadam"],
      Fufore: ["Fufore", "Jada", "Tongo"],
      Ganye: [
        "Bagale",
        "Bami",
        "Dakuna",
        "Gamu",
        "Ganye",
        "Gujera",
        "Gurum",
        "Jaggu",
        "Sugu",
      ],
      Gombi: [
        "Dakwa",
        "Dingai",
        "Duwa",
        "Garkida",
        "Gombi",
        "Guyaku",
        "Tawa",
        "Waduku",
        "Yang",
        "Yunusari",
      ],
      Jada: [
        "Danaba",
        "Jada",
        "Koma",
        "Leko",
        "Mbulo",
        "Mayokila",
        "Mayo Belwa",
        "Yelli",
      ],
      Madagali: [
        "Bitiku",
        "Gulak",
        "Hyambula",
        "Madagali",
        "Shuwa",
        "Wagga",
        "Wuro",
        "Balka",
      ],
      Maiha: ["Belel", "Koba", "Maiha", "Pakka", "Sarau", "Tambajam"],
      "Mubi North": [
        "Bahuli",
        "Betso",
        "Chaba",
        "Digil",
        "Kolere",
        "Lokuwa",
        "Mijilu",
        "Sabon",
        "Layi",
        "Vimtim",
        "Yelwa",
      ],
      "Mubi South": [
        "Birim",
        "Gella",
        "Gude",
        "Kwaja",
        "Lamorde",
        "Mugulvu",
        "Nassarawo",
        "Yadafa",
        "Yelwa",
        "Yewuratu",
      ],
      Numan: [
        "Bare",
        "Borrong",
        "Dahwa",
        "Dong",
        "Kodomti",
        "Lamurde",
        "Libbo",
        "Numan",
        "Vulpi",
      ],
      Shelleng: ["Bambam", "Banjiram", "Bodwai", "Gundo", "Shelleng"],
      Song: [
        "Baga",
        "Dumne",
        "Dirma",
        "Gudu Mboi",
        "Kilange",
        "Mayamari",
        "Sigire",
        "Song",
        "Sukuma",
        "Zumo",
      ],
      Toungo: ["Toungo", "Gembu", "Kola", "Tungo"],
      "Yola North": ["Girei", "Jimeta", "Yola"],
      "Yola South": ["Girei", "Yola"],
    },
  },
  {
    AkwaIbom: {
      Abak: [
        "Afaha Obong",
        "Afaha Offiong",
        "Ata Obio Akpa",
        "Atai Otoro",
        "Ediene",
        "Ikot Abasi",
        "Ikot Akpabio",
        "Ikot Ekang",
        "Ikot Oku Mfang",
        "Ikot Udo Ntuen",
        "Midim",
        "Otoro",
      ],
      "Eastern Obolo": [
        "Amadaka",
        "Ebighi-Okpono",
        "Egbokwe",
        "Elile",
        "Ete-Ubong",
        "Iko",
        "Okwok-Okoroete",
        "Okoroete",
        "Otunene",
        "Oyeren",
        "Uda",
        "Uyo",
      ],
      Eket: [
        "Afaha Atai",
        "Afaha Eket",
        "Afaha Uqua",
        "Eket Urban",
        "Esit Urua",
        "Ikot Abia",
        "Ikot Afaha",
        "Ikot Udoma",
        "Mkpok",
        "Nduo Eduo",
        "Okon",
        "Uquo",
        "Usung Inyang",
      ],
      "Esit Eket": [
        "Akai",
        "Akpautong",
        "Ebekpi",
        "Ede Urua",
        "Edor",
        "Ekpene Obo",
        "Etebi",
        "Ikpa",
        "Ndon Eyo",
        "Ntafre",
        "Uquo",
      ],
      "Essien Udim": [
        "Adiasim",
        "Afaha Ikot Ebak",
        "Afaha Ikot Obio Nkan",
        "Afaha Offiong",
        "Afaha Ugu",
        "Ata Essien Obio",
        "Ekpeyong Atai",
        "Ekpenyong 2",
        "Ikot Akpa Edu",
        "Ikot Ekpene",
        "Ikot Esen Akpan Ntuen",
        "Ikot Mbo",
        "Ikot Obioko",
        "Ikot Udo",
        "Nto Nsek",
        "Obio Akpa",
        "Ukana Ikot Ntuen",
        "Ukana Ikot Udo",
        "Ukana Uwa",
      ],
      "Etim Ekpo": [
        "Abak Obong",
        "Abat",
        "Afaha Ekpeneduk",
        "Afaha Obong",
        "Akpanang",
        "Akpautong",
        "Ikot Akpa Ntuk",
        "Ikot Ebidang",
        "Ikot Ekpene",
        "Ikot Udo Idem",
        "Ikot Udobong",
        "Ikot Uso Akpan",
        "Nung Obong",
        "Udianga Enem",
        "Utu Etim Ekpo",
      ],
      Etinan: [
        "Afaha Ekpene",
        "Afaha Iman",
        "Afaha Nsit",
        "Afaha Udoeyop",
        "Edebom",
        "Ekpene Ukim",
        "Ekpene Utu",
        "Etinan Urban",
        "Ikot Akpan Ishiet",
        "Ikot Akpan Ntuen",
        "Ikot Anang",
        "Ikot Ebo",
        "Ikot Ebiyan",
        "Ikot Edet",
        "Ikot Ekang",
        "Ikot Esifa",
        "Ikot Esu",
        "Ikot Etetuk",
        "Ikot Inyang",
        "Ikot Mbonde",
        "Ikot Oku Nsit",
        "Ikot Udombang",
        "Mbiokporo I",
        "Mbiokporo II",
        "Ndon Ekpe",
        "Ndon Obong",
        "Nsit Ubium",
      ],
      Ika: [
        "Achan Ika",
        "Afa Edem Edet",
        "Afa Ndon Oyo",
        "Afaha Akpan Ekpo",
        "Afaha Edem Urua",
        "Afaha Ibesit",
        "Afaha Ikot Ekong",
        "Afaha Ikot Nkan",
        "Afaha Udo Enem",
        "Akai Ika",
        "Ikot Akpa Ekang",
        "Ikot Akpa Eyo",
        "Ikot Akpa Nkuk",
        "Ikot Akpan Idem",
        "Ikot Esu Udo",
        "Ikot Inyang Otoro",
        "Ikot Mbom Itam",
        "Ikot Nkap",
        "Ikot Obio Utip",
        "Ikot Oku Etim",
        "Ikot Udo Ekop",
        "Iton Otoro",
        "Ndon Ise",
        "Nkwot Edem Edet",
        "Nung Ibekwe",
        "Nung Itak",
        "Nung Oku Udo Ekong",
        "Urua Udok",
      ],
      Ikono: [
        "Ibiaku Ntok Okpo",
        "Ikot Akpan",
        "Ikot Ekpene",
        "Ikot Nseyen",
        "Itak",
        "Nkwot",
        "Nnung Udoe",
        "Uyo Itam",
        "Ukwok",
        "Usung Atiat",
      ],
      "Ikot Abasi": [
        "Ete",
        "Ibekwe",
        "Ikot Abasi",
        "Ikot Akpaden",
        "Ikot Obong",
        "Ikpa Ibekwe",
        "Ikpa Nnung Assang",
        "Inen",
        "Mkpat Enin",
        "Ukpum Ete",
        "Ukpum Okon",
      ],
      "Ikot Ekpene": [
        "Amanyan",
        "Atan",
        "Ikot Abia",
        "Ikot Ekpene",
        "Ikot Esen",
        "Ikot Inyang",
        "Ikot Obong Edong",
        "Ikot Osurua",
        "Ikot Ubo",
        "Nto Edino",
        "Odoro Ikot",
        "Ukana",
        "Ukana Essien",
      ],
      Itu: [
        "Ayadehe",
        "Edem Itam",
        "Eka Edem",
        "Ekit Itam",
        "Ekondo",
        "Enen Atai",
        "Ikot Ada Akpan",
        "Ikot Andem Itam",
        "Ikot Anie",
        "Ikot Asua",
        "Ikot Essien",
        "Ikot Ikpe",
        "Ikot Mbonde",
        "Ikot Nsukara",
        "Ikot Oduk",
        "Ikot Ukap",
        "Ikot Uko",
        "Ibiaku Itam",
        "Itu",
        "Mbiatok",
        "Mbiabo",
        "Mbiokporo",
        "Mbiotom",
      ],
      Mbo: [
        "Ebughu",
        "Effiat",
        "Enwang",
        "Ibaka",
        "Ine Ekpe",
        "Uda",
        "Unyenge",
      ],
      "Mkpat Enin": [
        "Afaha Nsit",
        "Anua",
        "Ekpenyong",
        "Ibiaku",
        "Ikot Abasi",
        "Ikot Ekpene",
        "Ikot Imo",
        "Ikot Obio",
        "Ikot Udo",
        "Uyo",
      ],
      "Nsit Atai": [
        "Abak",
        "Afaha Atai",
        "Afaha Offot",
        "Ebekpo",
        "Ekpene Ukim",
        "Ikot Ekpene",
        "Ikot Imo",
        "Ikot Osung",
        "Ikot Udo",
        "Ikot Usen",
        "Itam",
        "Nsit Ibom",
        "Utu Etim Ekpo",
      ],
      "Nsit Ibom": [
        "Afaha",
        "Afaha Ikot Ekan",
        "Ikot Akpan",
        "Ikot Edim",
        "Ikot Ekpene",
        "Ikot Enang",
        "Ikot Imo",
        "Ikot Itie",
        "Ikot Ntuk",
        "Ikot Obong",
        "Ikot Usung",
        "Iwukem",
        "Nsikan",
        "Ukanafun",
      ],
      "Nsit Ubium": [
        "Afaha Offiong",
        "Afaha Udo Eyop",
        "Akai Ubium",
        "Akpautong",
        "Awa Ubium",
        "Ikot Akpan",
        "Ikot Edibon",
        "Ikot Esen",
        "Ikot Etim",
        "Ikot Nya",
        "Ikot Obio Okon",
        "Ikot Udo",
        "Ndukpoise",
        "Ubium Ikot Ekpene",
        "Ubium Village",
        "Ukat Ubium",
        "Uyo Offiong",
      ],
      "Obot Akara": [
        "Abak-Obot",
        "Eka Uruk Eshiet",
        "Ikot Abia",
        "Ikot Akpan",
        "Ikot Ekpene",
        "Ikot Essien",
        "Ikot Ewang",
        "Ikot Inyang",
        "Ikot Ntung",
        "Ikot Osom",
        "Ikot Ukpong",
        "Nto Edino",
        "Nto Etukudo",
        "Nto Mbadang",
        "Nto Nsek",
        "Nto Ubiam",
      ],
      Okobo: [
        "Atabong",
        "Ekeya",
        "Ewet",
        "Eyo Abasi",
        "Ibiaku",
        "Idung Afianwe",
        "Idung Iniang",
        "Ndibe",
        "Nsie",
        "Okopedi",
        "Oti Oro",
        "Udung Uko",
        "Urue Offong",
        "Uta Ewa",
      ],
      Onna: [
        "Abat",
        "Awa",
        "Edemaya",
        "Ikot Akpatek",
        "Ikot Ebekpo",
        "Ikot Edor",
        "Ikot Enang",
        "Ikot Etefon",
        "Ikot Ibritam",
        "Ikot Nkang",
        "Ikot Nseyen",
        "Ikot Udo",
        "Ndon Eyo",
        "Ndon Ikot Itie Udung",
        "Ndiya",
        "Oniong",
      ],
      Oron: [
        "Afaha Okpo",
        "Afaha Ukwong",
        "Akai Ubium",
        "Awa Iman",
        "Eyo Abasi",
        "Eyo Ufut",
        "Ibighi",
        "Ibaka",
        "Idua Assang",
        "Iquita",
        "Mbiabong",
        "Oron Urban",
        "Oti Oro",
        "Uko Akpan",
        "Usung Esuk",
      ],
      "Oruk Anam": [
        "Abak Midim",
        "Ekparakwa",
        "Etok",
        "Ikot Afanga",
        "Ikot Ibritam",
        "Ikot Obio Itong",
        "Ikot Oku Usung",
        "Ikot Uko",
        "Ikot Usung",
        "Ibesit Nung Ikot",
        "Ndiya",
        "Nung Ikot Ekan",
        "Nung Ikot Obioku",
        "Obio Akpa",
        "Otoro",
        "Utu",
      ],
      "Udung Uko": [
        "Afa Offiong",
        "Afa Uquo",
        "Afaha",
        "Atabong",
        "Iqukpok",
        "Ikot Afa",
        "Ikot Okpo",
        "Ndon Ebom",
        "Nduo Edou",
        "Nkwot Edem",
        "Odoro Ikot",
        "Urua Udok",
      ],
      Ukanafun: [
        "Afaha Idim",
        "Afaha Offot",
        "Afaha Okpo",
        "Ikot Akpan",
        "Ikot Ebak",
        "Ikot Ekang",
        "Ikot Esien",
        "Ikot Esu",
        "Ikot Essien",
        "Ikot Mfon",
        "Ikot Ntuk",
        "Ikot Oku Idim",
        "Ikot Osum",
        "Ikot Udo",
        "Ikot Ukpong",
        "Ikot Uso Ekong",
        "Ikot Usung",
        "Obong Itam",
      ],
      Uruan: [
        "Afaha Oku",
        "Afaha Urua",
        "Afaha Uyo",
        "Ekpene Ibia",
        "Ekwa",
        "Etoi",
        "Ikot Akpan",
        "Ikot Ebo",
        "Ikot Ekan",
        "Ikot Ekpenyong",
        "Ikot Esen",
        "Ikot Eyo",
        "Ikot Eyop",
        "Ikot Ifaha",
        "Ikot Iko",
        "Ikot Ima",
        "Ikot Inyang",
        "Ikot Obio Akpa",
        "Ikot Obio Itong",
        "Ikot Oku Ikot Ekan",
        "Ikot Oku Ubo",
        "Ikot Umiang",
        "Ikot Udo Abia",
        "Ikot Udo Esoro",
        "Ikot Udo Ekong",
        "Ikot Udom",
        "Ikot Uyo",
        "Ikot Usung",
        "Uruan Urban",
      ],
      Uyo: [
        "Awa Iman",
        "Ewet Housing",
        "Ifa Ikot Okpon",
        "Ifa Nkanga",
        "Ikot Akpan Abia",
        "Ikot Akpan Essien",
        "Ikot Akpan Etok",
        "Ikot Akpan Ikpong",
        "Ikot Ebido Oku",
        "Ikot Ekpe",
        "Ikot Ikpan",
        "Ikot Itie Udung",
        "Ikot Nkanda",
        "Ikot Oku Ikot Ekang",
        "Ikot Oku Mfang",
        "Ikot Uko",
        "Itiam",
        "Itu",
        "Obio Imo",
        "Uyo Urban",
      ],
    },
  },
  {
    Anambra: {
      Aguata: [
        "Achina",
        "Aguluezechukwu",
        "Akpo",
        "Amesi",
        "Ekwulobia",
        "Ezinifite",
        "Igbo-Ukwu",
        "Isuofia",
        "Nkpologwu",
        "Oraeri",
        "Uga",
      ],
      Ayamelum: [
        "Anaku",
        "Igbakwu",
        "Ifite-Ogwari",
        "Omasi",
        "Omor",
        "Umueje",
        "Umumbo",
        "Umuerum",
      ],
      Dunukofia: [
        "Aguluzigbo",
        "Alor",
        "Eziowelle",
        "Ifitedunu",
        "Neni",
        "Ukwulu",
      ],
      Ekwusigo: [
        "Amichi",
        "Azigbo",
        "Ekwulobia",
        "Igboukwu",
        "Isuaniocha",
        "Nnewi",
        "Nnewi Ichi",
        "Okpuno",
        "Uga",
      ],
      "Idemili North": [
        "Abatete",
        "Aguluzigbo",
        "Akwaeze",
        "Alor",
        "Awka-Etiti",
        "Nnobi",
        "Nkpor",
        "Umuoji",
        "Uke",
      ],
      "Idemili South": [
        "Abatete",
        "Aguleri",
        "Alor",
        "Ekwulobia",
        "Nnobi",
        "Nnokwa",
        "Oraifite",
        "Ukpor",
      ],
      Ihiala: [
        "Amorka",
        "Azia",
        "Ihiala",
        "Lilu",
        "Mbosi",
        "Nnewi (partly within Ihiala LGA)",
        "Orsumoghu",
        "Uli",
      ],
      Njikoka: ["Abagana", "Enugu-Ukwu", "Nimo", "Ukpo"],
      "Nnewi North": [
        "Akwu",
        "Amichi",
        "Ekwulumili",
        "Ichi",
        "Nnewi",
        "Oka",
        "Uruagu",
        "Umuorji",
      ],
      "Nnewi South": [
        "Amichi",
        "Amorka",
        "Azigbo",
        "Ekwulumili",
        "Ichi",
        "Nnobi",
        "Nnewi",
      ],
      Ogbaru: [
        "Akili-Ozizor",
        "Atani",
        "Ezira",
        "Igbariam",
        "Odekpe",
        "Oguom",
        "Okpoko",
        "Osamala",
        "Umunankwo",
        "Umuoba-Anam",
      ],
      "Onitsha North": [
        "Anambra East",
        "Anambra West",
        "Awka North",
        "Awka South",
        "Dunukofia",
        "Ekwusigo",
        "Idemili North",
        "Idemili South",
        "Ihiala",
        "Njikoka",
        "Nnewi North",
        "Nnewi South",
        "Ogbaru",
        "Onitsha North",
        "Onitsha South",
        "Orumba North",
        "Orumba South",
        "Oyi",
      ],
      "Onitsha South": [
        "Aguata",
        "Anambra East",
        "Anambra West",
        "Awka North",
        "Awka South",
        "Ayamelum",
        "Dunukofia",
        "Ekwusigo",
        "Idemili North",
        "Idemili South",
        "Ihiala",
        "Njikoka",
        "Nnewi North",
        "Nnewi South",
        "Ogbaru",
        "Orumba North",
        "Orumba South",
        "Oyi",
      ],
      "Orumba North": ["Awgbu", "Eziowelle", "Nanka", "Okpuno", "Umuchu"],
      "Orumba South": [
        "Agbudu",
        "Akpu",
        "Awa",
        "Ifite Ogwari",
        "Nanka",
        "Oko",
        "Owerre-Ezukala",
        "Umunze",
        "Umuchu",
        "Umudioka",
      ],
      Oyi: ["Aguleri", "Anambra East", "Eziagulu", "Igbariam", "Umueri"],
    },
  },
  {
    Bauchi: {
      Alkaleri: [
        "Alkaleri",
        "Dindima",
        "Dukul",
        "Gadaya",
        "Gagdi",
        "Kafin-Madaki",
        "Tafawa Balewa",
      ],
      Bogoro: [
        "Bogoro",
        "Daffo",
        "Goribung",
        "Gubi",
        "Kiri",
        "Makarau",
        "Kura",
        "Tafawa",
      ],
      Damban: [
        "Damban",
        "Dambam",
        "Dawaki",
        "Gimbiya",
        "Jama'are",
        "Kafin Madaki",
        "Malam Sidi",
        "Malam Titi",
        "Ningi",
      ],
      Darazo: [
        "Darazo",
        "Bakin Dutse",
        "Gada",
        "Kafin Madaki",
        "Kari",
        "Lame",
        "Mada",
      ],
      Dass: [
        "Dass",
        "Bauchi",
        "Dawaki",
        "Gindiri",
        "Kafin Hausa",
        "Tafawa Balewa",
      ],
      Gamawa: ["Gamawa", "Dadin Kowa", "Gwandu", "Hana"],
      Giade: ["Bajari", "Dajin", "Giade", "Gwaram", "Kariya", "Rafin"],
      "Itas/Gadau": ["Gadau", "Itas", "Jama’are"],
      "Jama'are": [
        "Aba",
        "Dukul",
        "Jama'are",
        "Kafin-Madaki",
        "Kafin-Shehu",
        "Yalwan",
      ],
      Katagum: [
        "Azare",
        "Bauchi",
        "Dambam",
        "Duguri",
        "Gamawa",
        "Kari",
        "Katagum",
        "Matazu",
        "Miga",
        "Zaki",
      ],
      Kirfi: [
        "Bauchi",
        "Dindima",
        "Gundari",
        "Kirfi",
        "Kobai",
        "Lame",
        "Ribadu",
        "Tafawa",
      ],
      Misau: ["Dagauda", "Dari", "Misau", "Sakwai", "Tafawa Balewa"],
      Ningi: ["Dutsen Abba", "Dutsen Kura", "Ningi", "Ribadu", "Shira"],
      Shira: [
        "Bungudu",
        "Dadin-Kowa",
        "Fadama",
        "Jama'are",
        "Kafin-Madaki",
        "Shira",
        "Tudun-Wada",
      ],
      "Tafawa Balewa": [
        "Bagel",
        "Barkin Ladi",
        "Dutsen Kura",
        "Jama'are",
        "Tafawa Balewa",
        "Toro",
      ],
      Toro: [
        "Azare",
        "Bakin Kogi",
        "Dambam",
        "Dingi",
        "Gamawa",
        "Ganjuwa",
        "Kari",
        "Ningi",
        "Rishi",
        "Toro",
      ],
      Warji: ["Gai", "Jama'are", "Kafin Madaki", "Kwara", "Pali", "Warji"],
      Zaki: ["Bajoga", "Dambam", "Ganjuwa", "Kafin-Madaki", "Saminaka", "Zaki"],
    },
  },
  {
    Bayelsa: {
      Brass: [
        "Brass Town",
        "Ekeremor",
        "Gbarantoru",
        "Odioma",
        "Ogbia",
        "Twon-Brass",
      ],
      Ekeremor: [
        "Bomo",
        "Ekeremor",
        "Foro",
        "Igbomotoru",
        "Ijaw",
        "Kolo",
        "Koroama",
        "Olugbobiri",
        "Oporoma",
        "Sagbama",
        "Sandfield",
        "Toru-Ebe",
      ],
      "Kolokuma/Opokuma": [
        "Akenfa",
        "Amasoma",
        "Bumodi",
        "Ebedebiri",
        "Ekeremor",
        "Elebele",
        "Kolo",
        "Odi",
        "Opokuma",
        "Peremabiri",
      ],
      Nembe: [
        "Akassa",
        "Azuzuama",
        "Boma",
        "Bulou-Orua",
        "Koluama",
        "Nembe (Nembe Town)",
        "Ogbolomabiri",
        "Olugbobiri",
        "Oporoma",
        "Peretorugbene",
        "Samkiri",
        "Teme",
      ],
      Ogbia: [
        "Azikoro",
        "Emadike",
        "Ewoama",
        "Kolo",
        "Ogbia",
        "Oloibiri",
        "Olugbobiri",
        "Okodi",
        "Okpoma",
        "Otuokpoti",
        "Samagidi",
      ],
      Sagbama: [
        "Akipelai",
        "Amaso",
        "Bilabiri",
        "Ebedebiri",
        "Gbaraun",
        "Ikibiri",
        "Ogobiri",
        "Olugbobiri",
        "Sagbama (Sagbama Urban)",
        "Toru-Orua",
      ],
      "Southern Ijaw": [
        "Agge",
        "Azuzuama",
        "Bilabiri",
        "Bile",
        "Cawthorne Channel",
        "Ebedebiri",
        "Gbarain",
        "Igbomatoro",
        "Ikarama",
        "Kolo",
        "Ogbe",
        "Okpoama",
        "Oporoma",
        "Sagbama",
        "Sandfield",
        "Tebu",
      ],
      Yenagoa: [
        "Agudama-Epie",
        "Azikoro",
        "Edepie",
        "Ekeremor",
        "Ekeki",
        "Igbogene",
        "Igbomotoru",
        "Ikarama",
        "Ovom",
        "Salto",
        "Swali",
        "Yenagoa (Yenagoa Urban)",
      ],
    },
  },
  {
    Benue: {
      Agatu: [
        "Abugbe",
        "Adoka",
        "Agatu",
        "Apir",
        "Ogbodo",
        "Obagaji",
        "Ogboju",
        "Ogugu",
      ],
      Apa: ["Adoka", "Agatu", "Ajegbe", "Anwase", "Anyibe", "Ogbadibo"],
      Buruku: ["Agasha", "Buruku", "Gboko", "Mbaakpu", "Mbasombo"],
      Guma: [
        "Daudu",
        "Gbajimba",
        "Naka",
        "Naka (formerly known as Naka and now considered a city)",
        "Umenger",
      ],
      "Gwer East": [
        "Adikpo",
        "Akwanga",
        "Apa",
        "Gboko",
        "Gwer",
        "Ishange",
        "Mbagwa",
        "Mbanor",
        "Nekede",
      ],
      "Gwer West": [
        "Adikpo",
        "Aila",
        "Gwer",
        "Ikyogen",
        "Mbagir",
        "Mbatyu",
        "Naka",
        "Ogbadibo",
        "Udam",
        "Ukum",
      ],
      "Katsina-Ala": [
        "Adikpo",
        "Chito",
        "Gbise",
        "Katsina-Ala (the administrative center)",
        "Mbayion",
        "Takum",
      ],
      Konshisha: [
        "Agatu",
        "Apa",
        "Buruku",
        "Gboko",
        "Guma",
        "Gwer-East",
        "Gwer-West",
        "Katsina-Ala",
        "Konshisha",
        "Ogbadibo",
        "Oju",
        "Okpokwu",
        "Obi",
        "Otukpo",
        "Tarka",
        "Ushongo",
        "Vandeikya",
      ],
      Kwande: [
        "Adikpo",
        "Ikurav-Tiev",
        "Mbayion",
        "Nimbo",
        "Tse-Agberagba",
        "Tse-Ginde",
      ],
      Logo: [
        "Aondoana",
        "Fidi",
        "Iorja",
        "Mbajir",
        "Mbatyula",
        "Mbagwen",
        "Mburkum",
        "Tse-Apera",
        "Tse-Ayadi",
        "Tse-Gbam",
      ],
      Makurdi: [
        "Adikpo",
        "North Bank",
        "Wurukum",
        "Wadata",
        "Vandeikya",
        "Yangoji",
      ],
      Ogbadibo: [
        "Ado",
        "Awhum",
        "Oba",
        "Otukpa (The administrative headquarters)",
        "Obokpa",
      ],
      Ohimini: [
        "Ado (The headquarters)",
        "Agbenema",
        "Ogbokpo",
        "Ogbadibo",
        "Otukpo",
      ],
      Oju: [
        "Awhum",
        "Oju (the administrative headquarters)",
        "Obioma",
        "Okpoga",
        "Ugboju",
      ],
      Okpokwu: ["Akii", "Ami", "Orokam", "Ogboju", "Okpoga", "Onyedega"],
      Obi: ["Adum", "Aondoana", "Obi", "Ogbaku", "Ogbadibo"],
      Otukpo: ["Otukpo", "Obagaji", "Utonkon", "Adoka"],
      Ushongo: ["Agasha", "Mbakwem", "Mbakpa", "Mbakul", "Ushongo Town"],
      Vandeikya: [
        "Akaa",
        "Akor",
        "Mbagen",
        "Mbakine",
        "Mbatyough",
        "Mbaake",
        "Mbayion",
        "Mbalom",
        "Vandeikya",
      ],
    },
  },
  {
    Borno: {
      Abadam: [
        "Abadam",
        "Baga",
        "Borno",
        "Damasak",
        "Gubio",
        "Kirawa",
        "Kukawa",
        "Mairi",
        "Malam Fatori",
        "Ngala",
        "Tumbun Gini",
      ],
      "Askira Uba": [
        "Askira",
        "Bama",
        "Bama-Madachi",
        "Bura",
        "Chul",
        "Dille",
        "Gubio",
        "Gwoza",
        "Kwaya Kusar",
        "Ngarwa",
        "Uba",
        "Waka",
      ],
      Bama: [
        "Abbaram",
        "Amtifura",
        "Andara",
        "Azir",
        "Bama (Bama Town)",
        "Banki",
        "Darajamal",
        "Dipcheri",
        "Gwoza",
        "Kumshe",
        "Ndufu",
        "Shehuri",
        "Soye",
        "Wulgo",
      ],
      Biu: [
        "Buratai",
        "Damboa",
        "Garubula",
        "Gunda",
        "Gur",
        "Miringa",
        "Mandaragirau",
        "Piku",
        "Wuyo",
        "Yamarkumi",
        "Zarawuyaku",
        "Zumbulum",
      ],
      Chibok: [
        "Chibok (Chibok Urban)",
        "Gatamwarwa",
        "Kautikari",
        "Korongilim",
        "Kuburmbula",
        "Mboa Kura",
        "Njoma",
        "Pemi",
        "Shikarkir",
        "Whuntaku",
      ],
      Damboa: [
        "Azir",
        "Balla",
        "Bego",
        "Damboa (Damboa Urban)",
        "Gumsuri",
        "Kafa",
        "Kopchi",
        "Mulgwai",
        "Sabon Gari",
        "Shawa",
        "Wuyaram",
        "Zara",
      ],
      Dikwa: ["Boboshe", "Dikwa", "Mudu", "Mallam Kaunari", "Ngudoram", "Soye"],
      Guzamala: [
        "Aduwa",
        "Gudumbali",
        "Gubio",
        "Guduba",
        "Maibara",
        "Moduri",
        "Wamiri",
      ],
      Gwoza: [
        "Ashigashiya",
        "Dure",
        "Gamboru",
        "Guduf",
        "Gwoza (Gwoza Town)",
        "Hambagda",
        "Kirawa",
        "LimanKara",
        "Ngoshe",
        "Pulka",
        "Warabe",
        "Wala",
        "Yamtake",
      ],
      Jere: [
        "Alau",
        "Bale Galtimari",
        "Dalori",
        "Dusuman",
        "Gongulong",
        "Jere (Jere Urban)",
        "Mairi",
        "Ngomari",
        "Old Maiduguri",
        "Zabbarmari",
      ],
      Kaga: [
        "Afa",
        "Benisheikh",
        "Borgozo",
        "Dogon Gada",
        "Galangi",
        "Mainok",
        "Marguba",
        "Ngamdu",
      ],
      "Kala Balge": [
        "Amchaka",
        "Buruwa",
        "Darajamal",
        "Izge",
        "Jeram",
        "Jilbe",
        "Kala",
        "Malam Fatori",
        "Rann",
        "Sigal",
      ],
      Konduga: [
        "Auno",
        "Bama",
        "Binikidi",
        "Kaga",
        "Konduga (Konduga Urban)",
        "Kwarori",
        "Mairi",
        "Miringa",
        "Ngamdu",
        "Shuwari",
      ],
      Kukawa: [
        "Baga",
        "Damasak",
        "Kukawa (Kukawa Town)",
        "Malam Fatori",
        "Munguno",
        "Ngala",
        "Wulgo",
      ],
      Mafa: [
        "Auno",
        "Bama",
        "Gajiram",
        "Mafa",
        "Maiduguri (though not within Mafa itself, it's a significant nearby city often associated with the region)",
        "Ngala",
        "Wamdeo",
      ],
      Magumeri: [
        "Bama",
        "Borno",
        "Gajiram",
        "Gubio",
        "Magumeri",
        "Marte",
        "Ngala",
        "Ngazargamu",
      ],
      Maiduguri: [
        "Bulumkutu",
        "Jere",
        "Maiduguri (Maiduguri Urban)",
        "Mairi",
        "Monguno",
        "Ngomari",
        "Old Maiduguri",
        "Shehuri",
        "Wulari",
      ],
      Marte: [
        "Baga",
        "Dikwa",
        "Gajiram",
        "Gubio",
        "Kurnawa",
        "Marte",
        "Ngala",
        "Wulgo",
      ],
      Mobbar: [
        "Auno",
        "Baga",
        "Damasak",
        "Gubio",
        "Kukuwa",
        "Kwaya",
        "Monguno",
        "Munguno",
        "Ngazargamu",
      ],
      Monguno: [
        "Auno",
        "Baga",
        "Bogom",
        "Damasak",
        "Gajiram",
        "Monguno",
        "Ngala",
        "Kukawa",
        "Kurnawa",
        "Malam Fatori",
      ],
      Ngala: [
        "Dikwa",
        "Gamboru",
        "Gombi",
        "Jambutu",
        "Kwaya Kusar",
        "Maiduguri",
        "Ngala (Ngala Urban)",
        "Rann",
        "Wulgo",
      ],
      Nganzai: [
        "Bakin Dutse",
        "Bama",
        "Borno",
        "Dikwa",
        "Gajiram",
        "Gajiganna",
        "Gubio",
        "Jajere",
        "Kaga",
        "Kwaya Kusar",
        "Magumeri",
        "Nganzai",
        "Ngude",
        "Shuwari",
        "Wuyo",
      ],
      Shani: [
        "Bama",
        "Buni Yadi",
        "Dikwa",
        "Gwoza",
        "Konduga",
        "Mafa",
        "Shani",
        "Uba",
      ],
    },
  },
  {
    "Cross River": {
      Akamkpa: ["Akpabuyo", "Akamkpa", "Boki", "Calabar", "Ikom", "Obubra"],
      Akpabuyo: [
        "Akpabuyo",
        "Akpabuyo Urban",
        "Bokoko",
        "Ikot Abasi",
        "Ikot Esuk",
        "Ikot Offiong",
        "Mbarakom",
        "Nsidung",
      ],
      Bakassi: [
        "Akpankpang",
        "Anantigha",
        "Bakassi",
        "Ikang",
        "Ita",
        "Mokpani",
        "Sagbama",
      ],
      Bekwarra: ["Bekwarra", "Bendu", "Mba", "Mbu", "Ugep", "Ukpah", "Ushie"],
      Biase: [
        "Akpabuyo",
        "Biase",
        "Ikot Effiong",
        "Ikot Nkebre",
        "Odukpani",
        "Ogep",
      ],
      Boki: ["Boki", "Ejagham", "Ishibori", "Mbarakom", "Okundi", "Okom"],
      "Calabar Municipal": [
        "Calabar",
        "Akpabuyo",
        "Atimbo",
        "Calabar South",
        "Ekpo Abasi",
        "Ikom",
        "Murtala Muhammed",
        "Ugep",
      ],
      "Calabar South": [
        "Anantigha",
        "Bakoko",
        "Efut Abua",
        "Efut Akani Esuk",
        "Efut",
        "Efangha",
        "Ekpo Abasi",
        "Henshaw Town",
        "Ikot Ansa",
        "Ikot Efanga",
        "Ikot Omin",
        "Mbukpa",
        "New Edgerley",
        "Obufa Esuk Orok",
        "Target",
        "Uwanse",
        "Waterside",
      ],
      Etung: [
        "Abia",
        "Agbokim",
        "Ajassor",
        "Amana",
        "Bendeghe",
        "Ekon",
        "Effraya",
        "Etomi",
        "Ikom",
        "Mkpot",
        "Nsofang",
      ],
      Ikom: [
        "Abakpa",
        "Abijang",
        "Adijinkpor",
        "Agbokim Waterfalls",
        "Akparabong",
        "Nkarasi",
        "Okuni",
        "Olulumo",
        "Osomba",
        "Yala-Nkum",
      ],
      Obanliku: [
        "Anape",
        "Bebi",
        "Bende",
        "Bepe",
        "Busi",
        "Busisi",
        "Kakwagom",
        "Obanliku",
        "Sankwala",
        "Utanga",
      ],
      Obubra: [
        "Ababene",
        "Adun",
        "Apiapum",
        "Ofatura",
        "Ochon",
        "Ogada",
        "Okangha",
        "Okom",
        "Ovukwa",
        "Ugep",
      ],
      Obudu: [
        "Begbere-Bekwarra",
        "Begiaka",
        "Begiading",
        "Bendi",
        "Ipong",
        "Obudu",
        "Ukpe",
        "Utugwan",
      ],
      Odukpani: [
        "Adim",
        "Anakpa",
        "Atan Okoyong",
        "Creek Town",
        "Ekong Anaku",
        "Ikot Efa",
        "Ikot Nakanda",
        "Inuakpa Okoyong",
        "Isong Inyang",
        "Mbiabo",
        "Ndon Ebom",
        "Obom Itiat",
        "Odot Forest",
        "Odukpani",
        "Orok Ntan",
        "Usung Esuk",
      ],
      Ogoja: [
        "Ekajuk",
        "Ibil",
        "Nkum",
        "Ntrigom",
        "Ogoja Town",
        "Uchong",
        "Uvuru",
        "Yala",
      ],
      Yala: [
        "Abakpa",
        "Akamkpa",
        "Akamkpa Town",
        "Etomi",
        "Ikorof",
        "Mbube",
        "Ogoja",
        "Okpoma",
        "Ugep",
        "Yala",
      ],
      Yarkur: [
        "Bebetim",
        "Ekureku",
        "Mbakong",
        "Okpoma",
        "Ugep",
        "Ugep Community",
      ],
    },
  },
  {
    Delta: {
      "Aniocha North": [
        "Aboh",
        "Ebu",
        "Ibusa",
        "Issele-Azagba",
        "Issele-Uku",
        "Oshimili",
        "Ubulu-Uku",
      ],
      "Aniocha South": [
        "Ebu",
        "Igbodo",
        "Isele-Uku",
        "Onicha-Uku",
        "Ubulu-Uku",
      ],
      Bomadi: [
        "Bomadi",
        "Boys Town",
        "Egbo",
        "Ogbobagbene",
        "Oginibo",
        "Orogho",
        "Tebu",
      ],
      Burutu: [
        "Burutu",
        "Aghoro",
        "Bille",
        "Forcados",
        "Gbaramatu",
        "Kpakiama",
        "Ogulagha",
      ],
      "Ika North East": [
        "Agbor",
        "Boji-Boji",
        "Ikaibolo",
        "Owa-Alero",
        "Owa-Oyibu",
        "Umunede",
      ],
      "Ika South": [
        "Abavo",
        "Akwukwu-Igbo",
        "Boji-Boji Owa",
        "Owa-Oyibu",
        "Ute-Okpu",
        "Ute-Erumu",
      ],
      "Isoko North": ["Aghalokpe", "Oleh", "Olomoro", "Osioma", "Uro", "Uzere"],
      "Isoko South": [
        "Akatogbo",
        "Awhinawhi",
        "Emevor",
        "Ezionum",
        "Igbide",
        "Olomoro",
        "Osubi",
        "Ughoton",
        "Umeh",
      ],
      "Ndokwa East": ["Aboh", "Ase", "Ebu", "Emu", "Isele-Azagba", "Obi"],
      "Ndokwa West": [
        "Abbi",
        "Emu",
        "Ogume",
        "Onicha-Ukwuani",
        "Utagba-Ogbe (Kwale)",
        "Utagba-Uno",
      ],
      "Oshimili North": [
        "Akwukwu-Igbo",
        "Ibusa (Ibuzor)",
        "Illah",
        "Okpanam",
        "Ukala",
        "Ebu",
      ],
      "Oshimili South": ["Cable Point", "Oko", "Umuezei", "Ogbele", "Umuonaje"],
      Patani: [
        "Abari",
        "Bolou-Angiama",
        "Odorubu",
        "Ogbeingbene",
        "Patani Town",
        "Toru-Angiama",
        "Uduophori",
      ],
      Sapele: [
        "Sapele Town",
        "Amukpe",
        "Oghara",
        "Elume",
        "Ogiedi",
        "Okuovu",
        "Ugborhen",
        "Ugbeyiyi",
      ],
      Udu: [
        "Aladja",
        "Enerhen",
        "Ekete",
        "Egini",
        "Emadadja",
        "Emogun",
        "Ovwian",
        "Owhrode",
        "Otor-Udu",
        "Oleri",
        "Ovworhokpokpo",
        "Oghior",
      ],
      "Ughelli North": [
        "Afiesere",
        "Agbarha-Otor",
        "Agbarho",
        "Ekiugbo",
        "Ekredjebor",
        "Evwreni",
        "Orogun",
        "Oteri",
        "Otovwodo (Ughelli)",
        "Uwheru",
      ],
      "Ughelli South": [
        "Ekakpamre",
        "Ekete",
        "Ekrejegbe",
        "Ewu",
        "Gbaregolor",
        "Oginibo",
        "Okparabe",
        "Olomu",
        "Otokutu",
        "Ovwor",
        "Owhawha",
        "Owhrode",
        "Ughoton",
        "Ujevwu",
        "Ughievwen",
        "Usiefrun",
      ],
      Uvwie: [
        "Ekpan",
        "Effurun",
        "Enerhen",
        "Jeddo",
        "Ugbomro",
        "Ugbolokposo",
        "Ugboroke",
        "Ugbuwangue",
      ],
      "Warri Central": [
        "Ajao",
        "Ijala",
        "Jude",
        "Mojere",
        "Ode-Itsekiri",
        "Osubi",
        "Warri",
      ],
      "Warri North": [
        "Ajao",
        "Bateren",
        "Egbokodo",
        "Effurun-Otor",
        "Gbokoda",
        "Koko",
        "Mofor",
        "Okpe",
        "Okwagbe",
        "Otefe",
      ],
      "Warri South": ["Ekpan", "Jesse", "Koko", "Oginibo", "Udu", "Warri"],
      "Warri South West": [
        "Beneath",
        "Effurun-Otor",
        "Forcados",
        "Ogorode",
        "Sapele",
        "Warri",
      ],
    },
  },
  {
    Ebonyi: {
      Abakaliki: [
        "Abakaliki (Abakaliki Urban)",
        "Azuiyiokwu",
        "Ezza",
        "Ezzamgbo",
        "Ikwo",
        "Ngbo",
        "Nkaliki",
        "Nkwegu",
        "Ohaukwu",
        "Uburu",
        "Umuoghara",
      ],
      "Afikpo North": [
        "Afikpo",
        "Amasiri",
        "Amudo",
        "Ekoli Edda",
        "Edda",
        "Ishiagu",
        "Mbube",
        "Ndufu-Alike",
        "Oso Edda",
        "Umuogodo",
      ],
      "Afikpo South": [
        "Amuro",
        "Edda",
        "Ezzama",
        "Ishiagu",
        "Ndiakachara",
        "Ndeabor",
        "Okposi",
        "Umunna",
      ],
      Ebonyi: [
        "Abakaliki (Ebonyi's capital city)",
        "Amanator",
        "Amagu",
        "Amaozara",
        "Amike",
        "Amudo",
        "Ezzamgbo",
        "Ezza",
        "Nkaliki",
        "Uburu",
      ],
      "Ezza North": [
        "Abakaliki",
        "Ameka",
        "Amudo",
        "Enyigba",
        "Ekka",
        "Ezza",
        "Ezillo",
        "Ntezi",
        "Okpuitumo",
        "Onicha",
      ],
      "Ezza South": [
        "Ameka",
        "Amudo",
        "Anike",
        "Enyigba",
        "Ezza",
        "Igbudu",
        "Ishiagu",
        "Nkalagu",
        "Okpuitumo",
        "Uhuahia",
      ],
      Ikwo: [
        "Amachi",
        "Ameka",
        "Amechi",
        "Echa",
        "Ezza",
        "Igbudu",
        "Ikwo",
        "Isinkwo",
        "Ogbaga",
        "Ohaozara",
        "Uburu",
      ],
      Ishielu: [
        "Amagu",
        "Ameka",
        "Amaeze",
        "Asor",
        "Ezzamgbo",
        "Ezzama",
        "Izzi",
        "Nkaleke",
        "Ngor",
        "Obegu",
        "Obiozara",
        "Okpuitumo",
        "Okposi",
      ],
      Ivo: [
        "Amagu",
        "Amike",
        "Anike",
        "Ekoli Edda",
        "Ezza",
        "Ishiagu",
        "Ivo",
        "Nkpologwu",
        "Okposi",
        "Umunaga",
      ],
      Izzi: [
        "Amagu",
        "Amike",
        "Azugwu",
        "Ezza",
        "Ezzamgbo",
        "Izzi (Izzi Urban)",
        "Ogboji",
        "Okpuitumo",
        "Ohaozara",
        "Ogbaku",
        "Umunya",
      ],
      Ohaozara: [
        "Amagu",
        "Amike",
        "Edda",
        "Enyigba",
        "Ivo",
        "Ndiagu",
        "Nkalagu",
        "Ohaozara",
        "Okposi",
        "Uburu",
      ],
      Onicha: [
        "Amagu",
        "Ameka",
        "Amohia",
        "Enyibichiri",
        "Ezza Onicha",
        "Ishiagu",
        "Obegu",
        "Onicha",
        "Onuofuo",
        "Umunya",
      ],
      Ohaukwu: [
        "Abakaliki",
        "Amagu",
        "Amata",
        "Atani",
        "Ezza",
        "Effium",
        "Ekwashi",
        "Ezza Effium",
        "Igbudu",
        "Ikwo",
        "Ohaozara",
        "Onicha",
        "Orieagu",
      ],
    },
  },
  {
    Edo: {
      "Akoko Edo": [
        "Agbede",
        "Auchi",
        "Fugar",
        "Ikpeshi",
        "Ogbona",
        "Ojirami",
        "Sobe",
      ],
      Egor: ["Evbuotubu", "Igueben", "Ilupeju", "Obazagbon", "Ohen", "Uselu"],
      "Esan Central": ["Ewossa", "Ibillo", "Igueben", "Opoji", "Ujiogba"],
      "Esan North East": [
        "Agbale",
        "Aiyegunle",
        "Ekpon",
        "Ekpoma",
        "Irrua",
        "Ujiogba",
      ],
      "Esan South East": ["Ake", "Ekiadolor", "Ekpoma", "Igueben", "Ujiogba"],
      "Esan West": [
        "Ewu",
        "Igueben",
        "Ikpoba-Okha (partially in Esan West)",
        "Ujiogba",
      ],
      "Etsako Central": [
        "Aibokun",
        "Agenebode",
        "Apana",
        "Ekperi",
        "Ewu",
        "Iguobazuwa",
        "Ogbona",
        "Okpella",
      ],
      "Etsako East": ["Aviele", "Fugar", "Jattu", "Ogba", "Okpella", "Uzea"],
      "Etsako West": [
        "Auchi",
        "Aviele",
        "Eruere",
        "Igueben",
        "Oshodi",
        "Sobe",
        "Udo",
        "Uromi",
      ],
      Igueben: ["Agaliga", "Agenebode", "Eguare", "Ehor", "Igueben", "Ivbiaro"],
      "Ikpoba-Okha": [
        "Abudu",
        "Benin City",
        "Evbuotubu",
        "Iyekogba",
        "Oregbeni",
        "Orhionmwon",
        "Ugbowo",
      ],
      Orhionmwon: [
        "Afuze",
        "Ekoegun",
        "Ewu",
        "Ibillo",
        "Igbanke",
        "Ologbo",
        "Ugo",
        "Ujiogba",
        "Uselu",
      ],
      Oredo: [
        "Ajao",
        "Benin City",
        "Egor",
        "Ikpoba Hill",
        "Oka",
        "Oredo",
        "Uselu",
      ],
      "Ovia North East": [
        "Aifuwa",
        "Ajao",
        "Avbiosi",
        "Ekpon",
        "Ekiadolor",
        "Ekiugbo",
        "Iguobazuwa",
        "Igbira",
        "Ogbese",
        "Ohuo",
      ],
      "Ovia South West": [
        "Afo",
        "Ekiadolor",
        "Iguobazuwa",
        "Iguogho",
        "Irua",
        "Ogbona",
        "Ogbosun",
        "Ovia",
      ],
      "Owan East": [
        "Afuze",
        "Aibiekhoe",
        "Avbiosi",
        "Egor",
        "Okpujie",
        "Oke-Oduna",
        "Uokha",
        "Uromi",
      ],
      "Owan West": [
        "Aibokun",
        "Afunwa",
        "Aibom",
        "Avbiosi",
        "Ekperi",
        "Ihievbe",
        "Ikabigbo",
        "Ikhueniro",
        "Irua",
        "Ogbekpen",
        "Ogbona",
        "Otuo",
      ],
      Uhunmwonde: [
        "Ehor",
        "Iguelaba",
        "Iguobazuwa",
        "Iguogbe",
        "Oredo",
        "Ugboko",
      ],
    },
  },
  {
    Ekiti: {
      "Ado Ekiti": [
        "Adebayo",
        "Afao",
        "Agbalala",
        "Ajilosun",
        "Iyin",
        "Odo Ado",
        "Oke Iye",
        "Oke-Osun",
      ],
      "Ekiti East": [
        "Ayetoro",
        "Eda",
        "Ijelu",
        "Ilupeju",
        "Itaji",
        "Omuo-Ekiti",
        "Orun",
      ],
      "Ekiti South West": [
        "Aramoko-Ekiti",
        "Ilawe-Ekiti",
        "Ilesa-Ekiti",
        "Ise-Ekiti",
        "Oke-Ako",
        "Omuo-Ekiti",
      ],
      "Ekiti West": [
        "Araromi-Obo",
        "Ijurin-Ekiti",
        "Isan-Ekiti",
        "Oke-Ako",
        "Omuo-Ekiti",
        "Otun-Ekiti",
      ],
      Emure: [
        "Emure-Ekiti",
        "Erinmope",
        "Ibuji",
        "Iye-Ekiti",
        "Odo-Ekiti",
        "Oke-Ako",
      ],
      "Ido/Osi": [
        "Ido-Ekiti",
        "Ijurin-Ekiti",
        "Ikole-Ekiti",
        "Ilesa-Ekiti",
        "Iyin-Ekiti",
        "Odo-Owa",
      ],
      Ikole: ["Ayede", "Ekole", "Igede", "Ikole", "Ire"],
      Ilejemeje: ["Eda", "Ilejemeje", "Ilemeso", "Imesi", "Iye"],
      "Irepodun/Ifelodun": [
        "Igbara-Odo",
        "Igbara-Odo Ekiti",
        "Igbemo Ekiti",
        "Ita Odo",
        "Ikun Ekiti",
        "Omuo Ekiti",
        "Osi Ekiti",
        "Usi Ekiti",
      ],
      Moba: ["Aisegba", "Ayegbaju", "Igbara-Odo", "Ijan", "Ise", "Omuo-Ekiti"],
      Oye: ["Eda", "Iye-Ekiti", "Oye-Ekiti", "Ureje"],
    },
  },
  {
    Enugu: {
      "Enugu East": [
        "Amagunze",
        "Ameke",
        "Amuri",
        "Obeagu",
        "Oruku",
        "Umuogbo",
        "Umuoda",
        "Uzo-Uwani",
      ],
      "Enugu North": [
        "Agbani",
        "Amagunze",
        "Enugu-Ezike",
        "Ndiagu",
        "Ogui",
        "Nsukka",
        "Ukehe",
      ],
      "Enugu South": ["Asata", "Enugu", "Okpara Square", "Ogui", "Trans-Ekulu"],
      Ezeagu: ["Amagu", "Awhum", "Eke", "Ezimo", "Ogbete", "Owerre-Ezeaghu"],
      "Isi-Uzo": ["Eha-Amufu", "Eha-Alumona", "Ezimo", "Ikem", "Isi-Uzo"],
      "Nkanu East": ["Awhum", "Amagunze", "Agbani", "Ugbawka", "Owo"],
      "Nkanu West": [
        "Agbani",
        "Amagunze",
        "Amuri",
        "Enugu-Ezike",
        "Mpu",
        "Nara",
      ],
      Nsukka: [
        "Ede-Oballa",
        "Enugu-Ezike",
        "Nsukka",
        "Obimo",
        "Opi",
        "Orba",
        "Ukehe",
      ],
      Udenu: [
        "Awhum",
        "Ezema",
        "Ibite",
        "Ibagwa-Aka",
        "Ibagwa-Ani",
        "Obollo-Afor",
        "Obollo-Eke",
        "Obollo-Itodo",
        "Obollo-Otoro",
        "Udenu",
      ],
      Udi: ["Amokwe", "Awhum", "Eke", "Udi", "Ogui-Eke", "Obinofia"],
      "Uzo-Uwani": [
        "Amurri",
        "Eha-Amufu",
        "Ezimo",
        "Mpu",
        "Neke",
        "Ogbede",
        "Ogbokwu",
        "Obollo-Eke",
        "Obollo-Afor",
        "Umuida",
      ],
    },
  },
  {
    Gombe: {
      Akko: [
        "Bage",
        "Daji",
        "Danjal",
        "Doma",
        "Ganjuwa",
        "Gombe",
        "Jauro Yinu",
        "Kaltungo",
        "Kwami",
        "Pallam",
        "Rama",
      ],
      Balanga: [
        "Balanga",
        "Billiri",
        "Dukku",
        "Goma",
        "Kaltungo",
        "Kukawa",
        "Shongom",
      ],
      Billiri: ["Biliri", "Buri", "Daba", "Gengle", "Kaltungo", "Kumo", "Piti"],
      Dukku: ["Dukku", "Bogo", "Biliri", "Dagu"],
      Funakaye: [
        "Dabai",
        "Funakaye",
        "Jekadafari",
        "Kaltungo",
        "Kwami",
        "Luwa",
        "Riyom",
      ],
      Gombe: [
        "Akko",
        "Balanga",
        "Billiri",
        "Dukku",
        "Funakaye",
        "Gombe",
        "Kaltungo",
        "Kwami",
        "Nafada",
        "Shongom",
        "Yamaltu/Deba",
      ],
      Kaltungo: ["Gona", "Kaltungo", "Kushaka", "Piti", "Ruma"],
      Kwami: ["Garga", "Gombe", "Kwami", "Nafada", "Rijau"],
      Nafada: ["Dukul", "Nafada", "Shongo"],
      Shongom: [
        "Dagauda",
        "Dewin",
        "Gona",
        "Kaltungo area",
        "Nafada",
        "Piti",
        "Shongom",
      ],
      "Yamaltu/Deba": ["Deba", "Dukul", "Gwandum", "Kumo", "Nasarawo Sakwai"],
    },
  },
  {
    Imo: {
      "Ahiazu Mbaise": [
        "Amuzi",
        "Afor-Ogbe",
        "Akabor",
        "Amuzi Oparanadim",
        "Ekwereazu",
        "Lagwa",
        "Mpam",
        "Obohia",
        "Ogbe",
        "Otulu",
        "Umunumo",
        "Uvuru",
      ],
      "Aboh Mbaise": [
        "Amuzu",
        "Enyiogugu",
        "Lorji",
        "Nguru",
        "Nkwogwu",
        "Umuokirika",
        "Umueze",
        "Uvuru",
      ],
      Akokwa: [
        "Akokwa",
        "Amaokpara",
        "Isiokpo",
        "Osina",
        "Urualla",
        "Umualaoma",
        "Ndianiche",
        "Umuezeaga",
        "Obodoukwu",
      ],
      "Ehime Mbano": [
        "Agbaja",
        "Agbaja-Uboma",
        "Amainyi",
        "Amauzari",
        "Umualumaku",
        "Umuezeala",
        "Umuezeala-Nsu",
        "Umueze-Ama",
        "Umunumo",
        "Umueze-Mbano",
      ],
      Ezinihitte: [
        "Ahiara",
        "Amumara",
        "Chokoneze",
        "Ezeagbogu",
        "Ifuho",
        "Itu",
        "Oboama",
        "Oboama-Nguru",
        "Okpofe",
        "Onicha",
        "Udo",
        "Umunama",
        "Umunekwu",
      ],
      "Ihitte/Uboma": [
        "Amaimo",
        "Umuihi",
        "Umuezegwu",
        "Okwuohia",
        "Umuderim",
        "Umuchieze",
        "Umuchima",
        "Abueke",
        "Amainyi",
        "Amakohia",
      ],
      Ikeduru: [
        "Amatta",
        "Amakohia",
        "Atta",
        "Avuvu",
        "Eziama",
        "Iho",
        "Inyishi",
        "Ngugo",
        "Uzoagba",
      ],
      "Isiala Mbano": [
        "Amaraku",
        "Amauzari",
        "Anara",
        "Ibeme",
        "Osu-Owerre",
        "Osuama",
        "Ugiri",
        "Umuduru",
        "Umuezeala",
        "Umunchi",
      ],
      Isu: ["Amandugba", "Amurie Omanze", "Ekwe", "Isu Njaba", "Umunakara"],
      Mbaitoli: [
        "Afara",
        "Egbeada",
        "Eziama Obiato",
        "Ifakala",
        "Njaba",
        "Ogbaku",
        "Orodo",
        "Ubomiri",
        "Umunoha",
      ],
      Mbiama: ["Ahoada", "Bera", "Egbeda", "Mbiama", "Odiemede"],
      Oguta: [
        "Awo-Omamma",
        "Ejemekwuru",
        "Oguta",
        "Oguta Town",
        "Umuokanne",
        "Umuohie",
      ],
      "Ohaji/Egbema": ["Awa", "Egbema", "Ohaji", "Okwudor", "Oguta"],
      Okigwe: [
        "Amagu",
        "Awa",
        "Isiukwuato",
        "Ishiagu",
        "Ogberurube",
        "Okigwe",
        "Umunna",
        "Umuahia",
      ],
      Orlu: [
        "Amakohia",
        "Amaraku",
        "Amauzari",
        "Awa",
        "Ejemekwuru",
        "Ikeduru",
        "Isu",
        "Okwu",
        "Orlu",
        "Umudim",
        "Umuaka",
      ],
      Orsu: [
        "Awo-Idemili",
        "Enyiogugu",
        "Iho",
        "Ihite",
        "Okwudor",
        "Oru",
        "Umudim",
        "Umulolo",
      ],
      "Owerri Municipal": [
        "Awo-Idemili",
        "Enyiogugu",
        "Iho",
        "Ihite",
        "Okwudor",
        "Oru",
        "Umudim",
        "Umulolo",
      ],
      "Owerri North": [
        "Aboh Mbaise",
        "Awa",
        "Emekuku",
        "Emii",
        "Eziama",
        "Ihiagwa",
        "Iloabuchi",
        "Oberia",
        "Okuku",
        "Umuguma",
      ],
      "Owerri West": [
        "Awo-Omamma",
        "Ihite",
        "Mbutu",
        "Ngor-Okpala",
        "Okwudor",
        "Owerri-Ebeiri",
        "Ubomir",
      ],
    },
  },
  {
    Jigawa: {
      Auyo: [
        "Auyo",
        "Dutse Alhaji",
        "Dutse Kudu",
        "Kafin Hausa",
        "Kaugama",
        "Kiri-Kiri",
        "Lemo",
        "Roni",
      ],
      Babura: [
        "Babura",
        "Kiyawa",
        "Kuka",
        "Kurfi",
        "Malamawa",
        "Sule Tankarka",
      ],
      Birniwa: [
        "Birniwa",
        "Dabi",
        "Dutsi",
        "Kafin-Hausa",
        "Kanya",
        "Kiyawa",
        "Yankwashi",
      ],
      "Birnin Kudu": [
        "Birnin Kudu",
        "Guri",
        "Kazaure",
        "Kiyawa",
        "Miga",
        "Ringim",
        "Taura",
      ],
      Buji: [
        "Buji",
        "Auyo",
        "Guwu",
        "Hadejia",
        "Karfi",
        "Kiyawa",
        "Maiduwuri",
        "Roni",
        "Tukur-Tukur",
      ],
      Dagin: ["Dajin", "Falgore", "Garko", "Kafur", "Kiyawa", "Kwanar Dangora"],
      Gagarawa: [
        "Gagarawa",
        "Kafin Hausa",
        "Kankara",
        "Kazaure",
        "Malam-Madori",
      ],
      Garki: ["Garki", "Dubi", "Kanya", "Sule Tankarkar", "Zango"],
      Gaya: [
        "Gaya",
        "Ajiwa",
        "Dutsen Abba",
        "Gwaram",
        "Hadejia",
        "Kafin Hausa",
        "Kumbotso",
        "Lambata",
        "Malam Madori",
        "Miga",
        "Roni",
        "Sule Tankarkar",
      ],
      Gwiwa: ["Gwiwa", "Dantudu", "Kwani", "Roni", "Sule-Tankarkar"],
      Hadejia: [
        "Hadejia",
        "Dawakin Tofa",
        "Guri",
        "Kafin Hausa",
        "Maigatari",
        "Yankwashi",
      ],
      Jahun: [
        "Dadin Kowa",
        "Gaji",
        "Jahun",
        "Kafin Hausa",
        "Kanyam",
        "Kazaure",
        "Roni",
      ],
      "Kafin Hausa": [
        "Basa",
        "Dabai",
        "Gayan",
        "Kafin Hausa",
        "Kiyawa",
        "Mai Kudi",
        "Malam Madori",
        "Malam Sidi",
      ],
      Kaugama: [
        "Auyo",
        "Dala",
        "Fagam",
        "Kaugama",
        "Kiyawa",
        "Kurin",
        "Maiduguri",
        "Roni",
        "Tsamiyar Biri",
        "Waki",
      ],
      Kazaure: [
        "Bawara",
        "Dabai",
        "Dawanu",
        "Gaba",
        "Jahun",
        "Kazaure",
        "Kiyawa",
        "Maigatari",
        "Roni",
      ],
      Kirikasamma: [
        "Auyo",
        "Babura",
        "Birnin Kudu",
        "Dutse",
        "Guri",
        "Kazaure",
        "Kirikasamma",
        "Maigatari",
        "Ringim",
        "Sule Tankarkar",
      ],
      Maigatari: [
        "Dabi",
        "Gandu",
        "Garki",
        "Maigatari",
        "Saminaka",
        "Tudun Wada",
      ],
      "Malam Madori": ["Garki", "Kiyawa", "Malam Madori", "Rugon", "Wudil"],
      Miga: ["Danzomo", "Gwaram", "Miga", "Roni"],
      Ringim: ["Ringim", "Garko", "Jahun", "Kiyawa", "Roni"],
      "Sule Tankarkar": [
        "Babba",
        "Danta",
        "Danzomo",
        "Karkarna",
        "Kifin",
        "Kofar Arewa",
        "Kofar Kudu",
        "Kuka",
        "Maiduguri",
        "Riga",
      ],
      Taura: [
        "Dabai",
        "Kafin Hausa",
        "Karnaya",
        "Malamawa",
        "Murtala",
        "Roni",
        "Taura",
      ],
      Yankwashi: [
        "Dabi",
        "Daki Turu",
        "Gidan Gambo",
        "Gidan Kiri",
        "Gidan Mota",
        "Kafin Hausa",
        "Kishimi",
        "Rohod",
        "Yankwashi",
      ],
    },
  },
  {
    Kaduna: {
      "Birnin Gwari": [
        "Bagoma",
        "Buruku",
        "Dogon Dawa",
        "Doka",
        "Gayam",
        "Gwaska",
        "Kakangi",
        "Kamfanin Doka",
        "Kutemeshi",
        "Kuriga",
        "Layin Lasan",
        "Layin",
        "Maigwari",
        "Maganda",
        "Randagi",
        "Tabanni",
      ],
      Chikun: [
        "Buruku",
        "Gwagwada",
        "Kakau",
        "Kujama",
        "Kujuru",
        "Kunai",
        "Kurmin Mashi",
        "Nasarawa",
        "Narayi",
        "Sabon Gayan",
        "Sabon Tasha",
        "Ungwan Dosa",
        "Ungwan Romi",
      ],
      Giwa: [
        "Dan Mahawayi",
        "Fatika",
        "Giwa",
        "Gangara",
        "Kakangi",
        "Kidandan",
        "Pan Hauya",
        "Shika",
        "Tsibiri",
        "Yakawada",
      ],
      Igabi: [
        "Afaka",
        "Birnin Yero",
        "Gwaraji",
        "Kerawa",
        "Kwarau",
        "Mahuta",
        "Rigachikun",
        "Rigasa",
        "Sabon Birnin Daji",
        "Turunku",
      ],
      Ikara: [
        "Auchan",
        "Ikara",
        "Janfalan",
        "Kurmin Kogi",
        "Kuya",
        "Paki",
        "Rumi",
        "Sa'a",
        "Saya-Saya",
        "Tashan-Fulani",
        "Tumburku",
      ],
      Jaba: [
        "Ankung",
        "Bitaro",
        "Fai",
        "Fada",
        "Kwoi",
        "Maigizoh",
        "Nok",
        "Sambang",
        "Sab-Zuro",
        "Sab-Zuro Langan",
        "Sabon Kaura",
        "Sanga",
        "Tsakiya",
        "Zikpak",
      ],
      "Jema'a": [
        "Aso",
        "Barde",
        "Fada",
        "Gidan Waya",
        "Godogodo",
        "Jagindi",
        "Jankasa",
        "Kaninkon",
        "Kagoma",
        "Kafanchan",
        "Katul",
        "Mabushi",
        "Nindem",
        "Zikpak",
      ],
      Kachia: [
        "Ankwa",
        "Awon",
        "Bishini",
        "Doka",
        "Gidan Tagwai",
        "Gumel",
        "Gumshi",
        "Kachia",
        "Kurmin Musa",
        "Kwaturu",
        "Ladduga",
        "Sabon Sarki",
        "Tashan Erem",
        "Zonkwa",
      ],
      "Kaduna North": [
        "Badarawa",
        "Doka",
        "Gabasawa",
        "Hayin Banki",
        "Kabala Costain",
        "Kawo",
        "Malali",
        "Unguwan Dosa",
        "Unguwan Rimi",
      ],
      "Kaduna South": [
        "Barnawa",
        "Kakuri",
        "Kurmin Mashi",
        "Makera",
        "Tudun Wada",
        "Television",
        "Ungwan Sanusi",
      ],
      Kagarko: ["Kagarko", "Kachia", "Kujama", "Makarfi", "Piti"],
      Kajuru: [
        "Angwan Gimbiya",
        "Angwan Kaji",
        "Angwan Lado",
        "Angwan Sarki",
        "Bakin Kogi",
        "Dankande",
        "Kagarko",
        "Kachia",
        "Kasuwan Magani",
        "Kwarau",
        "Kujama",
        "Maraban Rido",
        "Sabon Tasha",
        "Samaru",
        "Saminaka",
      ],
      Kaura: [
        "Akwanga",
        "Angwan Gwari",
        "Angwan Kachia",
        "Angwan Kogi",
        "Angwan Yaro",
        "Kafanchan",
        "Kagoro",
        "Kaura",
        "Zonkwa",
      ],
      Kauru: ["Gwagwada", "Kauru", "Kwanar", "Makarfi", "Sabon Gari", "Tashar"],
      Kubau: [
        "Bagado",
        "Baka",
        "Bakin Kogi",
        "Gimi",
        "Jaba",
        "Kagarko",
        "Kachia",
        "Kamuru",
        "Kubau",
        "Makarfi",
      ],
      Kudan: [
        "Bakin Kasuwa",
        "Bungudu",
        "Goribai",
        "Kudan",
        "Makarfi",
        "Rigachikun",
        "Soba",
        "Tudun Wada",
      ],
      Lere: [
        "Dandume",
        "Ganda",
        "Kaninkon",
        "Kauru",
        "Kofar Kudu",
        "Lere",
        "Rigachikun",
        "Saminaka",
        "Zango",
      ],
      Makarfi: [
        "Bomo",
        "Gambo",
        "Kafanchan",
        "Kwanar Makarfi",
        "Makarfi",
        "Mudi",
        "Sabon Gari",
      ],
      "Sabon Gari": [
        "Bagoma",
        "Dajin",
        "Dankande",
        "Kabaru",
        "Kage",
        "Kamuru",
        "Kurmin Zubair",
        "Mairama",
        "Nariya",
        "Sabon Gari",
        "Saminaka",
        "Tudun Wada",
      ],
      Sanga: [
        "Bakin Kogi",
        "Beli",
        "Gwantu",
        "Kafanchan",
        "Kwoi",
        "Piti",
        "Sanga",
      ],
      Soba: [
        "Badarawa",
        "Bakin Kasuwa",
        "Dan Kura",
        "Gidan Bawa",
        "Gidan Kwana",
        "Gidan Waya",
        "Jangali",
        "Kachia",
        "Lemu",
        "Makarfi",
        "Sabon Gari",
        "Soba",
        "Zango",
      ],
      "Zangon Kataf": [
        "Atyap",
        "Gidan Waya",
        "Gora",
        "Kafanchan",
        "Kwoi",
        "Taka",
        "Zonkwa",
      ],
      Zaria: [
        "Bagadus",
        "Dutsen Wai",
        "Gabasawa",
        "Gaskiya",
        "Gwa-Gwa",
        "Kofar Doka",
        "Kofar Gayan",
        "Kofar Gaya",
        "Kofar Gwandu",
        "Kofar Kibo",
        "Kofar Kudu",
        "Kofar Makarfi",
        "Kofar Mashi",
        "Kofar Nasarawa",
        "Kofar Shika",
        "Samaru",
        "Tudu",
        "Unguwan Dosa",
        "Unguwan Sarki",
        "Zaria City",
      ],
    },
  },
  {
    Kano: {
      Ajingi: [
        "Ajingi",
        "Danladi",
        "Garin-Ganye",
        "Gwarzo",
        "Kafin-Madaki",
        "Kokona",
        "Rijiya",
      ],
      Albasu: [
        "Albasu",
        "Bakin Kogi",
        "Gwarzo",
        "Kano",
        "Kofar Kudu",
        "Madobi",
        "Rimin Kebe",
        "Yandoto",
      ],
      Bagwai: [
        "Bagwai",
        "Bakin Kasuwa",
        "Dambatta",
        "Garko",
        "Kunchi",
        "Madobi",
        "Rimin Gado",
      ],
      Bebeji: [
        "Bebeji",
        "Dabagi",
        "Dandago",
        "Dawakin Tofa",
        "Gwarzo",
        "Kura",
        "Maiduguri",
        "Rimin Kebe",
      ],
      Bichi: [
        "Bichi",
        "Dandago",
        "Daushe",
        "Kafin-Mai-Karfi",
        "Kunya",
        "Matsaur",
        "Nasarawa",
        "Rimin Gado",
        "Rinji",
      ],
      Bunkure: [
        "Bunkure",
        "Dawakin Kudu",
        "Garko",
        "Kunchi",
        "Maimakawa",
        "Rano",
      ],
      Dala: [
        "Dala",
        "Dala-Gidan Kwana",
        "Dala-Kofar Dawanau",
        "Dala-Kofar Mata",
        "Dala-Kofar Wambai",
      ],
      Dambatta: [
        "Dambatta",
        "Dandago",
        "Dogo",
        "Gari",
        "Goribawa",
        "Rimin Gado",
        "Zangon Maji",
      ],
      "Dawakin Kudu": [
        "Dawakin Kudu",
        "Dawakin Tofa",
        "Garun Malam",
        "Kunchi",
        "Rano",
      ],
      "Dawakin Tofa": ["Dawakin Tofa", "Dawakin Kudu", "Tofa"],
      Doguwa: [
        "Bamkadi",
        "Doguwa",
        "Dutsen Kura",
        "Garko",
        "Kafin-Madaki",
        "Kura",
        "Madobi",
        "Rimin Gado",
      ],
      Fagge: [
        "Bakin Kogi",
        "Fagge",
        "Garko",
        "Kano",
        "Kofar Dan Auta",
        "Kofar Wambai",
        "Rimin Kebe",
      ],
      Gabasawa: [
        "Bakin Kogi",
        "Dawakin Tofa",
        "Gabasawa",
        "Garko",
        "Kauyen Dangi",
        "Rimin Kebe",
      ],
      Garko: [
        "Garko",
        "Dawakin Tofa",
        "Garun Malam",
        "Jambulo",
        "Kurawa",
        "Rimin Gado",
      ],
      "Garun Mallam": [
        "Garun Mallam",
        "Dandago",
        "Kurfai",
        "Kwarin Aji",
        "Wudil",
        "Yankaba",
      ],
      Gaya: ["Gaya", "Gari", "Kambaza", "Kunya", "Rano", "Riga"],
      Gezawa: ["Gezawa", "Dambatta", "Yankaba"],
      Gwale: ["Dawakin Tofa", "Fagge", "Kano City", "Rimi", "Tarauni"],
      Gwarzo: ["Gwarzo", "Dambatta", "Dutsen Titi", "Kano", "Rano", "Tarauni"],
      Kabo: [
        "Kabo",
        "Dutsen-Abba",
        "Gari",
        "Gora",
        "Kafin-Kaya",
        "Kura",
        "Tudun-Wada",
      ],
      "Kano Municipal": [
        "Bompai",
        "Dala",
        "Fagge",
        "Gaya",
        "Gwale",
        "Kano City",
        "Kofar Kudu",
        "Kofar Nasarawa",
        "Kofar Ruwa",
        "Rimi",
      ],
      Karaye: [
        "Bunkure",
        "Dambatta",
        "Dandago",
        "Danbata",
        "Kafin-Koro",
        "Karaye",
        "Kudu",
        "Rim",
      ],
      Kiru: [
        "Baba",
        "Bunkure",
        "Dambatta",
        "Dawakin Tofa",
        "Kiru",
        "Madobi",
        "Rano",
      ],
      Kumbotso: ["Dandago", "Kumbots", "Rurum", "Tudun Wada"],
      Kunchi: ["Gafasa", "Kunchi", "Maiduguri", "Tudun Wada"],
      Kura: ["Dara", "Gaya", "Kura", "Maiduguri", "Mashi"],
      Madobi: [
        "Ajuji",
        "Doguwa",
        "Falgore",
        "Madobi",
        "Rijiyar Lemo",
        "Tudun Wada",
      ],
      Makoda: ["Dambatta", "Kano", "Makoda", "Tudun Wada"],
      Minjibir: [
        "Ajao",
        "Baba",
        "Dambatta",
        "Gajiram",
        "Garko",
        "Kaoje",
        "Mara",
        "Minjibir",
        "Rano",
      ],
      Rano: ["Doguwa", "Garin-Mallam", "Kibiya", "Rano", "Tarauni"],
      "Rimin Gado": [
        "Rimin Gado",
        "Ganduje",
        "Kaya",
        "Kunchi",
        "Maiduguri",
        "Tsamiya",
      ],
      Rogo: ["Dambatta", "Rogo", "Rimin Gado"],
      Shanono: ["Dandago", "Gwarzo", "Kofar Kudu", "Rano", "Shanono"],
      Sumaila: [
        "Dakarawa",
        "Dambatta",
        "Falgore",
        "Gawar",
        "Kunya",
        "Maiduguri",
        "Rimin Gado",
        "Sakoda",
        "Sumaila",
      ],
      Takai: ["Bakin Kasuwa", "Danba", "Garin Malam", "Kafin Madaki", "Takai"],
      Tarauni: [
        "Baba Garin",
        "Gawo",
        "Kabo",
        "Karkasara",
        "Kwari",
        "Mariri",
        "Murtala",
      ],
      Tofa: ["Dandago", "Jirgi", "Karamai", "Kodo", "Ramin Kura", "Tofa"],
      Tsanyawa: [
        "Dawakin Tofa",
        "Gwarzo",
        "Kunchi",
        "Manda",
        "Maiduguri",
        "Tsanyawa",
      ],
      "Tudun Wada": [
        "Dandago",
        "Dawakin Tofa",
        "Kafin Madaki",
        "Kano City",
        "Rogo",
        "Tudun Wada",
      ],
      Ungogo: ["Ungogo", "Ganduje", "Dawanau", "Kabo", "Karkasara", "Kurfai"],
      Warawa: ["Dan-Agundi", "Garuwa", "Malamai", "Mudu", "Warawa"],
      Wudil: ["Dawakin Kudu", "Garko", "Gaya", "Kunchi", "Mudi", "Wudil"],
    },
  },
  {
    Katsina: {
      Bakori: ["Bakori", "Dandume", "Kuduna", "Mashi", "Zango"],
      Batagarawa: [
        "Batagarawa",
        "Dandume",
        "Dutsi",
        "Funtua",
        "Kafur",
        "Kaita",
        "Kankara",
        "Katsina",
      ],
      Batsari: [
        "Batsari",
        "Dutsi",
        "Gulbi",
        "Kafur",
        "Kuka",
        "Mashi",
        "Rawayya",
        "Sabo",
        "Sabulum",
      ],
      Baure: [
        "Baure",
        "Dabunkin Tofa",
        "Danjankuka",
        "Gidan Dutsi",
        "Gidan Kankiya",
        "Gusau",
        "Janguza",
        "Matsinawa",
        "Sabuwa",
        "Tashar Dan Bawa",
      ],
      Bindawa: [
        "Bindawa",
        "Dutsi",
        "Kofar Sauri",
        "Kofaru",
        "Mashi",
        "Rimi",
        "Tashar",
      ],
      Charanchi: [
        "Charanchi",
        "Dandume",
        "Garu",
        "Jangarau",
        "Kurfi",
        "Mai’Adua",
        "Tudun Wada",
      ],
      Dandume: ["Dandume", "Dandume Town", "Funtua", "Kankara", "Kara"],
      Danja: [
        "Danja",
        "Dogo",
        "Fago",
        "Gafai",
        "Jibia",
        "Kurfi",
        "Rimi",
        "Yar'aduwa",
      ],
      "Dan Musa": [
        "Dan Musa",
        "Dutsi",
        "Jibia",
        "Kankara",
        "Mashi",
        "Matazu",
        "Rimi",
        "Zango",
      ],
      Daura: ["Daura", "Dutsi", "Kankia", "Kusada", "Mai’adua", "Sandamu"],
      Dutsi: ["Dutsi", "Dutsinma", "Goribawa", "Kafur", "Kankara"],
      "Dutsin-Ma": ["Dutsin-Ma", "Kankara", "Kankiya", "Katsina"],
      Faskari: [
        "Faskari",
        "Funtua",
        "Goribawa",
        "Jibia",
        "Mairuwa",
        "Musa",
        "Ruwan Zafi",
      ],
      Funtua: [
        "Funtua",
        "Dandume",
        "Jibia",
        "Kafur",
        "Malumfashi",
        "Mashi",
        "Rimi",
      ],
      Ingawa: ["Ingawa", "Dandume", "Kanyau", "Kurfi", "Rimi"],
      Jibia: [
        "Bakin Kasuwa",
        "Borehole",
        "Jibia",
        "Kafur",
        "Mabera",
        "Mai'aduwa",
        "Shargalle",
        "Tudun Wada",
      ],
      Kafur: [
        "Ajiwa",
        "Dandume",
        "Kafur",
        "Kafur Town",
        "Katsina",
        "Ruma",
        "Tsaskiya",
      ],
      Kaita: ["Kaita", "Dutsi", "Jibia", "Kafur", "Kankara", "Zango"],
      Kankara: [
        "Abdallawa",
        "Dutsinma",
        "Gidan Dawa",
        "Kankara",
        "Mara",
        "Sabuwa",
      ],
      Kankia: [
        "Daddara",
        "Gadawa",
        "Kankia",
        "Karamai",
        "Kusada",
        "Rimi",
        "Sabuwa",
      ],
      Katsina: [
        "Daddara",
        "Gadawa",
        "Kankia",
        "Karamai",
        "Kusada",
        "Rimi",
        "Sabuwa",
      ],
      Kurfi: [
        "Ajiwa",
        "Babba",
        "Daddara",
        "Gandu",
        "Goribawa",
        "Kurfi",
        "Mara",
        "Rafin Titi",
      ],
      Kusada: ["Bani", "Dabawa", "Dutsin-Ma", "Kusada", "Rimi", "Yanduna"],
      "Mai'Adua": [
        "Bajoga",
        "Daddara",
        "Dantusa",
        "Dunya",
        "Jibiya",
        "Kankia",
        "Mai'Adua",
        "Sabuwa",
        "Wurma",
      ],
      Malumfashi: [
        "Dandume",
        "Gora",
        "Jibia",
        "Kankara",
        "Kankia",
        "Katsina",
        "Malumfashi",
        "Sabuwa",
        "Zango",
      ],
      Mani: [
        "Bauchi",
        "Dutsin-Ma",
        "Jibia",
        "Kankara",
        "Mani",
        "Mashi",
        "Sabuwa",
      ],
      Mashi: ["Dabai", "Dandume", "Kaita", "Mashi", "Sabuwa", "Tsaskiya"],
      Matazu: [
        "Batsari",
        "Dandume",
        "Garu",
        "Gora",
        "Kankia",
        "Matazu",
        "Yantumaki",
      ],
      Musawa: [
        "Bakin Kogi",
        "Batsari",
        "Daki Takwas",
        "Dutsi",
        "Gandun",
        "Karkarna",
        "Musawa",
        "Rimin Gado",
        "Sabon Gari",
        "Zangon",
      ],
      Rimi: ["Bakin Kasuwa", "Dandume", "Doka", "Kankia", "Katsina", "Rimi"],
      Sabuwa: ["Dandume", "Jibiya", "Kaita", "Katsina", "Sabuwa", "Zango"],
      Safana: [
        "Babban Dodo",
        "Dandume",
        "Dutsin-Ma",
        "Funtua",
        "Safana",
        "Yandoto",
      ],
      Sandamu: [
        "Ajiwa",
        "Bature",
        "Dandume",
        "Dutsen Baushe",
        "Goribawa",
        "Jibiya",
        "Kankara",
        "Sandamu",
      ],
      Zango: [
        "Daddara",
        "Danmusa",
        "Kafur",
        "Katsina",
        "Kudi",
        "Mashi",
        "Musu",
        "Rimi",
        "Zango",
      ],
    },
  },
  {
    Kebbi: {
      Aleiro: [
        "Aleiro",
        "Bakin Kogi",
        "Bakin Kasuwa",
        "Dan Alhaji",
        "Gidan Sarki",
        "Karabi",
        "Kiyawa",
        "Kwana",
        "Mairairai",
        "Wara",
      ],
      "Arewa Dandi": [
        "Dandi",
        "Dumi",
        "Gwandu",
        "Jega",
        "Kangiwa",
        "Koko",
        "Koko-Besse",
        "Maiyama",
        "Yauri",
      ],
      Argungu: [
        "Argungu",
        "Danko",
        "Gaya",
        "Gwandu",
        "Jega",
        "Kamba",
        "Kangiwa",
        "Koko",
        "Maiyama",
        "Yawuri",
      ],
      Augie: ["Augie", "Bena", "Gabi", "Jega", "Kamba", "Koko", "Zauro"],
      Bagudo: [
        "Bagudo",
        "Bena",
        "Gaya",
        "Garin Bawa",
        "Garin Kogi",
        "Kangiwa",
        "Koko",
        "Rafin Kawa",
      ],
      "Birnin Kebbi": [
        "Birnin Kebbi",
        "Argungu",
        "Dakingari",
        "Jega",
        "Kalgo",
        "Kamba",
        "Maiyama",
        "Sakaba",
        "Shanga",
        "Yauri",
      ],
      Bunza: ["Bunza", "Kangiwa", "Kuchi", "Gungunyi"],
      Dandi: ["Dandi", "Kamba", "Koko", "Wara"],
      Fakai: [
        "Bena",
        "Fakai",
        "Gagara",
        "Gulumbe",
        "Koko",
        "Kyauna",
        "Maska",
        "Sakaba",
      ],
      Gwandu: ["Bagudo", "Bena", "Gwandu", "Jega", "Koko", "Maiyama", "Yauri"],
      Jega: ["Bagudo", "Birnin Kebbi", "Jega", "Kanya", "Koko", "Yauri"],
      Kalgo: ["Bagudo", "Kalgo", "Kamba", "Wara"],
      "Koko/Besse": ["Besse", "Koko", "Mairi", "Rafin Gora", "Rijau", "Wara"],
      Maiyama: [
        "Aupo",
        "Bagudo",
        "Bawa",
        "Kabi",
        "Maiyama",
        "Malabu",
        "Manawachi",
        "Shiyar Bawa",
        "Sori",
      ],
      Ngaski: [
        "Bagudo",
        "Bodinga",
        "Gando",
        "Gawkungo",
        "Gwadangaji",
        "Koko",
        "Ngaski",
        "Rafin-Kasawa",
        "Saminaka",
      ],
      Sakaba: [
        "Bakuri",
        "Bini",
        "Dole-Kaina",
        "Fakon",
        "Gari",
        "Gashua",
        "Kamawa",
        "Katanga",
        "Kebbi",
        "Rafin-Kada",
        "Sakaba",
      ],
      Shanga: [
        "Argungu",
        "Bena",
        "Bugundu",
        "Dakingari",
        "Garin Baka",
        "Garin Jega",
        "Gwanara",
        "Kangiwa",
        "Kofar Gayan",
        "Maiyama",
        "Zauro",
      ],
      Suru: [
        "Bagudo",
        "Dakingari",
        "Gwandu",
        "Kangiwa",
        "Koko",
        "Suru",
        "Wara",
      ],
      "Wasagu/Danko": [
        "Danko",
        "Gwandu",
        "Jega",
        "Kamba",
        "Koko",
        "Shanga",
        "Wasagu",
      ],
      Yauri: [
        "Bena",
        "Danzomo",
        "Gulbadi",
        "Koko",
        "Ndaya",
        "Sambawa",
        "Yauri",
      ],
      Zuru: ["Bagudo", "Dandi", "Gwandu", "Jega", "Koko", "Maiyama", "Yauri"],
    },
  },
  {
    Kogi: {
      Adavi: ["Adavi", "Ajao", "Eika", "Ikuehi", "Odeke", "Oko"],
      Ajaokuta: ["Ajaokuta", "Adogo", "Eganyi", "Felele", "Kuroko", "Zango"],
      Ankpa: [
        "Abocho",
        "Ankpa",
        "Egume",
        "Ife-Olukotun",
        "Ogbogbo",
        "Okpo",
        "Ugwolawo",
      ],
      Bassa: ["Bassa", "Gegu", "Kiri", "Rumu", "Shiri"],
      Dekina: ["Dekina", "Egume", "Ofu", "Oguma", "Okura", "Udege"],
      Ibaji: [
        "Ajaka",
        "Igalamela",
        "Ibaji",
        "Igala-Mela",
        "Ogbogu",
        "Oboroke",
        "Orokere",
        "Ugwolawo",
      ],
      Idah: ["Idah", "Igala-Mela", "Igala", "Inye", "Onyedega", "Ugwolawo"],
      "Igalamela-Odolu": [
        "Abocho",
        "Ajaka",
        "Igalamela",
        "Odolu",
        "Ogugu",
        "Opeyi",
      ],
      Ijumu: [
        "Aiyegunle",
        "Egbe",
        "Ifeoluwapo",
        "Ijumu",
        "Ikoyi",
        "Ilero",
        "Odo-Ere",
        "Omi",
        "Sakaba",
      ],
      "Kabba/Bunu": [
        "Bunu",
        "Ifeolugbin",
        "Kabba",
        "Odo-Ere",
        "Omi",
        "Omi-Oka",
      ],
      Kogi: ["Ajaokuta", "Ogaminana", "Okehi", "Okene", "Okehi"],
      Lokoja: [
        "Lokoja",
        "Felele",
        "Kabba",
        "Ogaminana",
        "Ohinoyi",
        "Niger",
        "Ajaokuta",
      ],
      "Mopa-Muro": [
        "Lokoja",
        "Felele",
        "Akpanya",
        "Mopa",
        "Muro",
        "Okehi",
        "Ogori",
        "Orokere",
        "Rim",
        "Kabba",
        "Ogaminana",
        "Ohinoyi",
        "Niger",
        "Ajaokuta",
      ],
      Ofu: ["Adavi", "Ofu", "Ohu", "Otukpa", "Ugbokolo"],
      "Ogori/Magongo": [
        "Abobo",
        "Ajaokuta",
        "Ifeoluwapo",
        "Koton-Karfe",
        "Magongo",
        "Ogori",
        "Ogbogbo",
      ],
      Okehi: [
        "Ajao",
        "Eika",
        "Ekue",
        "Okengwe",
        "Okehi",
        "Okehi Town",
        "Oyin",
        "Uruvi",
      ],
      Okene: [
        "Adavi",
        "Ajao",
        "Ifeh",
        "Ikuehi",
        "Okene",
        "Okehi",
        "Ohinoyi",
        "Okehi",
        "Ogaminana",
        "Ubo",
      ],
      Olamaboro: [
        "Abejukolo",
        "Ajaokuta",
        "Ajaka",
        "Epeje",
        "Itobe",
        "Olamaboro",
        "Okura",
        "Ugep",
      ],
      Omala: ["Egume", "Imane", "Olu", "Ozugbe", "Ugwolawo"],
      "Yagba East": [
        "Aiyegunle",
        "Egbe",
        "Kabba",
        "Odo-Ere",
        "Odo-Ape",
        "Okehi",
        "Yagba",
      ],
      "Yagba West": [
        "Aiyegunle",
        "Ejiba",
        "Gbeleko",
        "Kabba",
        "Mopa",
        "Odo-Ere",
        "Odo-Ire",
        "Okunran",
        "Okehi",
        "Yagba",
      ],
    },
  },
  {
    Kwara: {
      Asa: [
        "Bode-Saadu",
        "Gaa-Akanbi",
        "Gaa-Odota",
        "Gaa-Saadu",
        "Ilesha-Baruba",
        "Koro",
        "Kpada",
        "Moro",
        "Oke-Onigbin",
      ],
      Baruten: [
        "Bode Saadu",
        "Chikanda",
        "Gwanara",
        "Koro",
        "Kosubosu",
        "Maska",
        "Odo-Owa",
        "Okuta",
        "Pampo",
        "Yashikira",
      ],
      Edu: [
        "Afon",
        "Ajase-Ipo",
        "Epe",
        "Ilesha-Baruba",
        "Ipee",
        "Jebba",
        "Kwara",
        "Patigi",
      ],
      Ekiti: [
        "Ekiti",
        "Idofin",
        "Ilemona",
        "Ilesha Baruba",
        "Oke Onigbin",
        "Oke Ero",
        "Oke Oyi",
      ],
      Ifelodun: [
        "Arandun",
        "Babanloma",
        "Bode-Saadu",
        "Esie",
        "Ijara-Isin",
        "Oke-Onigbin",
        "Oke-Ode",
      ],
      "Ilorin East": [
        "Alapa",
        "Alore",
        "Ijagbo",
        "Irepodun",
        "Isale-Koko",
        "Okepadi",
        "Oke-Ode",
        "Owode",
        "Sango",
      ],
      "Ilorin South": [
        "Apata",
        "Eruda",
        "Ilorin",
        "Okelele",
        "Oke-Ode",
        "Omu-Aran",
        "Share",
      ],
      "Ilorin West": [
        "Adabata",
        "Alagbado",
        "Apata",
        "Ilorin",
        "Okelele",
        "Oke-oyi",
        "Offa",
        "Sabo",
      ],
      Irepodun: [
        "Ajase-Ipo",
        "Erin-Ile",
        "Ijara-Isin",
        "Isin",
        "Omu-Aran",
        "Oke-Ode",
      ],
      Isin: [
        "Arandun",
        "Ejidongari",
        "Ilesha-Baruba",
        "Ijara",
        "Oke-Ode",
        "Okemesi",
        "Oke-Ero",
      ],
      Kaiama: ["Kaiama", "Kpada", "Kpotoro"],
      Moro: [
        "Bode-Saadu",
        "Edidi",
        "Iloffa",
        "Kpada",
        "Lafiagi",
        "Okuta",
        "Share",
      ],
      Offa: ["Offa", "Iludun", "Oloje", "Oke-Ode", "Oloje"],
      "Oke Ero": [
        "Afo",
        "Egbe",
        "Ilesha-Baruba",
        "Oke Ero (headquarters)",
        "Omu-Aran",
      ],
      Oyun: ["Ajase-Ipo", "Ilesha-Baruba", "Ilesha", "Owode", "Oyun", "Pata"],
      Patigi: [
        "Araromi",
        "Bode Saadu",
        "Jebba",
        "Kpata",
        "Patigi",
        "Shonga",
        "Tungi",
      ],
    },
  },
  {
    Lagos: {
      Agege: [
        "Agege",
        "Alimosho",
        "Ifako-Ijaiye",
        "Iju",
        "Ogba",
        "Orile-Agege",
      ],
      "Ajeromi-Ifelodun": [
        "Ajegunle",
        "Apapa",
        "Ijeshatedo",
        "Ijora",
        "Ojo",
        "Randle",
      ],
      Alimosho: [
        "Ayobo",
        "Egbeda",
        "Ikotun",
        "Iyana-Ipaja",
        "Kola",
        "Liasu",
        "Mosan-Okunola",
        "Ogunlana",
        "Shasha",
        "Tolu",
      ],
      "Amuwo-Odofin": [
        "Apple Junction",
        "Festac Town",
        "Ijegun",
        "Kirikiri",
        "Mile 2",
        "Satellite Town",
      ],
      Apapa: [
        "Apapa",
        "Apapa GRA (Government Reserved Area)",
        "Ebute Metta",
        "Ijora",
        "Liverpool",
        "Orile",
        "Tin Can Island",
      ],
      Badagry: [
        "Agbara",
        "Badagry",
        "Ibereko",
        "Mowo",
        "Olorunda",
        "Seme",
        "Topo",
        "Vity",
      ],
      Epe: [
        "Epe",
        "Ejirin",
        "Imota",
        "Ibeju",
        "Ijebu-Ode (part of it falls within Epe)",
        "Oke-Odo",
        "Oke-Ira",
        "Orimerunmu",
        "Poka",
        "Sabo",
      ],
      "Eti Osa": ["Ajah", "Ajao Estate", "Lekki", "Victoria Island"],
      "Ibeju-Lekki": [
        "Ajah",
        "Badore",
        "Dolphin Estate",
        "Eleko",
        "Ibeju",
        "Ikota",
        "Jakande Estate",
        "Lekki",
        "Magbon Alade",
        "Oko-Ajao",
        "Orimedu",
        "Victoria Island Extension",
      ],
      "Ifako-Ijaiye": ["Ifako", "Ijaiye", "Agege", "Ogba", "Pen Cinema"],
      Ikeja: [
        "Agege",
        "Alausa",
        "Agidingbi",
        "Computer Village",
        "Ikeja",
        "Magodo",
        "Ogba",
        "Pen Cinema",
        "Shogunle",
      ],
      Ikorodu: [
        "Agbowa",
        "Igbogbo",
        "Ikorodu",
        "Ijede",
        "Imota",
        "Isawo",
        "Odongunyan",
        "Ogijo",
      ],
      Kosofe: [
        "Agboyi-Ketu",
        "Alapere",
        "Anthony Village",
        "Ketu",
        "Magodo",
        "Mile 12",
        "Ogudu",
        "Shango",
        "Soluyi",
      ],
      "Lagos Island": [
        "Ajao Estate",
        "Apongbon",
        "Coker",
        "Idumota",
        "Lagos Island",
        "Oke-Popo",
        "Tinubu Square",
      ],
      "Lagos Mainland": [
        "Ebute Metta",
        "Fadeyi",
        "Ikorodu",
        "Iponri",
        "Jibowu",
        "Lafiaji",
        "Maroko",
        "Mende",
        "Mushin",
        "Oyingbo",
        "Shomolu",
        "Surulere",
        "Yaba",
      ],
      Mushin: [
        "Adamosa",
        "Ajele",
        "Anifowoshe",
        "Ashabi",
        "Durojaiye",
        "Ihama",
        "Isolo",
        "Itire",
        "Ketu",
        "Mushin",
        "Oke-Odo",
        "Onipanu",
        "Shasha",
        "Sura",
      ],
      Ojo: [
        "Ajangbadi",
        "Ajao Estate",
        "Amuwo Odofin",
        "Badagry Expressway",
        "Iba",
        "Igbede",
        "Ijanikin",
        "Ijegun",
        "Ojo",
        "Ojo Alaba",
        "Ojo Town",
      ],
      "Oshodi-Isolo": [
        "Ejigbo",
        "Isolo",
        "Oshodi",
        "Okota",
        "Ilasa",
        "Shogunle",
        "Orile-Agege",
      ],
      Shomolu: [
        "Bariga",
        "Fadeyi",
        "Gbagada",
        "Ifako",
        "Ketu",
        "Ogba",
        "Onipanu",
        "Palmgrove",
        "Shomolu",
        "Sabo",
      ],
      Surulere: [
        "Aguda",
        "Bode Thomas",
        "Coker",
        "Itire",
        "Kilo",
        "Lawanson",
        "Masha Nnobi",
        "Obele",
        "Onikan",
        "Ojuelegba",
        "Sari Iganmu",
        "Surulere (central area)",
      ],
    },
  },
  {
    Nasarawa: {
      Akwanga: [
        "Akwanga",
        "Gudi",
        "Keffi",
        "Nasarawa",
        "Nassarawa Eggon",
        "Panda",
      ],
      Awe: [
        "Awe",
        "Garu",
        "Gwandara",
        "Kofar Nassarawa",
        "Kwandere",
        "Lafia",
        "Rikau",
      ],
      Doma: [
        "Doma",
        "Daddare",
        "Doma Town",
        "Garin-Gada",
        "Gwari",
        "Karshi",
        "Mabudi",
        "Rinji",
      ],
      Karu: [
        "Gudi",
        "Karu",
        "Kwandare",
        "Mararaba",
        "New Karu",
        "Panda",
        "Sabo",
        "Uke",
      ],
      Keana: [
        "Adudu",
        "Bakin Kogi",
        "Gadabuke",
        "Kassap",
        "Keana",
        "Piti",
        "Rokoto",
        "Wada",
      ],
      Keffi: [
        "Abako",
        "Afo",
        "Angwan Daji",
        "Angwan Kogo",
        "Keffi",
        "Kwoi",
        "Moroa",
        "Nasarawa",
        "Nunkere",
        "Piti",
      ],
      Kokona: ["Doma", "Kokona", "Nasarawa", "Ribi", "Tunga", "Wamba"],
      Lafia: [
        "Agyaragu",
        "Daddare",
        "Doma",
        "Gadabuke",
        "Kwandare",
        "Lafia",
        "Moroa",
        "Nasarawa",
        "Rinza",
        "Toto",
      ],
      Nasarawa: ["Agyaragu", "Daddere", "Doma", "Gudi", "Nasarawa", "Tunga"],
      "Nasarawa Egon": [
        "Agyaragu",
        "Doma",
        "Egon",
        "Kabba",
        "Keffi",
        "Nasarawa Egon",
        "Tunga",
        "Zumbagbe",
      ],
      Obi: ["Adudu", "Ado", "Gwandara", "Mangu", "Obi", "Rinji", "Tunga"],
      Toto: ["Doma", "Gadagyi", "Karu", "Nasarawa", "Toto"],
      Wamba: [
        "Afo",
        "Angwan-Kasa",
        "Angwan-Logo",
        "Angwan-Moro",
        "Gidan-Bawa",
        "Gidan-Kogi",
        "Ishakoro",
        "Koto",
        "Wamba",
      ],
    },
  },
  {
    Niger: {
      Agaie: [
        "Agaie",
        "Auna",
        "Gaba",
        "Gulu",
        "Jima",
        "Kagarko",
        "Malle",
        "Nasko",
        "Sabo",
      ],
      Agwara: [
        "Agwara",
        "Babba",
        "Bago",
        "Bisa",
        "Gwari",
        "Kakuri",
        "Muna",
        "Sarkin Pawa",
        "Wawa",
      ],
      Bida: ["Bida", "Biri", "Gbara", "Lapai", "Mokwa", "Suleja", "Zungeru"],
      Borgu: ["Borgu", "Kangiwa", "New Bussa", "Piti"],
      Bosso: [
        "Bosso",
        "Chanchaga",
        "Farina",
        "Gidan Kwano",
        "Kpakungu",
        "Kure Kure",
        "Lapai",
        "Niger",
      ],
      Chanchaga: [
        "Baba",
        "Chanchaga",
        "Kpakungu",
        "Lapai",
        "Minna",
        "Sarkin Pawa",
      ],
      Edati: [
        "Borgu",
        "Edati",
        "Katcha",
        "Kutigi",
        "Lapai",
        "Lambata",
        "Mokwa",
        "Nasko",
      ],
      Gbako: [
        "Babba",
        "Doka",
        "Gbaran",
        "Gbako",
        "Gidan Goga",
        "Kundu",
        "Rafin-Kahugu",
      ],
      Gurara: ["Gurara", "Kuta", "Mada", "Shiroro", "Tafa", "Zuba"],
      Katcha: ["Doko", "Katcha", "Kogo", "Lemu", "Panda", "Rafi"],
      Kontagora: [
        "Bungudu",
        "Gidan Boka",
        "Gidan Kwano",
        "Gidan Waya",
        "Kankia",
        "Kontagora",
        "Rijau",
        "Sarkin Pawa",
      ],
      Lapai: [
        "Bida",
        "Dibo",
        "Kpada",
        "Lapai",
        "Lemu",
        "Nasko",
        "Sabo",
        "Shahuchi",
      ],
      Lavun: [
        "Adonu",
        "Doko",
        "Gurara",
        "Lavun",
        "Lemu",
        "Machi",
        "Piti",
        "Raji",
      ],
      Magama: [
        "Bangi",
        "Borgu",
        "Doko",
        "Katcha",
        "Magama",
        "Nasko",
        "Rafi",
        "Suleja",
      ],
      Mariga: ["Bakin Kogi", "Bana", "Gulu", "Kagara", "Mariga", "Rafin Yashi"],
      Mashegu: ["Danko", "Gimba", "Mashegu", "Niger", "Rijau"],
      Mokwa: [
        "Bokani",
        "Gaba",
        "Gidan-Kwari",
        "Jebba",
        "Kainji",
        "Kodo",
        "Mokwa",
        "Ndaruka",
        "Rijau",
        "Shiroro",
      ],
      Munya: ["Bida", "Kuta", "Lapai", "Munya", "Shinny"],
      Paikoro: [
        "Bida",
        "Garin Malam",
        "Gwari",
        "Katcha",
        "Kpada",
        "Paikoro",
        "Suleja",
      ],
      Rafi: [
        "Babba",
        "Bola",
        "Dahna",
        "Fuka",
        "Kagara",
        "Mariga",
        "Manga",
        "Rafi",
        "Rijau",
        "Wawa",
      ],
      Rijau: ["Agaie", "Boni", "Garu", "Jebba", "Kpotama", "Rijau", "Tafa"],
      Shiroro: [
        "Bassa",
        "Kuta",
        "Minna",
        "Rafi",
        "Rijau",
        "Sabo",
        "Shiroro",
        "Wawa",
      ],
      Suleja: [
        "Baba Jukuy",
        "Gwagwa",
        "Kofar Doka",
        "Kuchi",
        "Maje",
        "Suleja",
        "Tafa",
        "Zuba",
      ],
      Tafa: [
        "Borgu",
        "Daga",
        "Gari",
        "Kakuri",
        "Madaka",
        "Nasko",
        "Suleja",
        "Tafa",
        "Zuba",
      ],
      Wushishi: [
        "Basa",
        "Dabugi",
        "Gurdi",
        "Kucheri",
        "Lapai",
        "Maka",
        "Miawo",
        "Rafin-Kanya",
        "Wushishi",
        "Yashi",
      ],
    },
  },
  {
    Ogun: {
      "Abeokuta North": [
        "Aregbe",
        "Ibara",
        "Imo",
        "Itoko",
        "Oke-Ata",
        "Onikolobo",
        "Obantoko",
      ],
      "Abeokuta South": [
        "Adigbe",
        "Ake",
        "Alabata",
        "Ago-Iwoye",
        "Ibara",
        "Ijemo",
        "Imo",
        "Isale Igbein",
        "Oke-Ilewo",
        "Oke-Lantoro",
        "Oke-Ogun",
        "Sabo",
        "Sodeke",
        "Sokori",
      ],
      "Ado-Odo/Ota": [
        "Ado-Odo",
        "Agbara",
        "Ajuwon",
        "Akute",
        "Alagbado",
        "Ijoko",
        "Iyesi",
        "Ota",
        "Sango",
        "Sango-Ota",
      ],
      "Egbado North": [
        "Alagbole",
        "Asejire",
        "Imota",
        "Ijako",
        "Ijebu-Ife",
        "Ikenne",
        "Ise",
        "Itamogiri",
        "Iyana Ilogbo",
        "Oke-Odo",
        "Ogba",
        "Ogijo",
        "Ogunti",
        "Sango",
      ],
      "Egbado South": [
        "Ayetoro",
        "Iganmode",
        "Ilaro",
        "Imasayi",
        "Oke-Odan",
        "Oke-Sokori",
        "Oke-Yeke",
        "Ogere",
        "Oke-Aro",
        "Opeji",
      ],
      Ewekoro: [
        "Ewekoro",
        "Imasayi",
        "Ipara",
        "Lafenwa",
        "Ogijo",
        "Odogunyan",
        "Oke-Odo",
        "Ilese",
        "Ijako",
        "Alagbole",
      ],
      Ifo: ["Ado-Odo", "Agbado", "Ibafo", "Ifo", "Itele", "Ogunmakin"],
      "Ijebu East": [
        "Alapako",
        "Agbowa",
        "Afo",
        "Akinsan",
        "Epe",
        "Igbogbo",
        "Ikorodu",
        "Ijebu",
        "Ilese",
        "Imota",
        "Isiu",
        "Itoga",
        "Oke-Ota",
        "Olorunda",
        "Oluwa",
        "Odogunyan",
        "Olowogbowo",
        "Onipanu",
        "Oniru",
        "Orimedu",
        "Otao",
        "Sabo",
      ],
      "Ijebu North": [
        "Ajegunle",
        "Epe",
        "Ibeju",
        "Ijebu-Igbo",
        "Ijebu-Ode",
        "Ilese",
        "Itele",
        "Odo-Aye",
        "Odo-Egiri",
        "Odo-Otua",
      ],
      "Ijebu North-East": [
        "Ajao",
        "Agbowa",
        "Alapoti",
        "Asiwaju",
        "Ijebu-Igbo",
        "Ijebu-Ode",
        "Ijebu-Remo",
        "Imo",
        "Itamogiri",
        "Odo-Eran",
        "Oke-Ore",
        "Oke-Sopen",
      ],
      "Ijebu Ode": [
        "Ayegbami",
        "Ijebu Ode",
        "Ijebu-Ife",
        "Imo",
        "Itamapako",
        "Oke-Sopen",
        "Oru",
        "Ososa",
        "Owo",
      ],
      Ikenne: ["Agura", "Ikenne", "Irolu", "Odogbolu", "Ogere"],
      "Imeko-Afon": ["Imeko", "Afon", "Agosasa", "Asiko", "Ijoun", "Oja-Odan"],
      Ipokia: [
        "Agosasa",
        "Ijebu-Igbo",
        "Ijebu-Ode",
        "Ijebu-South",
        "Ilaro",
        "Imeko",
        "Iporo-Akede",
        "Mamu",
        "Oke-Odan",
        "Olowogbowo",
        "Orile-Imo",
        "Pako",
        "Sabe",
        "Sango",
      ],
      "Obafemi-Owode": [
        "Awa",
        "Gbonagun",
        "Ibafo",
        "Ifo",
        "Imo",
        "Mowe",
        "Ogijo",
        "Owode",
        "Ota",
        "Sango",
      ],
      Odeda: [
        "Abeokuta",
        "Akinsehinwa",
        "Araromi",
        "Ibogun",
        "Ilugun",
        "Imeri",
        "Ode Omi",
        "Ode Remo",
        "Odeda",
        "Oba",
        "Oni",
        "Oniyide",
        "Oniyan",
        "Oyo",
      ],
      Odogbolu: [
        "Aiyepe",
        "Ala",
        "Apogun",
        "Enyinwa",
        "Ibefun",
        "Igbaga",
        "Ikenne",
        "Ilese",
        "Ilyushin",
        "Imosan",
        "Irolu",
        "Moloko-Asipa",
        "Odogbolu",
        "Ogbo",
        "Omu",
        "Ososa",
      ],
      "Remo North": ["Akaka", "Ilara", "Isara", "Ode-Remo", "Orile-Oko"],
      Sagamu: [
        "Agbowa",
        "Aiyepe",
        "Ajaka",
        "Ajegunle",
        "Akeredolu",
        "Akimbo",
        "Alara",
        "Ayegbami",
        "Ayetoro",
        "Batoro",
        "Epe",
        "Ewuga",
        "Igbepa",
        "Ijagba",
        "Isale Oko",
        "Isote",
        "Iwelepe",
        "Latawa",
        "Liyangu",
        "Makun",
        "Ogijo",
        "Ode-Remo",
        "Ogere",
        "Oke-Ilewo",
        "Oko-Ita",
        "Sabo",
        "Simawa",
        "Soyindo",
      ],
    },
  },
];
