export const industryOptions = [
  "Realtors",
  "Real Estate Agent",
  "Attorneys",
  "Investors",
  "Broker",
  "Estate Agent",
  "Barristers",
  "Arbitrators",
  "Solicitors",
  "Advocates",
  "Lawyer",
  "Legal Practitioner",
  "Law Firm",
  "Real Estate Appraiser",
  "Property Analyst",
  "Facility Manager",
  "Estate Surveyor & Valuer",
  "Property Manager",
  "Contractor",
  "Land Surveyor",
  "Hotel Manager",
  "Architect",
  "Builder",
  "Developer",
  "Town Planner",
  "Civil Engineer",
  "Caretaker",
  "Quantity Surveyor",
  "Property Supervisor",
  "Real Estate Developer",
  "Real Estate Investors",
  "Property Developers",
  "Hospitality Company",
  "Joint Business",
  "Enterprise",
  "Sole Proprietorship ",
  "Real Estate Company",
];

export const titleOrQualifications = [
  "Prince",
  "Princess",
  "Alhaji",
  "Alhaja",
  "Mr",
  "Mrs",
  "Esv",
  "Esq",
  "LL.B ",
  "RSV ",
  "Anvis",
  "ANIM",
  "Dr",
  "Proff",
  "Rtp",
  "Mnitp",
  "Mnim",
  "MMP",
  "Fipman",
  "Fcicpfm",
  "TPL",
  "MBA",
  "PMP",
  "F.ASCE",
  "M.NSE",
  "F.NICE",
  "MAPM",
  "OON",
  "FNIA",
  "PPNIA",
  "PPARCON",
  "MMI",
  "AIA",
  "ENGR",
];
