export interface BranchAPIResponse {
  status: string;
  message: string;
  data: {
    branch: {
      id: number;
      company_id: number;
      is_active: boolean;
      branch_name: string;
      picture: string;
      state: string;
      local_government: string;
      city: string;
      branch_desc: string;
      branch_address: string;
      email: string | null;
      bank_name: string;
      account_name: string;
      account_number: string;
      staffs_count: number;
      properties_count: number;
      landlords_count: number;
      tenants_count: number;
      complaints_count: number;
      invoice_count: number;
      inquiry_count: number;
      current_month_inquiry_count: number;
      current_month_complaints_count: number;
      current_month_staffs_count: number;
      current_month_invoice_count: number;
      current_month_properties_count: number;
      current_month_landlords_count: number;
      current_month_tenants_count: number;
      receipt_statistic: {
        total_receipt: string;
        total_paid_receipt: string;
        total_pending_receipt: string;
        percentage_change_total: number;
        percentage_change_paid: number;
        percentage_change_pending: number;
      };
      staffs: Array<{
        id: number;
        user_id: number;
        is_active: boolean;
        title: string | null;
        professional_title: string | null;
        picture: string;
        staff_role: string;
        name: string;
        tier: number;
        online_status: string;
      }>;
      properties: Array<{
        id: number;
        branch_id: number;
        inventory_id: number | null;
        landlord_id: number | null;
        user_id: number;
        company_id: number;
        video_link: string | null;
        title: string;
        state: string;
        local_government: string;
        city_area: string;
        full_address: string;
        category: string;
        description: string;
        property_type: string;
        agency_fee: number;
        who_to_charge_new_tenant: string | null;
        who_to_charge_renew_tenant: string | null;
        caution_deposit: string | null;
        group_chat: boolean;
        rent_penalty: boolean;
        fee_penalty: boolean;
        request_call_back: boolean;
        book_visitors: boolean;
        vehicle_record: boolean;
        active_vat: boolean;
        currency: string;
        coordinate: string | null;
        management_fee: number;
        fee_period: string | null;
        is_featured: boolean;
        is_inventory: number;
        created_at: string;
        updated_at: string;
        deleted_at: string | null;
        image_count: number;
        unit_count: number;
        review_count: number;
        units: Array<{
          id: number;
          user_id: number;
          property_id: number;
          tenant_id: number;
          unit_name: string;
          unit_type: string;
          unit_sub_type: string;
          unit_preference: string;
          measurement: string;
          bedroom: string;
          bathroom: string;
          toilet: number;
          facilities: string | null;
          en_suit: boolean;
          prepaid: boolean;
          wardrobe: boolean;
          pet_allowed: boolean;
          total_area_sqm: string | null;
          number_of: string;
          fee_period: string;
          fee_amount: string;
          vat_amount: string;
          security_fee: string;
          service_charge: string;
          agency_fee: string;
          legal_fee: string;
          caution_fee: string;
          inspection_fee: string;
          management_fee: string | null;
          other_charge: string;
          negotiation: boolean;
          total_package: string;
          renew_fee_period: string;
          renew_fee_amount: string;
          renew_vat_amount: string;
          renew_service_charge: string;
          renew_other_charge: string;
          renew_total_package: string;
          renew_agency_fee: string;
          renew_security_fee: string;
          renew_legal_fee: string | null;
          renew_caution_fee: string | null;
          renew_inspection_fee: string | null;
          renew_management_fee: string | null;
          is_active: string;
          published: boolean;
          status: string;
          reject_reason: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        }>;
      }>;
      activities: Array<{
        S_N: number;
        title: string;
        description: string;
        ip_address: string;
        location: {
          city: string;
          country: string;
          latitude: number;
          longitude: number;
        };
        created_at: string;
        updated_at: string;
        date: string;
        time: string;
      }>;
      created_at: string;
      updated_at: string;
      vacant_unit: number;
      vacant_month_unit: number;
      expired_unit: number;
      expired_month_unit: number;
      listing: number;
      listing_month: number;
    };
    manager: {
      id: number;
      user_id: number;
      company_id: number;
      branch_id: number;
      is_active: boolean;
      title: string;
      professional_title: string;
      years_experience: string | null;
      staff_role: string;
      deleted_at: string | null;
      created_at: string;
      updated_at: string;
      user: {
        id: number;
        encodedId: string;
        name: string;
        email: string;
        phone: string;
        username: string | null;
        referrer_code: string | null;
        email_verified_at: string;
        phone_verified_at: string | null;
        username_updated_at: string | null;
        is_active: boolean;
        is_company_owner: boolean;
        tier_id: number;
        last_seen: string | null;
        provider_id: string | null;
        provider_name: string | null;
        deleted_at: string | null;
        created_at: string;
        updated_at: string;
        is_verified: boolean;
        unread_messages_count: number;
        unread_notifications_count: number;
        profile_completion_status: string;
        is_subscription_expired: boolean;
        current_plan: string;
        current_subscription_expiry: string;
        profile: {
          id: number;
          user_id: number;
          type: string;
          name: string | null;
          email: string | null;
          phone: string | null;
          picture: string;
          background_image: string | null;
          title: string | null;
          gender: string;
          address: string | null;
          state: string | null;
          lga: string | null;
          city: string | null;
          bio: string | null;
          dob: string | null;
          religion: string | null;
          marital_status: string | null;
          occupation: string | null;
          job_type: string | null;
          family_type: string | null;
          facebook: string | null;
          x: string | null;
          instagram: string | null;
          linkedin: string | null;
          youtube: string | null;
          tiktok: string | null;
          website: string | null;
          note: string | null;
          bvn_link_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          bvn_linked: boolean;
          completion_status: string;
        };
      };
    };
    sub_wallet: {
      wallet_id: string | null;
      balance: string;
      escrow_balance: string;
      is_active: string;
      pin_status: boolean;
      credit_total: number;
      debit_total: number;
      balance_total: string;
      last_week_credit: number;
      last_week_debit: number;
      last_week_balance: number;
      recent_transactions: Array<{
        id: number;
        amount: string;
        transaction_type: string;
        reference: string;
        description: string;
        status: string;
        balance_before: string;
        balance_after: string;
        source_name: string;
        date: string;
      }>;
    };
    recent_transactions: Array<{
      id: number;
      amount: string;
      transaction_type: string;
      reference: string;
      description: string;
      status: string;
      balance_before: string;
      balance_after: string;
      source_name: string;
      date: string;
    }>;
  };
  errors: any;
}
