import { properties } from "@/app/(nav)/user/management/landlord/data";
import { UserProfileData } from "@/components/Management/Rent And Unit/application-user-card";
import { PropertyAllocation } from "@/components/Management/Rent And Unit/property-allocation-card";
import { Field } from "@/components/Table/types";
import { amber } from "@mui/material/colors";

export const applicationDummyData = [
  {
    id: "1",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "john doe",
    tier_id: "1",
    user_id: "user_001",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "john.doe@example.com",
    property_name: "Sunset Villa - Luxury Apartment",
    renew_fee_period: "yearly",
    address: "123 Main St, Ikoyi, Lagos, Lagos State",
    phone_number: "+2348012345678",
    date: "2025-08-01",
    total_package: "2,500,000",
    yearly_amount: "2,000,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "2",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "jane smith",
    tier_id: "2",
    user_id: "user_002",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "jane.smith@example.com",
    property_name: "Green Heights - Studio Flat",
    renew_fee_period: "monthly",
    address: "456 Oak Ave, Lekki, Lagos, Lagos State",
    phone_number: "+2348098765432",
    date: "2025-07-15",
    total_package: "1,200,000",
    yearly_amount: "100,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_001",
        flagger_name: "alice brown",
        email: "alice.brown@example.com",
        tier_id: "3",
        phone: "+2348011112222",
        company_name: "PropertyGuard Ltd",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Suspicious payment history",
        appeal_reason: "Payment issue resolved",
        status: "pending",
      },
    ],
  },
  {
    id: "3",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "michael okoro",
    tier_id: "1",
    user_id: "user_003",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "michael.okoro@example.com",
    property_name: "Ocean View - Penthouse",
    renew_fee_period: "yearly",
    address: "789 Beach Rd, Victoria Island, Lagos, Lagos State",
    phone_number: "+2348023456789",
    date: "2025-06-20",
    total_package: "5,000,000",
    yearly_amount: "4,500,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "4",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "sarah adebayo",
    tier_id: "3",
    user_id: "user_004",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "sarah.adebayo@example.com",
    property_name: "City Loft - One Bedroom",
    renew_fee_period: "monthly",
    address: "101 Pine St, Surulere, Lagos, Lagos State",
    phone_number: "+2348034567890",
    date: "2025-05-10",
    total_package: "800,000",
    yearly_amount: "70,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_002",
        flagger_name: "david lee",
        email: "david.lee@example.com",
        tier_id: "2",
        phone: "+2348022223333",
        company_name: "SafeHomes Inc",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Incomplete documentation",
        appeal_reason: "",
        status: "rejected",
      },
    ],
  },
  {
    id: "5",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "emeka chukwu",
    tier_id: "2",
    user_id: "user_005",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "emeka.chukwu@example.com",
    property_name: "Sky Towers - Two Bedroom",
    renew_fee_period: "yearly",
    address: "321 Cedar Rd, Ikeja, Lagos, Lagos State",
    phone_number: "+2348045678901",
    date: "2025-08-10",
    total_package: "3,000,000",
    yearly_amount: "2,800,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "6",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "chioma nwosu",
    tier_id: "1",
    user_id: "user_006",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "chioma.nwosu@example.com",
    property_name: "Palm Gardens - Bungalow",
    renew_fee_period: "monthly",
    address: "654 Elm St, Yaba, Lagos, Lagos State",
    phone_number: "+2348056789012",
    date: "2025-07-25",
    total_package: "1,500,000",
    yearly_amount: "120,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_003",
        flagger_name: "tolu ade",
        email: "tolu.ade@example.com",
        tier_id: "1",
        phone: "+2348033334444",
        company_name: "RealEstate Co",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Verification pending",
        appeal_reason: "Awaiting document submission",
        status: "evaluated",
      },
    ],
  },
  {
    id: "7",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "david okeke",
    tier_id: "t3",
    user_id: "user_007",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "david.okeke@example.com",
    property_name: "Blue Haven - Duplex",
    renew_fee_period: "yearly",
    address: "987 Maple Ave, Ajah, Lagos, Lagos State",
    phone_number: "+2348067890123",
    date: "2025-06-15",
    total_package: "4,200,000",
    yearly_amount: "4,000,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "8",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "amina bello",
    tier_id: "2",
    user_id: "user_008",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "amina.bello@example.com",
    property_name: "Urban Nest - Studio",
    renew_fee_period: "monthly",
    address: "147 Birch St, Gbagada, Lagos, Lagos State",
    phone_number: "+2348078901234",
    date: "2025-05-05",
    total_package: "900,000",
    yearly_amount: "80,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_004",
        flagger_name: "kemi olu",
        email: "kemi.olu@example.com",
        tier_id: "2",
        phone: "+2348044445555",
        company_name: "SecureProperties Ltd",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Failed background check",
        appeal_reason: "",
        status: "rejected",
      },
    ],
  },
  {
    id: "9",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "tunde lawal",
    tier_id: "1",
    user_id: "user_009",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "tunde.lawal@example.com",
    property_name: "Star Residences - Three Bedroom",
    renew_fee_period: "yearly",
    address: "258 Willow Rd, Ikota, Lagos, Lagos State",
    phone_number: "+2348089012345",
    date: "2025-08-12",
    total_package: "3,500,000",
    yearly_amount: "3,200,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "10",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg"],
    full_name: "fatima musa",
    tier_id: "3",
    user_id: "user_010",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "fatima.musa@example.com",
    property_name: "Golden Plaza - Apartment",
    renew_fee_period: "monthly",
    address: "369 Spruce St, Magodo, Lagos, Lagos State",
    phone_number: "+2348090123456",
    date: "2025-07-30",
    total_package: "1,800,000",
    yearly_amount: "150,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_005",
        flagger_name: "chidi eze",
        email: "chidi.eze@example.com",
        tier_id: "1",
        phone: "+2348055556666",
        company_name: "TrustHomes Ltd",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Discrepancy in application",
        appeal_reason: "Clarified details",
        status: "evaluated",
      },
    ],
  },
  {
    id: "11",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg"],
    full_name: "oliver igwe",
    tier_id: "2",
    user_id: "user_011",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "oliver.igwe@example.com",
    property_name: "Crystal Towers - Penthouse",
    renew_fee_period: "yearly",
    address: "741 Ash Rd, Lekki Phase 1, Lagos, Lagos State",
    phone_number: "+2348012345670",
    date: "2025-06-25",
    total_package: "6,000,000",
    yearly_amount: "5,500,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "12",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg"],
    full_name: "grace adeniyi",
    tier_id: "1",
    user_id: "user_012",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "grace.adeniyi@example.com",
    property_name: "Silver Court - Studio",
    renew_fee_period: "monthly",
    address: "852 Poplar St, Ogba, Lagos, Lagos State",
    phone_number: "+2348023456781",
    date: "2025-05-15",
    total_package: "950,000",
    yearly_amount: "85,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_006",
        flagger_name: "bola akin",
        email: "bola.akin@example.com",
        tier_id: "3",
        phone: "+2348066667777",
        company_name: "EliteProperties Ltd",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Invalid references",
        appeal_reason: "",
        status: "rejected",
      },
    ],
  },
  {
    id: "13",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg"],
    full_name: "peter obi",
    tier_id: "2",
    user_id: "user_013",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "peter.obi@example.com",
    property_name: "Emerald Gardens - Two Bedroom",
    renew_fee_period: "yearly",
    address: "963 Sycamore Rd, Ikeja GRA, Lagos, Lagos State",
    phone_number: "+2348034567892",
    date: "2025-08-05",
    total_package: "2,800,000",
    yearly_amount: "2,600,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
  {
    id: "14",
    application_status: "evaluated",
    images: ["/empty/SampleProperty.jpeg"],
    full_name: " Ngozi Eze",
    tier_id: "3",
    user_id: "user_014",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "flagged",
    user_type: "web",
    email: "ngozi.eze@example.com",
    property_name: "Royal Suites - Apartment",
    renew_fee_period: "monthly",
    address: "159 Chestnut St, Maryland, Lagos, Lagos State",
    phone_number: "+2348045678903",
    date: "2025-07-20",
    total_package: "1,600,000",
    yearly_amount: "130,000",
    period_type: "monthly",
    currency: "₦",
    flag_details: [
      {
        flagger_id: "flagger_007",
        flagger_name: "uche nwa",
        email: "uche.nwa@example.com",
        tier_id: "2",
        phone: "+2348077778888",
        company_name: "PrimeHomes Ltd",
        picture: "/empty/SampleLandlord.jpeg",
        is_flagged: true,
        reason: "Pending verification",
        appeal_reason: "Documents submitted",
        status: "evaluated",
      },
    ],
  },
  {
    id: "15",
    application_status: "approved",
    images: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty2.jpeg"],
    full_name: "yusuf ali",
    tier_id: "1",
    user_id: "user_015",
    photo: "/empty/SampleLandlord.jpeg",
    flagged: "unflagged",
    user_type: "mobile",
    email: "yusuf.ali@example.com",
    property_name: "Paradise Villas - Duplex",
    renew_fee_period: "yearly",
    address: "753 Magnolia Rd, Banana Island, Lagos, Lagos State",
    phone_number: "+2348056789014",
    date: "2025-06-10",
    total_package: "7,000,000",
    yearly_amount: "6,500,000",
    period_type: "yearly",
    currency: "₦",
    flag_details: [],
  },
];

export const sampleUser: UserProfileData = {
  name: "Abimbola Adedeji",
  profileImage: "/empty/SampleLandlord.jpeg",
  email: "abimbola@gmail.com",
  id: "22132876554444",
  status: "mobile",
  isVerified: true,
  gender: "Male",
  birthday: "12/12/12",
  religion: "Christianity",
  phone: "+2348132086958",
  maritalStatus: "Single",
  contactAddress: {
    address: "U4 Joke Plaza Bodija Ibadan",
    city: "Ibadan",
    state: "Oyo State",
    lg: "Ibadan North Central",
  },
};

export const payRecordFields: Field[] = [
  {
    id: "id",
    label: "S/N",
    accessor: "id",
  },
  {
    id: "payment_date",
    label: "Payment Date",
    accessor: "payment_date",
  },
  {
    id: "amount",
    label: "Amount",
    accessor: "amount",
  },
  {
    id: "details",
    label: "Details",
    accessor: "details",
  },
  {
    id: "due_date",
    label: "Due Date",
    accessor: "due_date",
  },
];

export const generateApplicationTable = (numItems: number) => {
  return Array.from({ length: numItems }, (_, index) => ({
    id: (index + 1).toString(),
    payment_date: `6/10/2024`,
    amount: `₦${(index + 1) * 100000}`,
    details: `Payment for Property ${index + 1}`,
    date_created: `6/10/2024`,
    due_date: `6/10/2024`,
  }));
};

export const mockProperties: PropertyAllocation[] = [
  {
    id: "123456776342",
    unitDetails: "Newly Built 5 Bedroom Detached Duplex",
    unitSubType: "bedroom duplex",
    unitPreference: "Newly Built",
    unitPrice: "300,000",
    unitType: "House",
    firstDeposit: "300,000",
    propertyImages: ["/empty/SampleProperty.jpeg"],
    hasVideo: true,
    managedBy: "Taiwo Salam and Co. Properties Limited",
    salesType: "Installment Sales",
    currency: "₦",
  },
  {
    id: "987654321098",
    unitDetails: "Modern 3 Bedroom Apartment",
    unitSubType: "bedroom apartment",
    unitPreference: "Furnished",
    unitPrice: "150,000",
    unitType: "Apartment",
    firstDeposit: "450,000",
    propertyImages: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty.jpeg", "/empty/SampleProperty.jpeg"],
    hasVideo: false,
    managedBy: "Premium Estates",
    salesType: "Rental",
    currency: "₦",
  },
  {
    id: "456789123456",
    unitDetails: "Luxury 4 Bedroom Penthouse",
    unitSubType: "bedroom penthouse",
    unitPreference: "Premium",
    unitPrice: "25,000,000",
    unitType: "Penthouse",
    firstDeposit: "5,000,000",
    propertyImages: ["/empty/SampleProperty.jpeg", "/empty/SampleProperty.jpeg"],
    hasVideo: true,
    managedBy: "Elite Properties International",
    salesType: "Outright Sales",
    currency: "₦",
  },
];
