import Head from "next/head";
import "@/styles/globals.css";

// Imports
import { Toaster } from "sonner";
import { primaryFont } from "@/utils/fonts";
import ThemeProvider from "./theme-provider";
import { Theme } from "@/components/theme";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <title>Create Next app</title>
      </Head>
      <body
        className={`${primaryFont.className} antialiased`}
        // suppressHydrationWarning
      >
        <Theme
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeProvider />
          <div className="w-full relative z-[1]">{children}</div>
          <div id="portal" className="z-[2]">
            <Toaster
              richColors
              className={`${primaryFont.className} antialiased z-[1000]`}
              position="top-right"
              duration={5000}
            />
          </div>
        </Theme>
      </body>
    </html>
  );
}
