import type { Metadata } from "next";
import Head from "next/head";
// Styles
import "@/styles/mobile.css";
import "@/styles/globals.css";

// Imports
import { Toaster } from "sonner";
import { dmSans } from "@/utils/fonts";
import ThemeProvider from "./theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dmSans.className} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider />
        <div className="w-full relative z-[1]">
          {children}
          <Toaster richColors className={`${dmSans.className} antialiased`} />
        </div>
        <div id="portal" className="z-[2]"></div>
      </body>
    </html>
  );
}
