import api from "@/services/api";
import { AxiosError } from "axios";
import { toast } from "sonner";

export const createVehicleRecord = async (data: any) => {
  try {
    const response = await api.post("/vehicle-record", data);
    if (response.status >= 200 && response.status < 300) {
      toast.success("Vehicle record created successfully.");
    } else {
      toast.error("Unexpected response from the server.");
    }
  } catch (error) {
    if (error instanceof AxiosError) {
      toast.error(`Error: ${error.response?.data?.message || error.message}`);
    } else {
      console.error(error);
      toast.error("An unexpected error occurred.");
    }
  }
};











export const vehicleData = {
  Cars: {
    brands: [
      "Acura",
      "Alfa Romeo",
      "Aston Martin",
      "Avatr",
      "BAIC",
      "BAW",
      "Bentley",
      "BMW",
      "Brabus",
      "Brilliance",
      "Buick",
      "Cadillac",
      "Changan",
      "Chevrolet",
      "Chery",
      "Chrysler",
      "Citroen",
      "Dacia",
      "Daewoo",
      "Daihatsu",
      "Dongfeng",
      "Ferrari",
      "Fiat",
      "Foton",
      "Geely",
      "Genesis",
      "Higer",
      "Huawei",
      "Hummer",
      "International",
      "Isuzu",
      "IVM",
      "Jetour",
      "JAC",
      "JMC",
      "King Long",
      "Lamborghini",
      "Lancia",
      "Land Rover",
      "Lincoln",
      "MAN",
      "Maruti Suzuki",
      "Maserati",
      "Maxus",
      "Mercury",
      "MG",
      "Mikano ZNA",
      "Mitsubishi",
      "Nord",
      "Oldsmobile",
      "Opel",
      "Polaris",
      "Peugeot",
      "Renault",
      "Rolls-Royce",
      "Saab",
      "Saturn",
      "Seat",
      "Skoda",
      "SsangYong",
      "Subaru",
      "Tata",
      "Tesla",
      "TVS",
      "Volkswagen",
      "Volvo",
      "Wuling",
      "ZX Auto",
      "Toyota",
      "Mercedes-Benz",
      "Lexus",
      "Honda",
      "Hyundai",
      "BMW",
      "Ford",
      "GAC",
      "GMC",
      "Infiniti",
      "Jaguar",
      "Jeep",
      "Kia",
      "Mazda",
      "Mini",
      "Nissan",
      "Pontiac",
      "Porsche",
      "Rover",
      "Scion",
      "Tesla",
      "Volkswagen",
      "Other Brand",
    ],
    colors: [
      "Beige",
      "Black",
      "Blue",
      "Brown",
      "Burgundy",
      "Gold",
      "Gray",
      "Green",
      "Ivory",
      "Matt Black",
      "Off white",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Silver",
      "Teal",
      "White",
      "Yellow",
      "Other Color",
    ],
    years: [
      "1987 - 1991",
      "1992 - 1996",
      "1997 - 2001",
      "2002 - 2006",
      "2007 - 2011",
      "2012 - 2016",
      "2017 - 2021",
      "2022 - 2026",
      "Other Year",
    ],
  },
  "Buses & Microbuses": {
    brands: [
      "Ashok Leyland",
      "Blue Bird",
      "Chevrolet",
      "Citroen",
      "Daewoo",
      "Daihatsu",
      "Dodge",
      "Fiat",
      "Force",
      "Foton",
      "Freightliner",
      "GMC",
      "Honda",
      "Hyundai",
      "Isuzu",
      "Iveco",
      "IVM",
      "JAC",
      "Jet",
      "Jin Bei",
      "Joylong",
      "Kia",
      "King Long",
      "LDV",
      "Mazda",
      "Mitsubishi",
      "Nissan",
      "Opel",
      "Peugeot",
      "Renault",
      "Scania",
      "Tata",
      "Vauxhall",
      "Volvo",
      "Yutong",
      "Toyota",
      "Volkswagen",
      "Ford",
      "Suzuki",
      "Mercedes-Benz",
      "Other Brand",
    ],
    colors: [
      "Beige",
      "Black",
      "Blue",
      "Brown",
      "Gold",
      "Green",
      "Grey",
      "Orange",
      "Pink",
      "Red",
      "Silver",
      "White",
      "Yellow",
      "Other Color",
    ],
    years: [
      "1972 - 1976",
      "1977 - 1981",
      "1982 - 1986",
      "1987 - 1991",
      "1992 - 1996",
      "1997 - 2001",
      "2002 - 2006",
      "2007 - 2011",
      "2012 - 2016",
      "2017 - 2021",
      "2022 - 2026",
      "Other Years",
    ],
  },
  "Heavy Equipment": {
    brands: [
      "Aerial Platforms",
      "Asphalt Pavers",
      "Backhoe Loaders",
      "Boom Lifts",
      "Bulldozers",
      "Car Lifts",
      "Compactors",
      "Compressors",
      "Concrete Mixers",
      "Concrete Pumps",
      "Container Handlers",
      "Crane Forks",
      "Cranes",
      "Crushers",
      "Drilling Rigs",
      "Dumpers",
      "Farm Machines",
      "Graders",
      "Loaders",
      "LPG Tanks",
      "Mobile Crusher",
      "Pallet Stackers",
      "Piling Machine",
      "Pipe Layers",
      "Planes",
      "Pneumatic Rollers",
      "Road Roller",
      "Scissor Lifts",
      "Storage Tanks",
      "Swamp Buggies",
      "Tar Boilers",
      "Trenchers",
      "Vibratory Rollers",
      "Wagon Drills",
      "Wheel Loaders",
      "Other",
    ],
    colors: [],
    years: [
      "1972 - 1976",
      "1977 - 1981",
      "1982 - 1986",
      "1987 - 1991",
      "1992 - 1996",
      "1997 - 2001",
      "2002 - 2006",
      "2007 - 2011",
      "2012 - 2016",
      "2017 - 2021",
      "2022 - 2026",
      "Other Years",
    ],
  },
  "Trucks & Trailers": {
    brands: [
      "Crane Trucks",
      "Dump Trucks",
      "Fire Fighting Trucks",
      "Food Trucks",
      "Garbage Compactors",
      "Garbage Trucks",
      "Heavy-Duty Trucks",
      "Low-Bed Trucks",
      "Manlift Trucks",
      "Mini Truck",
      "Refrigerator Truck",
      "Rigid Trucks",
      "Self-Loader Trucks",
      "Semi-Trailers",
      "Tank Trucks",
      "Tow Trucks",
      "Tractor Units",
      "Trailers",
      "Other",
    ],
    colors: [],
    years: [
      "1972 - 1976",
      "1977 - 1981",
      "1982 - 1986",
      "1987 - 1991",
      "1992 - 1996",
      "1997 - 2001",
      "2002 - 2006",
      "2007 - 2011",
      "2012 - 2016",
      "2017 - 2021",
      "2022 - 2026",
      "Other Years",
    ],
  },
};
