export type DepositRequestModalProps = {
  requestId: string;
  propertyName: string;
  tenant_id?: string;
  state: string;
  unitDetails: string;
  branch: string;
  amount: string;
  status?: "pending" | "completed" | "progress" | "approved";
  request_from?: string;
  is_inventory?: boolean;
  is_examine?: boolean;
  is_maintain?: boolean;
  inventory_at?: string | null;
  examined_at?: string | null;
  maintain_at?: string | null;
  rejected_at?: string | null;
  inventory_by?: string | null;
  examine_by?: string | null;
  maintain_by?: string | null;
  created_at?: string | null;
  refunded_amount?: string | null;
  resolved_by?: string | null;
  resolved_date?: string | null;
  onDataUpdate?: () => void;
  has_inventory?: boolean;
  inventory?: { src: string; isVideo: boolean}[];
};
