import { getBackgroundColor } from "@/app/(nav)/dashboard/data";
import { Field } from "@/components/Table/types";
import {
  BuildingIcon,
  LandlordIcon,
  TenantIcon,
  BedIcon,
  ExpiredIcon,
  InvoiceIcon,
  InquiriesIcon,
  ComplaintsIcon,
  ListingsIcon,
} from "@/public/icons/dashboard-cards/icons";
import { format, subDays } from "date-fns";

export const initialPropertyDevDashboardStats = [
  {
    title: "Properties",
    bg: getBackgroundColor("properties"),
    icon: BuildingIcon,
    value: "0",
    subValue: "0",
    link: "/management/properties/",
  },
  {
    title: "Units",
    bg: getBackgroundColor("landlords"),
    icon: LandlordIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
  {
    title: "Investors",
    bg: getBackgroundColor("tenants & occupants"),
    icon: TenantIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
  {
    title: "Owner",
    bg: getBackgroundColor("vacant unit"),
    icon: BedIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
  {
    title: "Client",
    bg: getBackgroundColor("expired"),
    icon: ExpiredIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
  {
    title: "Listing",
    bg: getBackgroundColor("invoices"),
    icon: InvoiceIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
  {
    title: "Available Sales",
    bg: getBackgroundColor("inquiries"),
    icon: InquiriesIcon,
    value: "0",
    subValue: "0",
    link: "/tasks/inquires",
  },
  {
    title: "Invoices",
    bg: getBackgroundColor("complaints"),
    icon: ComplaintsIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
  {
    title: "Application",
    bg: getBackgroundColor("listings"),
    icon: ListingsIcon,
    value: "0",
    subValue: "0",
    link: "#",
  },
];

export const propertyDevDummyTasks = [
  {
    id: "1",
    columnId: "rejected",
    // officer: "John Doe",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "rejected",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "2",
    columnId: "rejected",
    // email: "email@gmail.com",
    // officer: "John Doe",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "rejected",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "3",
    // officer: "John Doe",
    // email: "email@gmail.com",
    columnId: "rejected",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "rejected",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "4",
    columnId: "processing",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "processing",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "5",
    columnId: "processing",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "processing",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "6",
    // officer: "John Doe",
    columnId: "approved",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "7",
    columnId: "approved",
    // officer: "John Doe",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "8",
    columnId: "approved",
    // officer: "John Doe",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "9",
    columnId: "approved",
    // officer: "John Doe",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "10",
    columnId: "approved",
    // officer: "John Doe",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "11",
    columnId: "approved",
    // email: "email@gmail.com",
    // officer: "John Doe",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "12",
    // officer: "John Doe",
    // email: "email@gmail.com",
    columnId: "approved",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
  {
    id: "13",
    // officer: "John Doe",
    columnId: "approved",
    // email: "email@gmail.com",
    content: {
      messageCount: 2,
      linkCount: 1,
      userAvatars: [
        "/empty/avatar.png",
        "/empty/avatar.png",
        "/empty/avatar.png",
      ],
      // date_time: "25 Jan 2024 (02:30pm)",
      date: "25 Jan 2024",
      status: "approved",
      progress: 50,
    },
    name: "John Doe",
    title: "Project Manager",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    avatarSrc: "/empty/avatar.png",
  },
];


export const dashboardPerformanceChartData = [
  { date: "2024-09-01", profits: 50, sales: 70, expenses: 30 },
  { date: "2024-09-02", profits: 90, sales: 100, expenses: 60 },
  { date: "2024-09-03", profits: 30, sales: 40, expenses: 20 },
  { date: "2024-09-08", profits: 110, sales: 120, expenses: 80 },
  { date: "2024-08-18", profits: 60, sales: 70, expenses: 50 },
  { date: "2024-08-20", profits: 130, sales: 150, expenses: 90 },
  { date: "2024-08-28", profits: 80, sales: 100, expenses: 60 },
  { date: "2024-09-30", profits: 120, sales: 140, expenses: 100 },
];

export const dashboardListingsChartData = Array.from({ length: 90 }, (_, i) => {
  const date = subDays(new Date(), i);
  return {
    date: format(date, "yyyy-MM-dd"),
    views: Math.floor(Math.random() * 100) + 50,
    enquiries: Math.floor(Math.random() * 50) + 20,
  };
}).reverse();

export const invoiceTableFields: Field[] = [
  {
    id: "1",
    accessor: "client_picture",
    isImage: true,
    picSize: 40,
  },
  {
    id: "2",
    label: "Name",
    accessor: "client_name",
  },
  { id: "3", label: "Invoice ID", accessor: "invoice_id" },
  {
    id: "4",
    label: "Details",
    accessor: "payment_reason",
    cellStyle: {
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
      maxWidth: "350px",
    },
  },
  { id: "5", label: "Total Amount", accessor: "total_amount" },
  { id: "6", label: "Date", accessor: "invoice_date" },
];

export const dashboardInvoiceTableData = Array.from(
  { length: 15 },
  (_, index) => {
    const names = [
      "Samuel Fiyinfoluwa",
      "Dada Teniola Emmanuel",
      "Abdulrafiu Mubi",
    ];
    return {
      id: `${index + 1}`,
      picture: "/empty/SampleLandlord.jpeg",
      name: names[index % names.length],
      invoice_id: `INV${index + 1}`,
      details:
        "Rent Cost: Start date: September 02, 2024. Rent Cost: Start date: September 02, 2024.",
      total_amount: `₦${(
        Math.floor(Math.random() * 20000) + 102000
      ).toLocaleString()}`,
      date: "12/12/2034",
    };
  }
);
