import { TenantPageData } from "@/app/(nav)/management/tenants/data";
import { BadgeIconColors } from "@/components/BadgeIcon/badge-icon";
import type { UserCardProps } from "@/components/Management/landlord-and-tenant-card";
import { ClientPageData } from "./types";
import { Field } from "@/components/Table/types";

export const dummyTenants: UserCardProps[] = [
  {
    id: "1",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "John Doe",
    title: "Software Engineer",
    email: "john.doe@example.com",
    phone_number: "+2348012345678",
    user_tag: "web",
    badge_color: "green" as BadgeIconColors,
    other_info: "Lives in Lagos",
    note: true,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "2",
    picture_url: "/empty/SampleLandlord.jpeg",
    name: "Jane Smith",
    title: "Product Designer",
    email: "jane.smith@example.com",
    phone_number: "+2348098765432",
    user_tag: "mobile",
    badge_color: "blue" as BadgeIconColors,
    other_info: "Lives in Abuja",
    note: false,
    is_flagged: false,
    is_verified: false,
    is_active: true,
    isOnline: false,
  },
  {
    id: "3",
    picture_url: "/empty/SampleLandlord.jpeg",
    name: "Michael Johnson",
    title: "Accountant",
    email: "michael.j@example.com",
    phone_number: "+2348056789012",
    user_tag: "mobile",
    badge_color: "red" as BadgeIconColors,
    other_info: "Lives in Port Harcourt",
    note: true,
    is_flagged: true,
    is_verified: false,
    is_active: false,
    isOnline: false,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
  {
    id: "4",
     picture_url: "/empty/SampleLandlord.jpeg",
    name: "Sarah Williams",
    title: "HR Manager",
    email: "sarah.w@example.com",
    phone_number: "+2348076543210",
    user_tag: "web",
    badge_color: "yellow" as BadgeIconColors,
    other_info: "Lives in Kano",
    note: false,
    is_flagged: false,
    is_verified: true,
    is_active: true,
    isOnline: true,
  },
];

export const dummyClientPageData: ClientPageData = {
  clients: dummyTenants,
  total_clients: 24,
  new_clients_this_month: 3,
  web_clients: 10,
  new_web_clients_this_month: 1,
  mobile_clients: 14,
  new_mobile_clients_this_month: 2,
  current_page: 1,
  total_pages: 3,
};

export const clientTableFields: Field[] = [
  {
    id: "1",
    accessor: "picture_url",
    isImage: true,
    cellStyle: { paddingRight: "4px" },
  },
  {
    id: "2",
    accessor: "full_name",
    cellStyle: {
      paddingLeft: "4px",
      fontWeight: 700,
      color: "#000",
    },
  },
  {
    id: "3",
    accessor: "email",
    cellStyle: {
      whiteSpace: "nowrap",
    },
  },
  {
    id: "4",
    accessor: "phone_number",
    cellStyle: {
      whiteSpace: "nowrap",
    },
  },
  { id: "5", accessor: "user_tag" },
  { id: "6", accessor: "manage/chat" },
];
